import { DicionarioTraducao } from "./tipos";

export const dicionarioCalculadora: DicionarioTraducao = {
  "(-) Custo de Energia": { en: "(-) Electricity Cost", es: "(-) Coste de Energía" },
  "(-) Custo de Insumos": { en: "(-) Supplies Cost", es: "(-) Coste de Insumos" },
  "(-) Custo de Materiais": { en: "(-) Materials Cost", es: "(-) Coste de Materiales" },
  "(-) Depreciação": { en: "(-) Depreciation", es: "(-) Depreciación" },
  "(-) Despesas Fixas (Gerais)": { en: "(-) Fixed Overhead Expenses", es: "(-) Gastos Fijos (Generales)" },
  "(=) Margem de Contribuição": { en: "(=) Contribution Margin", es: "(=) Margen de Contribución" },
  "+ Embalagem": { en: "+ Packaging", es: "+ Embalaje" },
  "+ Lixamento": { en: "+ Sanding", es: "+ Lijado" },
  "+ Mimo": { en: "+ Freebie/Gift", es: "+ Detalle/Regalo" },
  "+ Outro": { en: "+ Other", es: "+ Otro" },
  "+ Pintura Básica": { en: "+ Basic Painting", es: "+ Pintura Básica" },
  "+ Pintura Detalhada": { en: "+ Detailed Painting", es: "+ Pintura Detallada" },
  "+ Primer": { en: "+ Primer", es: "+ Imprimación" },
  "+ Verniz": { en: "+ Varnish/Clearcoat", es: "+ Barniz" },
  "🔩 Insumos Logísticos & Pós-Processamento": { en: "🔩 Logistics & Post-Processing Supplies", es: "🔩 Insumos Logísticos y Pospocesado" },
  "15% de perda adicionados ao cálculo!": { en: "15% waste added to calculation!", es: "¡15% de merma añadida al cálculo!" },
  "Abrir no WhatsApp": { en: "Open in WhatsApp", es: "Abrir en WhatsApp" },
  "Acabamento": { en: "Finishing", es: "Acabado" },
  "Aceito a proposta de serviços e autorizo o início da fabricação do lote técnico.": { en: "I accept the service proposal and authorize the start of manufacturing for the technical batch.", es: "Acepto la propuesta de servicios y autorizo el inicio de fabricación del lote técnico." },
  "Action Figure": { en: "Action Figure", es: "Figura de Acción" },
  "Adicionar ao catálogo": { en: "Add to catalog", es: "Añadir al catálogo" },
  "Adicionar nova peça (linha zerada)": { en: "Add new part (blank row)", es: "Añadir nueva pieza (línea vacía)" },
  "Adicionar Novo Insumo": { en: "Add New Supply", es: "Añadir Nuevo Insumo" },
  "Adicionar Novo Material": { en: "Add New Material", es: "Añadir Nuevo Material" },
  "Aguardando dados": { en: "Waiting for data", es: "Esperando datos" },
  "Aguardando Máquina": { en: "Waiting for Machine", es: "Esperando Máquina" },
  "Ajustar": { en: "Adjust", es: "Ajustar" },
  "Alta Rentabilidade (Excelente lucro)": { en: "High Profitability (Excellent margin)", es: "Alta Rentabilidad (Excelente margen)" },
  "Análise técnica de fatiamento, risco operacional e posicionamento comercial": { en: "Technical slicing analysis, operational risk and commercial positioning", es: "Análisis técnico de laminado, riesgo operativo y posicionamiento comercial" },
  "apenas de 1 peça": { en: "for 1 part only", es: "solo para 1 pieza" },
  "Aprovar": { en: "Approve", es: "Aprobar" },
  "Armazém de Insumos": { en: "Supplies Warehouse", es: "Almacén de Insumos" },
  "Armazém de Materiais": { en: "Materials Warehouse", es: "Almacén de Materiales" },
  "Assinatura Digital do Emissor": { en: "Issuer Digital Signature", es: "Firma Digital del Emisor" },
  "Atividades manuais como lixar, aplicar primer, pintar ou dar banho de álcool/isopropílico na peça após a impressão.": { en: "Manual labor such as sanding, priming, painting or IPA wash after printing.", es: "Mano de obra como lijado, imprimación, pintura o baño de alcohol tras la impresión." },
  "Atualizar": { en: "Update", es: "Actualizar" },
  "Auto-ajuste": { en: "Auto-adjust", es: "Autoajuste" },
  "Baixar arquivo local": { en: "Download local file", es: "Descargar archivo local" },
  "Baixar Proposta em PDF": { en: "Download Proposal PDF", es: "Descargar Presupuesto en PDF" },
  "Baixo Custo": { en: "Low Cost", es: "Bajo Coste" },
  "Baixo Risco": { en: "Low Risk", es: "Bajo Riesgo" },
  "Buscando detalhes do orçamento...": { en: "Retrieving quote details...", es: "Buscando detalles del presupuesto..." },
  "Buscar material...": { en: "Search material...", es: "Buscar material..." },
  "Calcular frete automático (BrasilAPI)": { en: "Calculate automatic shipping", es: "Calcular envío automático" },
  "Canais de Venda": { en: "Sales Channels", es: "Canales de Venta" },
  "Canais de Venda e Logística": { en: "Sales Channels & Logistics", es: "Canales de Venta y Logística" },
  "Canal Ativo": { en: "Active Channel", es: "Canal Activo" },
  "Carregando Proposta": { en: "Loading Proposal", es: "Cargando Propuesta" },
  "Cliente Destinatário": { en: "Recipient Client", es: "Cliente Destinatario" },
  "Cliente do Projeto": { en: "Project Customer", es: "Cliente del Proyecto" },
  "Cobra um adicional no orçamento para cobrir possíveis peças perdidas": { en: "Charges an additional amount in the quote to cover potential failed parts", es: "Añade un recargo al presupuesto para cubrir posibles piezas fallidas" },
  "Código:": { en: "Code:", es: "Código:" },
  "Comissão (%)": { en: "Commission (%)", es: "Comisión (%)" },
  "Comissão Marketplace": { en: "Marketplace Commission", es: "Comisión de Marketplace" },
  "Complementos do projeto": { en: "Project add-ons", es: "Complementos del proyecto" },
  "Componentes adicionais de montagem, lixamento técnico e remoção manual de suportes.": { en: "Additional assembly hardware, technical sanding and manual support removal.", es: "Componentes adicionales de montaje, lijado técnico y retirada manual de soportes." },
  "Condições e Prazos Adicionais": { en: "Additional Terms & Deadlines", es: "Condiciones y Plazos Adicionales" },
  "Configurações da Calculadora": { en: "Calculator Settings", es: "Configuración de la Calculadora" },
  "Configurações pré-definidas para tipos de projeto": { en: "Presets for project types", es: "Ajustes predefinidos para tipos de proyecto" },
  "Configurações Rápidas": { en: "Quick Settings", es: "Ajustes Rápidos" },
  "Configurações sincronizadas!": { en: "Settings synchronized!", es: "¡Configuraciones sincronizadas!" },
  "Configurar Perfis": { en: "Configure Profiles", es: "Configurar Perfiles" },
  "Configure as taxas deste marketplace": { en: "Configure rates for this marketplace", es: "Configure las comisiones de este marketplace" },
  "Configure suas taxas de marketplace": { en: "Configure your marketplace rates", es: "Configure sus comisiones de marketplace" },
  "Confirmar Aceite": { en: "Confirm Acceptance", es: "Confirmar Aceptación" },
  "Consultar CEP": { en: "Lookup ZIP Code", es: "Consultar Código Postal" },
  "Consumo Energético": { en: "Power Consumption", es: "Consumo Energético" },
  "Copiado para a área de transferência!": { en: "Copied to clipboard!", es: "¡Copiado al portapapeles!" },
  "Copiado!": { en: "Copied!", es: "¡Copiado!" },
  "Copiar Proposta": { en: "Copy Proposal", es: "Copiar Presupuesto" },
  "Copilot de Precificação & IA Maker": { en: "Pricing Copilot & Maker AI", es: "Copiloto de Precios e IA Maker" },
  "Cotação de Frete em Tempo Real": { en: "Real-Time Shipping Quote", es: "Cotización de Envío en Tiempo Real" },
  "Custo Fixo (R$)": { en: "Fixed Cost ($)", es: "Coste Fijo (€)" },
  "Custo Fixo por Venda": { en: "Fixed Cost per Sale", es: "Coste Fijo por Venta" },
  "Custo Horário": { en: "Hourly Cost", es: "Coste Horario" },
  "Custo por kWh": { en: "Cost per kWh", es: "Coste por kWh" },
  "Custo Un.": { en: "Unit Cost", es: "Coste Un." },
  "Customize presets e templates": { en: "Customize presets and templates", es: "Personalice preajustes y plantillas" },
  "Custos Adicionais": { en: "Additional Costs", es: "Costes Adicionales" },
  "Custos consolidados de engenharia tridimensional, fatiamento, setup técnico e pós-processamento da peça física.": { en: "Consolidated costs of 3D engineering, slicing, technical setup, and physical part post-processing.", es: "Costes consolidados de ingeniería tridimensional, laminado, configuración técnica y posprocesado de la pieza física." },
  "Custos de plataforma e fretes": { en: "Platform fees and shipping", es: "Comisiones de plataforma y envíos" },
  "Dê um nome para o projeto antes de salvar!": { en: "Give the project a name before saving!", es: "¡Asigne un nombre al proyecto antes de guardar!" },
  "Declinar": { en: "Decline", es: "Rechazar" },
  "Defina a máquina que produzirá o projeto": { en: "Select the machine that will produce the project", es: "Seleccione la máquina que producirá el proyecto" },
  "Depreciação": { en: "Depreciation", es: "Depreciación" },
  "Descreva sua experiência...": { en: "Describe your experience...", es: "Describa su experiencia..." },
  "Descrição Curta": { en: "Short Description", es: "Descripción Corta" },
  "Deseja adicionar custos fixos do negócio?": { en: "Do you want to add fixed business overheads?", es: "¿Desea añadir costes fijos del negocio?" },
  "Deseja ajustar o valor manualmente?": { en: "Want to adjust value manually?", es: "¿Desea ajustar el valor manualmente?" },
  "Desfazer (Ctrl+Z)": { en: "Undo (Ctrl+Z)", es: "Deshacer (Ctrl+Z)" },
  "Detalhamento Financeiro": { en: "Financial Breakdown", es: "Desglose Financiero" },
  "Detalhes do Projeto": { en: "Project Details", es: "Detalles del Proyecto" },
  "Diagnóstico & Risco": { en: "Diagnosis & Risk", es: "Diagnóstico y Riesgo" },
  "Digite um CEP com 8 dígitos": { en: "Enter a valid postal code", es: "Introduzca un código postal válido" },
  "Direto": { en: "Direct", es: "Directo" },
  "Duplicar Orçamento": { en: "Duplicate Quote", es: "Duplicar Presupuesto" },
  "Editar Canal": { en: "Edit Channel", es: "Editar Canal" },
  "Em Manutenção": { en: "Under Maintenance", es: "En Mantenimiento" },
  "Embalagem, Setup de máquina, Operação, etc.": { en: "Packaging, Machine setup, Operation, etc.", es: "Embalaje, Configuración de máquina, Operación, etc." },
  "Embalagens, brindes ou repasse de custos (luz, aluguel) na peça": { en: "Packaging, gifts, or overhead pass-through (power, rent) on the part", es: "Embalajes, regalos o repercusión de costes (luz, alquiler) en la pieza" },
  "Emissão:": { en: "Issue Date:", es: "Emisión:" },
  "Energia (R$)": { en: "Energy ($)", es: "Energía (€)" },
  "Energia Elétrica": { en: "Electricity", es: "Energía Eléctrica" },
  "Enviar com anexo": { en: "Send with attachment", es: "Enviar con adjunto" },
  "Enviar orçamento por e-mail": { en: "Send quote by email", es: "Enviar presupuesto por correo" },
  "Enviar para assinatura": { en: "Send for signature", es: "Enviar para firma" },
  "Enviar para Produção": { en: "Send to Production", es: "Enviar a Producción" },
  "Equipamento": { en: "Equipment", es: "Equipo" },
  "Erro ao buscar CEP via BrasilAPI": { en: "Error looking up postal code", es: "Error al consultar código postal" },
  "Erro ao gerar PDF.": { en: "Error generating PDF.", es: "Error al generar el PDF." },
  "Especificação": { en: "Specification", es: "Especificación" },
  "Especificações da Proposta": { en: "Proposal Specifications", es: "Especificaciones de la Propuesta" },
  "Especificações Técnicas": { en: "Technical Specifications", es: "Especificaciones Técnicas" },
  "Este link mágico parece estar corrompido ou expirado. Entre em contato com o fornecedor.": { en: "This magic link seems corrupted or expired. Please contact the provider.", es: "Este enlace mágico parece estar dañado o caducado. Póngase en contacto con el proveedor." },
  "Este orçamento é válido por 15 dias corridos. Os valores podem sofrer alteração caso o modelo 3D original passe por reajustes.": { en: "This quote is valid for 15 consecutive days. Values may change if the original 3D model is modified.", es: "Este presupuesto es válido durante 15 días naturales. Los valores pueden variar si el modelo 3D original sufre reajustes." },
  "Estimativa baseada em parâmetros manuais.": { en: "Estimate based on manual parameters.", es: "Estimación basada en parámetros manuales." },
  "Estime quantas gramas de filamento ou horas costumam dar errado nesse tipo de peça. O sistema adicionará isso ao custo do cliente.": { en: "Estimate grams of filament or hours that typically fail for this piece. The system will add this to client cost.", es: "Estime los gramos de filamento u horas que suelen fallar en este tipo de pieza. El sistema lo añadirá al coste del cliente." },
  "Estoque de Insumos": { en: "Supplies Stock", es: "Inventario de Insumos" },
  "Estoque Vazio": { en: "Empty Stock", es: "Stock Vacío" },
  "Estratégia de Preenchimento": { en: "Infill Strategy", es: "Estrategia de Relleno" },
  "Estratégias de Preço": { en: "Pricing Strategies", es: "Estrategias de Precios" },
  "Estúdio Principal": { en: "Main Studio", es: "Estudio Principal" },
  "Estúdio removido com sucesso.": { en: "Studio successfully removed.", es: "Estudio eliminado con éxito." },
  "Ex: Action Figure Batman": { en: "e.g.: Batman Action Figure", es: "Ej: Figura de Acción Batman" },
  "Ex: Altura de camada 0.12mm": { en: "e.g.: Layer height 0.12mm", es: "Ej: Altura de capa 0.12mm" },
  "Ex: Embalagem": { en: "e.g.: Packaging", es: "Ej: Embalaje" },
  "Ex: Impressão 3D de alta precisão": { en: "e.g.: High precision 3D printing", es: "Ej: Impresión 3D de alta precisión" },
  "Ex: PrintPro Lab": { en: "e.g.: PrintPro Lab", es: "Ej: PrintPro Lab" },
  "Exclusivo PRO": { en: "PRO Exclusive", es: "Exclusivo PRO" },
  "Existem Custos Adicionais?": { en: "Are there additional costs?", es: "¿Existen costes adicionales?" },
  "Exportar PDF": { en: "Export PDF", es: "Exportar PDF" },
  "Express ⚡": { en: "Express ⚡", es: "Express ⚡" },
  "extra aplicado na peça": { en: "extra applied to part", es: "extra aplicado a la pieza" },
  "Extremo": { en: "Extreme", es: "Extremo" },
  "Fabricação de peças físicas tridimensionais com base no arquivo de fatiamento fornecido. O lote inclui testes iniciais de setup de fabricação para garantia de precisão dimensional.": { en: "Manufacturing of physical 3D parts based on the provided slicing file. The batch includes initial setup test prints to ensure dimensional accuracy.", es: "Fabricación de piezas físicas tridimensionales según el archivo de laminado provisto. El lote incluye pruebas iniciales de configuración para asegurar precisión dimensional." },
  "Falar com o Maker": { en: "Contact Maker", es: "Hablar con el Maker" },
  "Falha ao calcular sugestão de IA.": { en: "Failed to calculate AI suggestion.", es: "Fallo al calcular sugerencia de IA." },
  "Fator multiplicador aplicado ao custo total para chegar ao preço final.": { en: "Multiplier factor applied to total cost to reach final price.", es: "Factor multiplicador aplicado al coste total para obtener el precio final." },
  "Fechar seletor de cliente": { en: "Close customer selector", es: "Cerrar selector de cliente" },
  "Fechar seletor de equipamento": { en: "Close equipment selector", es: "Cerrar selector de equipo" },
  "Feedback enviado para o Lab! 🚀": { en: "Feedback sent to the Lab! 🚀", es: "¡Comentarios enviados al Lab! 🚀" },
  "Filamento Gasto": { en: "Filament Used", es: "Filamento Gastado" },
  "Filamento ou resina técnica de alta performance consumidos na peça principal e suportes.": { en: "High performance technical filament or resin consumed in main body and supports.", es: "Filamento o resina técnica consumidos en la pieza principal y soportes." },
  "Filamento Perdido": { en: "Wasted Filament", es: "Filamento Desperdiciado" },
  "Foco em Precisão": { en: "Precision Focus", es: "Enfoque en Precisión" },
  "Fornecedor / Maker": { en: "Provider / Maker", es: "Proveedor / Maker" },
  "Frete e Envio": { en: "Shipping & Delivery", es: "Envío y Entrega" },
  "Frete Fixo": { en: "Flat Shipping Rate", es: "Envío Fijo" },
  "Gerar Link da Proposta": { en: "Generate Proposal Link", es: "Generar Enlace del Presupuesto" },
  "Gerencie filamentos e resinas": { en: "Manage filaments and resins", es: "Gestione filamentos y resinas" },
  "Gestão de Custos Adicionais": { en: "Additional Costs Management", es: "Gestión de Costes Adicionales" },
  "Histórico de Variações": { en: "Variation History", es: "Historial de Variaciones" },
  "Histórico de Versões": { en: "Version History", es: "Historial de Versiones" },
  "Identificação do Orçamento": { en: "Quote Identification", es: "Identificación del Presupuesto" },
  "Identificação do Projeto": { en: "Project Identification", es: "Identificación del Proyecto" },
  "Impacto Direto": { en: "Direct Impact", es: "Impacto Directo" },
  "Impressões com mais de 6h bloqueiam a mesa por turnos inteiros. Utilize a estratégia Recomendada ou Premium para cobrir a ociosidade do equipamento.": { en: "Prints over 6h tie up the bed for whole shifts. Use Recommended or Premium strategy to cover machine idle time.", es: "Impresiones de más de 6h bloquean la cama por turnos enteros. Use la estrategia Recomendada o Premium para cubrir el tiempo ocioso." },
  "Impressora Principal": { en: "Primary Printer", es: "Impresora Principal" },
  "Índice de Perda": { en: "Loss Rate", es: "Índice de Pérdida" },
  "Índice de Risco Operacional": { en: "Operational Risk Index", es: "Índice de Riesgo Operacional" },
  "Inserir ou buscar cliente...": { en: "Enter or search customer...", es: "Introducir o buscar cliente..." },
  "Insira pesos e tempos nos cards ao lado": { en: "Enter weights and times in the side cards", es: "Introduzca pesos y tiempos en las tarjetas laterales" },
  "Insumos & Extras": { en: "Supplies & Extras", es: "Insumos y Extras" },
  "Item": { en: "Item", es: "Artículo" },
  "Itens Adicionais": { en: "Additional Items", es: "Elementos Adicionales" },
  "Itens extras que você gasta no projeto além do filamento ou resina, como super-cola, tinta, verniz ou embalagens.": { en: "Extra project items beyond filament or resin, such as superglue, paint, varnish or packaging.", es: "Elementos extras además de filamento o resina, como pegamento, pintura, barniz o embalajes." },
  "kWh (R$)": { en: "kWh ($)", es: "kWh (€)" },
  "Lab de Protótipos": { en: "Prototypes Lab", es: "Lab de Prototipos" },
  "Limpar Tudo / Resetar": { en: "Clear All / Reset", es: "Limpiar Todo / Restablecer" },
  "Link Mágico Copiado": { en: "Magic Link Copied", es: "Enlace Mágico Copiado" },
  "Link Mágico copiado para a Área de Transferência!": { en: "Magic Link copied to Clipboard!", es: "¡Enlace Mágico copiado al Portapapeles!" },
  "Link público de orçamento copiado para envio ao cliente.": { en: "Public quote link copied to send to client.", es: "Enlace público de presupuesto copiado para enviar al cliente." },
  "Lixamento": { en: "Sanding", es: "Lijado" },
  "Lixamento, Primer, Pintura e Verniz": { en: "Sanding, Primer, Painting & Varnish", es: "Lijado, Imprimación, Pintura y Barniz" },
  "Logística e Precificação": { en: "Logistics & Pricing", es: "Logística y Precios" },
  "Lote Produzido": { en: "Batch Produced", es: "Lote Producido" },
  "Lote Técnico Especificado": { en: "Technical Batch Specified", es: "Lote Técnico Especificado" },
  "M. Livre": { en: "Mercado Libre / Marketplace", es: "Mercado Libre" },
  "Manufatura 3D sob Demanda": { en: "On-Demand 3D Manufacturing", es: "Fabricación 3D bajo Demanda" },
  "Mão de obra / h": { en: "Labor / h", es: "Mano de obra / h" },
  "Máquina": { en: "Machine", es: "Máquina" },
  "Margem": { en: "Margin", es: "Margen" },
  "Margem + Custos Extras": { en: "Margin + Extra Costs", es: "Margen + Costes Extras" },
  "Margem Competitiva (Ideal para volume)": { en: "Competitive Margin (Ideal for volume)", es: "Margen Competitivo (Ideal para volumen)" },
  "Margem de Lucro Desejada": { en: "Desired Profit Margin", es: "Margen de Beneficio Deseado" },
  "Margem de Risco (Lucro muito baixo)": { en: "Risk Margin (Very low profit)", es: "Margen de Riesgo (Beneficio muy bajo)" },
  "Margem de Risco Detectada!": { en: "Risk Margin Detected!", es: "¡Margen de Riesgo Detectado!" },
  "Margem Lucro": { en: "Profit Margin", es: "Margen Beneficio" },
  "Margem Real": { en: "Real Margin", es: "Margen Real" },
  "Massa Estimada": { en: "Estimated Mass", es: "Masa Estimada" },
  "Materiais e Consumo": { en: "Materials & Consumption", es: "Materiales y Consumo" },
  "Materiais e Insumos": { en: "Materials & Supplies", es: "Materiales e Insumos" },
  "Mesa / Lote": { en: "Bed / Batch", es: "Cama / Lote" },
  "Metricas de tempo e hardware": { en: "Time & hardware metrics", es: "Métricas de tiempo y hardware" },
  "Modelagem 3D": { en: "3D Modeling", es: "Modelado 3D" },
  "Modelagem 3D sob medida e adequação de peças": { en: "Custom 3D modeling and part adaptation", es: "Modelado 3D a medida y adaptación de piezas" },
  "Mostrar favoritos primeiro": { en: "Show favorites first", es: "Mostrar favoritos primero" },
  "Mostrar os mais usados primeiro": { en: "Show most used first", es: "Mostrar los más usados primero" },
  "Motores base de custeio": { en: "Core costing engines", es: "Motores base de costes" },
  "Multiplicador (Markup):": { en: "Multiplier (Markup):", es: "Multiplicador (Markup):" },
  "Não é possível remover o único estúdio existente.": { en: "Cannot remove the only existing studio.", es: "No es posible eliminar el único estudio existente." },
  "Não foi possível copiar.": { en: "Unable to copy.", es: "No se pudo copiar." },
  "Nenhum acabamento": { en: "No finish", es: "Sin acabado" },
  "Nenhum custo fixo": { en: "No fixed overhead", es: "Sin costes fijos" },
  "Nenhum insumo cadastrado ainda. Adicione agora para começar.": { en: "No supplies registered yet. Add now to start.", es: "Ningún insumo registrado todavía. Añada ahora para empezar." },
  "Nenhum material cadastrado ainda. Adicione agora para começar.": { en: "No materials registered yet. Add now to start.", es: "Ningún material registrado todavía. Añada ahora para empezar." },
  "Nenhum snapshot salvo ainda.": { en: "No snapshot saved yet.", es: "Ningún snapshot guardado todavía." },
  "Nome do Canal": { en: "Channel Name", es: "Nombre del Canal" },
  "Nome do custo...": { en: "Cost name...", es: "Nombre del coste..." },
  "NOME DO ORÇAMENTO...": { en: "QUOTE NAME...", es: "NOMBRE DEL PRESUPUESTO..." },
  "Nome do processo...": { en: "Process name...", es: "Nombre del proceso..." },
  "Nome do Projeto": { en: "Project Name", es: "Nombre del Proyecto" },
  "Novo Canal": { en: "New Channel", es: "Nuevo Canal" },
  "Novo Custo": { en: "New Cost", es: "Nuevo Coste" },
  "Novo Estúdio (Fase 3)": { en: "New Studio (Phase 3)", es: "Nuevo Estudio (Fase 3)" },
  "Novo Orçamento": { en: "New Quote", es: "Nuevo Presupuesto" },
  "NOVO TEMPLATE": { en: "NEW TEMPLATE", es: "NUEVA PLANTILLA" },
  "O envio e aceite nesta proposta configura sinal verde para inclusão imediata na fila de produção física do Maker. O tempo estimado de impressão está sujeito ao fluxo da oficina.": { en: "Submitting and accepting this proposal provides the green light for immediate inclusion in the Maker's physical production queue. Estimated print time is subject to shop flow.", es: "El envío y aceptación de esta propuesta da luz verde para la inclusión inmediata en la cola de producción física del Maker. El tiempo estimado de impresión está sujeto al flujo del taller." },
  "O proponente maker foi notificado sobre a recusa do lote.": { en: "The maker proponent was notified of the batch rejection.", es: "El proponente maker ha sido notificado sobre el rechazo del lote." },
  "O tempo gasto no computador desenhando a peça do zero, ajustando as dimensões de um modelo pronto ou fatiando para a máquina.": { en: "Computer time spent designing from scratch, adjusting dimensions or slicing.", es: "Tiempo frente al ordenador diseñando desde cero, ajustando dimensiones o laminando." },
  "O valor que você cobra do cliente para juntar dinheiro e comprar uma máquina nova quando essa quebrar.": { en: "The amount charged to save up and replace the machine when it reaches end of life.", es: "El valor que cobra al cliente para ahorrar y reponer la máquina cuando termine su vida útil." },
  "O valor recomendado oferece o melhor equilíbrio entre conversão rápida e saúde financeira do seu maquinário.": { en: "The recommended value offers the best balance between fast conversion and equipment financial health.", es: "El valor recomendado ofrece el mejor equilibrio entre conversión rápida y salud financiera de la máquina." },
  "Observações Técnicas": { en: "Technical Notes", es: "Observaciones Técnicas" },
  "Oficial ANEEL": { en: "Official Tariff", es: "Tarifa Oficial" },
  "Opções de Exportação": { en: "Export Options", es: "Opciones de Exportación" },
  "Operação e Setup": { en: "Operation & Setup", es: "Operación y Setup" },
  "Operacional": { en: "Operational", es: "Operativo" },
  "Operador": { en: "Operator", es: "Operador" },
  "Orçamento de Manufatura 3D": { en: "3D Manufacturing Quote", es: "Presupuesto de Fabricación 3D" },
  "Orçamento recuperado com sucesso!": { en: "Quote restored successfully!", es: "¡Presupuesto recuperado con éxito!" },
  "Orçamento resetado com sucesso!": { en: "Quote reset successfully!", es: "¡Presupuesto restablecido con éxito!" },
  "Orçamento restaurado!": { en: "Quote restored!", es: "¡Presupuesto restaurado!" },
  "Orçamento Salvo": { en: "Quote Saved", es: "Presupuesto Guardado" },
  "Orçamento salvo com sucesso!": { en: "Quote saved successfully!", es: "¡Presupuesto guardado con éxito!" },
  "Orçamento salvo e sincronizado!": { en: "Quote saved and synced!", es: "¡Presupuesto guardado y sincronizado!" },
  "Orçamento salvo localmente!": { en: "Quote saved locally!", es: "¡Presupuesto guardado localmente!" },
  "Orçamento salvo na versão 2.0!": { en: "Quote saved in version 2.0!", es: "¡Presupuesto guardado en la versión 2.0!" },
  "Otimização Inteligente": { en: "Smart Optimization", es: "Optimización Inteligente" },
  "Otimizar IA": { en: "Optimize AI", es: "Optimizar IA" },
  "Padrão": { en: "Standard", es: "Estándar" },
  "Padrão do estúdio": { en: "Studio default", es: "Predeterminado del estudio" },
  "Para clientes corporativos (B2B), a previsibilidade de prazo e acabamento técnico sobrepõem o preço unitário. A estratégia Recomendada ou Premium tem excelente aceitação.": { en: "For B2B clients, predictable turnaround and technical finish outweigh unit price. Recommended or Premium has high acceptance.", es: "Para clientes B2B, la previsibilidad del plazo y el acabado técnico prevalecen sobre el precio. La estrategia Recomendada o Premium tiene gran aceptación." },
  "PDF Exportado": { en: "PDF Exported", es: "PDF Exportado" },
  "PDF gerado com sucesso!": { en: "PDF generated successfully!", es: "¡PDF generado con éxito!" },
  "Peça Técnica": { en: "Technical Part", es: "Pieza Técnica" },
  "Peça Única": { en: "Single Part", es: "Pieza Única" },
  "Perdas & Falhas": { en: "Losses & Failures", es: "Pérdidas y Fallos" },
  "Perfil de Vida Útil": { en: "Lifespan Profile", es: "Perfil de Vida Útil" },
  "Perfis de Projeto": { en: "Project Profiles", es: "Perfiles de Proyecto" },
  "Personalizar Orçamento": { en: "Customize Quote", es: "Personalizar Presupuesto" },
  "Personalize orçamentos e operacional": { en: "Customize quotes and operations", es: "Personalice presupuestos y operaciones" },
  "Peso Estimado": { en: "Estimated Weight", es: "Peso Estimado" },
  "Peso Total Descartado": { en: "Total Discarded Weight", es: "Peso Total Descartado" },
  "Pintura Básica": { en: "Basic Painting", es: "Pintura Básica" },
  "Pintura Detalhada": { en: "Detailed Painting", es: "Pintura Detallada" },
  "Piso / Atacado": { en: "Floor / Wholesale", es: "Suelo / Mayorista" },
  "Preço Calculado Atual": { en: "Current Calculated Price", es: "Precio Calculado Actual" },
  "Preço de Mercado": { en: "Market Price", es: "Precio de Mercado" },
  "Preço Mínimo Viável": { en: "Minimum Viable Price", es: "Precio Mínimo Viable" },
  "Preço Otimizado por IA": { en: "AI Optimized Price", es: "Precio Optimizado por IA" },
  "Preço Recomendado": { en: "Recommended Price", es: "Precio Recomendado" },
  "Prejuízo ou Margem Nula!": { en: "Loss or Zero Margin!", es: "¡Pérdida o Margen Nulo!" },
  "Prejuízo Total": { en: "Total Loss", es: "Pérdida Total" },
  "Premium": { en: "Premium", es: "Premium" },
  "Preparação e Setup Operacional": { en: "Preparation & Operational Setup", es: "Preparación y Configuración Operativa" },
  "Presets Rápidos": { en: "Quick Presets", es: "Preajustes Rápidos" },
  "PrintLog OS": { en: "PrintLog OS", es: "PrintLog OS" },
  "Processo": { en: "Process", es: "Proceso" },
  "Produção e Impressão": { en: "Production & Printing", es: "Producción e Impresión" },
  "Projeto Completo": { en: "Full Project", es: "Proyecto Completo" },
  "PROPOSTA APROVADA DIGITALMENTE": { en: "PROPOSAL DIGITALLY APPROVED", es: "PROPUESTA APROBADA DIGITALMENTE" },
  "PROPOSTA COMERCIAL": { en: "COMMERCIAL PROPOSAL", es: "PROPUESTA COMERCIAL" },
  "Proposta comercial copiada para a área de transferência!": { en: "Commercial proposal copied to clipboard!", es: "¡Propuesta comercial copiada al portapapeles!" },
  "PROPOSTA DE SERVIÇO": { en: "SERVICE PROPOSAL", es: "PROPUESTA DE SERVICIO" },
  "PROPOSTA DECLINADA PELO CLIENTE": { en: "PROPOSAL DECLINED BY CLIENT", es: "PROPUESTA RECHAZADA POR EL CLIENTE" },
  "Proposta Inválida": { en: "Invalid Proposal", es: "Presupuesto Inválido" },
  "Proposta Selecionada": { en: "Selected Proposal", es: "Propuesta Seleccionada" },
  "Proposta WhatsApp": { en: "WhatsApp Proposal", es: "Propuesta de WhatsApp" },
  "Proposta:": { en: "Proposal:", es: "Propuesta:" },
  "Protótipo (Rápido)": { en: "Prototype (Fast)", es: "Prototipo (Rápido)" },
  "Quantidade de Peças (Lotes):": { en: "Number of Parts (Batches):", es: "Cantidad de Piezas (Lotes):" },
  "Recalcular com outra variação de IA": { en: "Recalculate with another AI variation", es: "Recalcular con otra variante de IA" },
  "Recomendações Práticas da IA para a Produção": { en: "Practical AI Recommendations for Production", es: "Recomendaciones Prácticas de IA para Producción" },
  "Recomendado": { en: "Recommended", es: "Recomendado" },
  "Redirecionando para a tela de Upgrade...": { en: "Redirecting to Upgrade screen...", es: "Redirigiendo a la pantalla de Upgrade..." },
  "Refazer (Ctrl+Y)": { en: "Redo (Ctrl+Y)", es: "Rehacer (Ctrl+Y)" },
  "Remover esta peça": { en: "Remove this part", es: "Eliminar esta pieza" },
  "Resetar": { en: "Reset", es: "Restablecer" },
  "Resetar Orçamento?": { en: "Reset Quote?", es: "¿Restablecer Presupuesto?" },
  "Resina Gasta": { en: "Resin Used", es: "Resina Gastada" },
  "Resumo Financeiro": { en: "Financial Summary", es: "Resumen Financiero" },
  "Risco Crítico": { en: "Critical Risk", es: "Riesgo Crítico" },
  "Risco Elevado": { en: "High Risk", es: "Riesgo Elevado" },
  "Risco Moderado": { en: "Moderate Risk", es: "Riesgo Moderado" },
  "Saldo": { en: "Balance", es: "Saldo" },
  "Salvamento Automático": { en: "Auto-Save", es: "Autoguardado" },
  "Salvar Manualmente": { en: "Save Manually", es: "Guardar Manualmente" },
  "Salvar Orçamento": { en: "Save Quote", es: "Guardar Presupuesto" },
  "Salvar Projeto": { en: "Save Project", es: "Guardar Proyecto" },
  "Salvo localmente (Erro na nuvem).": { en: "Saved locally (Cloud error).", es: "Guardado localmente (Error en la nube)." },
  "Selecione como a inteligência deve processar os dados": { en: "Select how the intelligence should process data", es: "Seleccione cómo la inteligencia debe procesar los datos" },
  "Selecione insumos para calcular": { en: "Select supplies to calculate", es: "Seleccione insumos para calcular" },
  "Selecione itens para calcular": { en: "Select items to calculate", es: "Seleccione elementos para calcular" },
  "Selecione para aplicar": { en: "Select to apply", es: "Seleccione para aplicar" },
  "Selecione um canal": { en: "Select a channel", es: "Seleccione un canal" },
  "Sem margem adicionada": { en: "No margin added", es: "Sin margen añadido" },
  "Serviço / Processo": { en: "Service / Process", es: "Servicio / Proceso" },
  "Serviços e Adicionais": { en: "Services & Add-ons", es: "Servicios y Adicionales" },
  "Setup físico da impressora, calibração, troca de bicos/resinas e otimização geométrica do fatiamento.": { en: "Printer physical setup, calibration, nozzle/resin change and slicing geometry optimization.", es: "Configuración física, calibración, cambio de boquilla/resina y optimización geométrica del laminado." },
  "Seu Inventário": { en: "Your Inventory", es: "Su Inventario" },
  "Seus Canais": { en: "Your Channels", es: "Sus Canales" },
  "Severo": { en: "Severe", es: "Severo" },
  "Shopee": { en: "Shopee", es: "Shopee" },
  "Sim, apagar tudo": { en: "Yes, clear everything", es: "Sí, borrar todo" },
  "Slogan / Frase de Rodapé": { en: "Slogan / Footer Tagline", es: "Eslogan / Frase de Pie de Página" },
  "Snapshot removido!": { en: "Snapshot removed!", es: "¡Snapshot eliminado!" },
  "Sua opinião molda o futuro do PrintLog.": { en: "Your feedback shapes the future of PrintLog.", es: "Su opinión moldea el futuro de PrintLog." },
  "Sugestão via Inteligência Artificial": { en: "AI-Powered Suggestion", es: "Sugerencia con Inteligencia Artificial" },
  "Taxa de Comissão (%)": { en: "Commission Fee (%)", es: "Comisión Porcentual (%)" },
  "Taxa de Risco / Falha": { en: "Risk / Failure Margin", es: "Margem de Riesgo / Fallo" },
  "Taxa Fixa (R$)": { en: "Fixed Fee ($)", es: "Tasa Fija (€)" },
  "Taxa Fixa Plataforma": { en: "Platform Fixed Fee", es: "Comisión Fija de Plataforma" },
  "Tecnologia": { en: "Technology", es: "Tecnología" },
  "Tem certeza que deseja apagar todo o orçamento atual e começar do zero? Esta ação limpará todos os materiais, insumos e custos informados.": { en: "Are you sure you want to clear the entire current quote and start from scratch? This action will clear all materials, supplies, and costs entered.", es: "¿Está seguro de que desea borrar todo el presupuesto actual y empezar de cero? Esta acción borrará todos los materiales, insumos y costes informados." },
  "Templates de Projeto": { en: "Project Templates", es: "Plantillas de Proyecto" },
  "Tempo (Min)": { en: "Time (Min)", es: "Tiempo (Min)" },
  "Tempo de Fatiamento": { en: "Slicing Time", es: "Tiempo de Laminado" },
  "Tempo de Impressão": { en: "Print Time", es: "Tiempo de Impresión" },
  "Tempo de Máquina": { en: "Machine Time", es: "Tiempo de Máquina" },
  "Tempo de Operador": { en: "Operator Time", es: "Tiempo de Operario" },
  "Tempo de Processamento (Máquina)": { en: "Processing Time (Machine)", es: "Tiempo de Procesado (Máquina)" },
  "Tempo de Projeto": { en: "Project Time", es: "Tiempo de Proyecto" },
  "Tempo Estimado de Produção:": { en: "Estimated Production Time:", es: "Tiempo Estimado de Producción:" },
  "Tempo Perdido": { en: "Lost Time", es: "Tiempo Perdido" },
  "Tempo Total de Produção": { en: "Total Production Time", es: "Tiempo Total de Producción" },
  "Termos de Aceite Comercial": { en: "Commercial Acceptance Terms", es: "Términos de Aceptación Comercial" },
  "Texto Persuasivo Pronto para Envio": { en: "Persuasive Text Ready for Sending", es: "Texto Persuasivo Listo para Enviar" },
  "Tipo Cobrança": { en: "Billing Type", es: "Tipo de Cobro" },
  "Total do Orçamento": { en: "Quote Total", es: "Total del Presupuesto" },
  "Total Item": { en: "Item Total", es: "Total del Elemento" },
  "Total Sugerido": { en: "Suggested Total", es: "Total Sugerido" },
  "Tudo": { en: "All", es: "Todo" },
  "URL da Logo (Opcional)": { en: "Logo URL (Optional)", es: "URL del Logo (Opcional)" },
  "Use o controle deslizante ou os botões rápidos": { en: "Use the slider or quick buttons", es: "Use el control deslizante o los botones rápidos" },
  "Uso do equipamento / h": { en: "Equipment usage / h", es: "Uso del equipo / h" },
  "Uso efetivo de hardware de manufatura 3D e consumo correspondente de energia elétrica.": { en: "Effective use of 3D manufacturing hardware and corresponding power draw.", es: "Uso efectivo de hardware de fabricación 3D y consumo eléctrico correspondiente." },
  "Uso Estimado": { en: "Estimated Usage", es: "Uso Estimado" },
  "Validação e Aceite do Cliente": { en: "Client Validation & Acceptance", es: "Validación y Aceptación del Cliente" },
  "Valor (R$)": { en: "Amount ($)", es: "Importe (€)" },
  "Valor da Hora (R$)": { en: "Hourly Rate ($)", es: "Valor Hora (€)" },
  "Valor do Frete (R$)": { en: "Shipping Cost ($)", es: "Coste de Envío (€)" },
  "Verniz": { en: "Varnish", es: "Barniz" },
  "Versões e snapshots salvos": { en: "Saved versions and snapshots", es: "Versiones y snapshots guardados" },
  "Vida útil do equipamento": { en: "Equipment Lifespan", es: "Vida útil del equipo" },
  "Vincule o cliente e os detalhes técnicos": { en: "Link customer and technical details", es: "Vincule al cliente y los detalles técnicos" },
  "Visão Estratégica:": { en: "Strategic View:", es: "Visión Estratégica:" },
  "Você precisa Salvar o Projeto antes de gerar o Link Mágico!": { en: "You must Save the Project before generating the Magic Link!", es: "¡Debe Guardar el Proyecto antes de generar el Enlace Mágico!" },
  "Voltar para a Página Inicial": { en: "Back to Home", es: "Volver a la Página Principal" },
  "WhatsApp (Link)": { en: "WhatsApp (Link)", es: "WhatsApp (Enlace)" },
  "WhatsApp (PDF)": { en: "WhatsApp (PDF)", es: "WhatsApp (PDF)" },
  "Avançado": { en: "Advanced", es: "Avanzado" },
  "Simples": { en: "Simple", es: "Simple" },
  "Auto": { en: "Auto", es: "Auto" },
  "Manual": { en: "Manual", es: "Manual" },
  "Modo Avançado (Exibindo todos os parâmetros)": { en: "Advanced Mode (Displaying all parameters)", es: "Modo Avanzado (Mostrando todos los parámetros)" },
  "Modo Simplificado (Exibindo apenas o essencial)": { en: "Simplified Mode (Displaying only essentials)", es: "Modo Simplificado (Mostrando solo lo essencial)" },
  "Modo Simplificado ativado": { en: "Simplified Mode activated", es: "Modo Simplificado activado" },
  "Modo Avançado ativado!": { en: "Advanced Mode activated!", es: "¡Modo Avanzado activado!" },
  "Salvamento automático desativado": { en: "Auto-save disabled", es: "Autoguardado desactivado" },
  "Salvamento automático ativado!": { en: "Auto-save activated!", es: "¡Autoguardado activado!" },
  "Editando Precificação": { en: "Editing Pricing", es: "Editando Fijación de Precios" },
  "Motor de Orçamentação Avançado": { en: "Advanced Quoting Engine", es: "Motor de Presupuestación Avanzado" },
  "Escolher impressora...": { en: "Choose printer...", es: "Elegir impresora..." },
  "Aplicar 15% de Perda": { en: "Apply 15% Waste", es: "Aplicar 15% de Merma" },
  "A impressora": { en: "The printer", es: "La impresora" },
  "apresentou falhas em 15% dos projetos nos últimos 30 dias.": { en: "showed failures in 15% of projects in the last 30 days.", es: "presentó fallos en el 15% de los proyectos en los últimos 30 días." },
  "Favoritos": { en: "Favorites", es: "Favoritos" },
  "Mais Usados": { en: "Most Used", es: "Más Usados" },
  "Sem resultados": { en: "No results", es: "Sin resultados" },
  "Gerenciar Estoque": { en: "Manage Inventory", es: "Gestionar Stock" },
  "Valores equivalem a 1 peça isolada. O custo total será multiplicado por": { en: "Values correspond to 1 single part. Total cost will be multiplied by", es: "Los valores corresponden a 1 sola pieza. El coste total se multiplicará por" },
  "Tempo e material da mesa inteira. O custo inserido já cobre todas as": { en: "Time and material for the full bed. The entered cost already covers all", es: "Tiempo y material de toda la cama. El coste introducido ya cubre todas las" },
  "produzidas de uma só vez.": { en: "produced at once.", es: "producidas de una sola vez." },
  "Soma de todas as partes de um kit. O custo do kit completo será multiplicado por": { en: "Sum of all parts in a kit. Complete kit cost will be multiplied by", es: "Suma de todas las partes de un kit. El coste del kit completo se multiplicará por" },
  "Tarifa de Energia Inteligente": { en: "Smart Electricity Rate", es: "Tarifa Eléctrica Inteligente" },
  "Selecionar Estado": { en: "Select State/Region", es: "Seleccionar Estado/Región" },
  "Bandeira Tarifária ANEEL (Sobretaxa de Estiagem)": { en: "Energy Tariff Flag (Drought Surcharge)", es: "Banderas Tarifarias (Recargo por Sequía)" },
  "Sem taxa extra": { en: "No extra fee", es: "Sin tasa extra" },

  "Detectamos automaticamente sua localização via backend Cloudflare para carregar a tarifa residencial da distribuidora do seu estado somada à bandeira selecionada.": { en: "We automatically detect your location via Cloudflare backend to load your regional residential electricity rate plus the selected flag.", es: "Detectamos automáticamente su ubicación mediante el backend de Cloudflare para cargar la tarifa eléctrica residencial de su región junto con la bandera seleccionada." },
  "Sim, detectar Estado pelo IP": { en: "Yes, detect State via IP", es: "Sí, detectar Estado por IP" },
  "Não, escolher Estado manualmente": { en: "No, choose State manually", es: "No, elegir Estado manualmente" },
  "Selecione o seu Estado abaixo para aplicar a tarifa média correspondente com a bandeira selecionada.": { en: "Select your State below to apply the corresponding average rate with the selected tariff flag.", es: "Seleccione su Estado a continuación para aplicar la tarifa media correspondiente con la bandera seleccionada." },
  "Buscando Localização...": { en: "Detecting Location...", es: "Buscando Ubicación..." },
  "Processando inteligência de mercado com Llama 3.2...": { en: "Processing market intelligence with Llama 3.2...", es: "Procesando inteligencia de mercado con Llama 3.2..." },
  "Avaliando tempo de máquina, riscos de empenamento, complexidade e calibrando margens líquidas": { en: "Evaluating machine time, warping risks, complexity and calibrating net margins", es: "Evaluando tiempo de máquina, riesgos de deformación, complejidad y calibrando márgenes netos" },
  "Deseja adicionar horas de design (CAD)?": { en: "Want to add design (CAD) hours?", es: "¿Desea añadir horas de diseño (CAD)?" },
  "Deseja adicionar acabamento e pintura?": { en: "Want to add finishing and painting?", es: "¿Desea añadir acabado y pintura?" },
  "Prever falha ou erro de impressão?": { en: "Predict failure or print errors?", es: "¿Prever fallo o error de impresión?" },
  "B2B (3x)": { en: "B2B (3x)", es: "B2B (3x)" },
  "B2C (5x)": { en: "B2C (5x)", es: "B2C (5x)" },
  "Sincronizando com a nuvem...": { en: "Syncing with cloud...", es: "Sincronizando con la nube..." },
  "Montando PDF oficial...": { en: "Generating official PDF...", es: "Generando PDF oficial..." },
  "Baixando orçamento...": { en: "Downloading quote...", es: "Descargando presupuesto..." },
  "Vencimento:": { en: "Due Date:", es: "Vencimiento:" },
  "Investimento Total:": { en: "Total Investment:", es: "Inversión Total:" },
  "Arquivado": { en: "Archived", es: "Archivado" },
  "Projeto:": { en: "Project:", es: "Proyecto:" },
  "Cliente:": { en: "Client:", es: "Cliente:" },
  "Descrição:": { en: "Description:", es: "Descripción:" },
  "VALOR TOTAL:": { en: "TOTAL VALUE:", es: "VALOR TOTAL:" },
  "Orçamentos Salvos": { en: "Saved Quotes", es: "Presupuestos Guardados" },
  "* Os snapshots agora ficam salvos na sua nuvem e sincronizados em todos os dispositivos.": { en: "* Snapshots are now saved in your cloud and synchronized across all devices.", es: "* Las instantáneas ahora se guardan en su nube y se sincronizan en todos los dispositivos." },
  "• Complexidade:": { en: "• Complexity:", es: "• Complejidad:" },
  "Sim, Aplicar": { en: "Yes, Apply", es: "Sí, Aplicar" },
  "Não, Manter Atual": { en: "No, Keep Current", es: "No, Mantener Actual" },
  "Custos Fixos / Adicionais": { en: "Fixed / Additional Costs", es: "Costes Fijos / Adicionales" },
  "Consumo de Matéria-Prima": { en: "Raw Material Consumption", es: "Consumo de Materia Prima" },
  "Material Aplicado": { en: "Applied Material", es: "Material Aplicado" },
  "Insumos & Acabamento": { en: "Supplies & Finish", es: "Insumos y Acabado" },
  "ESTÚDIO:": { en: "STUDIO:", es: "ESTUDIO:" },
  "| HORA:": { en: "| TIME:", es: "| HORA:" },
  "← Voltar para detecção automática": { en: "← Back to automatic detection", es: "← Volver a detección automática" },
  "Fabricação:": { en: "Manufacturing:", es: "Fabricación:" },
};
