import { DicionarioTraducao } from "./tipos";

export const dicionarioBase: DicionarioTraducao = {
  "+ Primer": { en: "+ Primer", es: "+ Imprimación" },
  "100% dos Makers": { en: "100% of Makers", es: "100% de los Makers" },
  "14 Peças": { en: "14 Parts", es: "14 Piezas" },
  "2. Fornecimento \\\"AS IS\\\" (Como Está) e Disponibilidade": { en: "2. \\\"AS IS\\\" Provision and Availability", es: "2. Suministro \\\"AS IS\\\" (Tal Cual) y Disponibilidad" },
  "A Pagar": { en: "To Pay", es: "Por Pagar" },
  "A Receber": { en: "To Receive", es: "Por Cobrar" },
  "A Vencer / Expirados": { en: "Expiring / Expired", es: "Por Vencer / Vencidos" },
  "A conta de luz pode representar uma parcela significativa do custo. Ignorar isso é fatal.": { en: "Electricity can represent a significant share of the cost. Ignoring it is fatal.", es: "La factura eléctrica puede representar una parte significativa del coste. Ignorarlo es fatal." },
  "A parte jurídica, sem exageros.": { en: "The legal part, without exaggeration.", es: "La parte legal, sin exageraciones." },
  "ADAPTAÇÃO AUTOMÁTICA DE FORMATOS": { en: "AUTOMATIC FORMAT ADAPTATION", es: "ADAPTACIÓN AUTOMÁTICA DE FORMATOS" },
  "AGENDAR AGORA": { en: "SCHEDULE NOW", es: "PROGRAMAR AHORA" },
  "ALERTA": { en: "ALERT", es: "ALERTA" },
  "Abandone as planilhas. Gerencie custos, prazos e hardware em uma interface industrial de alta densidade.": { en: "Abandon spreadsheets. Manage costs, deadlines, and hardware in a high-density industrial interface.", es: "Abandone las hojas de cálculo. Gestione costes, plazos y hardware en una interfaz industrial de alta densidad." },
  "Abertos": { en: "Open", es: "Abiertos" },
  "Abrir Raio-X do Maker": { en: "Open Maker Deep Dive", es: "Abrir Radiografía del Maker" },
  "Acesse ou Crie sua conta": { en: "Sign In or Create Account", es: "Inicie Sesión o Cree su Cuenta" },
  "Acesso a todas as ferramentas": { en: "Access to all tools", es: "Acceso a todas las herramientas" },
  "Acesso total gratuito para quem apoia o início do projeto": { en: "Full free access for everyone supporting the launch", es: "Acceso total gratuito para quienes apoyan el inicio del proyecto" },
  "Acesso à Central Maker": { en: "Access to Maker Hub", es: "Acceso a la Central Maker" },
  "Acompanhamento detalhado de rentabilidade e saúde financeira": { en: "Detailed profitability and financial health tracking", es: "Seguimiento detallado de rentabilidad y salud financiera" },
  "Acréscimo de +R$ 0,019/kWh": { en: "+R$ 0.019/kWh surcharge", es: "Recargo de +R$ 0,019/kWh" },
  "Acréscimo de +R$ 0,045/kWh": { en: "+R$ 0.045/kWh surcharge", es: "Recargo de +R$ 0,045/kWh" },
  "Acréscimo de +R$ 0,079/kWh": { en: "+R$ 0.079/kWh surcharge", es: "Recargo de +R$ 0,079/kWh" },
  "Acréscimo de +R$ 0,142/kWh (seca severa)": { en: "+R$ 0.142/kWh surcharge (severe drought)", es: "Recargo de +R$ 0,142/kWh (sequía severa)" },
  "Action Figure": { en: "Action Figure", es: "Figura de Acción" },
  "Adaptação Automática de Formatos": { en: "Automatic Format Adaptation", es: "Adaptación Automática de Formatos" },
  "Adicionar": { en: "Add", es: "Añadir" },
  "Adicionar à Fila": { en: "Add to Queue", es: "Añadir a la Cola" },
  "Agenda de Manutenção Preditiva": { en: "Predictive Maintenance Schedule", es: "Agenda de Mantenimiento Predictivo" },
  "Aguardando": { en: "Waiting", es: "En Espera" },
  "Aguardando Início": { en: "Pending Start", es: "Esperando Inicio" },
  "Ajustes Visuais": { en: "Visual Adjustments", es: "Ajustes Visuales" },
  "Alerta": { en: "Alert", es: "Alerta" },
  "Alerta / Manutenção": { en: "Alert / Maintenance", es: "Alerta / Mantenimiento" },
  "Alerta de Estoque": { en: "Stock Alert", es: "Alerta de Stock" },
  "Alertas Estoque": { en: "Stock Alerts", es: "Alertas de Stock" },
  "Alocar em:": { en: "Allocate to:", es: "Asignar a:" },
  "Alta": { en: "High", es: "Alta" },
  "Alterar Senha": { en: "Change Password", es: "Cambiar Contraseña" },
  "Alto Contraste": { en: "High Contrast", es: "Alto Contraste" },
  "Altura de Camada": { en: "Layer Height", es: "Altura de Capa" },
  "Anual": { en: "Annual", es: "Anual" },
  "Análise de Desperdício": { en: "Scrap & Waste Analysis", es: "Análisis de Desperdicio" },
  "Ao alternar o idioma, datas, moedas e termos operacionais são ajustados instantaneamente sem recarregar a página e ficam salvos no seu navegador.": { en: "When switching languages, dates, currencies, and operational terms are instantly adjusted without reloading and saved to your browser.", es: "Al cambiar el idioma, las fechas, monedas y términos operativos se ajustan instantáneamente sin recargar la página y se guardan en su navegador." },
  "Ao continuar, você concorda com nossos": { en: "By continuing, you agree to our", es: "Al continuar, usted acepta nuestros" },
  "Aparência": { en: "Appearance", es: "Apariencia" },
  "Apenas Abertos": { en: "Only Open", es: "Solo Abiertos" },
  "Assinar Plano PRO": { en: "Subscribe to PRO Plan", es: "Suscribirse al Plan PRO" },
  "Assinatura": { en: "Subscription", es: "Suscripción" },
  "Assinatura & Acesso": { en: "Subscription & Access", es: "Suscripción y Acceso" },
  "Atenção": { en: "Attention", es: "Atención" },
  "Ativo": { en: "Active", es: "Activo" },
  "Atlas Mega 02": { en: "Atlas Mega 02", es: "Atlas Mega 02" },
  "Atlas Mega 02 precisa de lubrificação em 2h de uso.": { en: "Atlas Mega 02 needs lubrication after 2h of use.", es: "Atlas Mega 02 necesita lubricación en 2h de uso." },
  "Atrasado": { en: "Overdue", es: "Atrasado" },
  "Automático": { en: "System Default", es: "Automático" },
  "Avançar": { en: "Next", es: "Avanzar" },
  "Avisar sobre janela técnica noturna": { en: "Notify about nightly maintenance window", es: "Avisar sobre ventana técnica nocturna" },
  "Avisos Globais & Broadcast": { en: "Global Notices & Broadcast", es: "Avisos Globales y Difusión" },
  "Ações": { en: "Actions", es: "Acciones" },
  "BUSCAR...": { en: "SEARCH...", es: "BUSCAR..." },
  "Backups:": { en: "Backups:", es: "Copias de seguridad:" },
  "Baixa": { en: "Low", es: "Baja" },
  "Baixar": { en: "Download", es: "Descargar" },
  "Baixar PDF": { en: "Download PDF", es: "Descargar PDF" },
  "Bandeira Amarela": { en: "Yellow Flag", es: "Tarifa Amarilla" },
  "Bandeira Verde": { en: "Green Flag", es: "Tarifa Verde" },
  "Bandeira Vermelha 1": { en: "Red Flag 1", es: "Tarifa Roja 1" },
  "Bandeira Vermelha 2": { en: "Red Flag 2", es: "Tarifa Roja 2" },
  "Base de Clientes": { en: "Customer Base", es: "Base de Clientes" },
  "Base de usuários exportada em CSV com dados essenciais.": { en: "User base exported to CSV with essential data.", es: "Base de usuarios exportada en CSV con datos esenciales." },
  "Benefícios": { en: "Benefits", es: "Beneficios" },
  "Bico": { en: "Nozzle", es: "Boquilla" },
  "Bobina": { en: "Spool", es: "Bobina" },
  "Botão de dispensar pelo usuário": { en: "User dismiss button", es: "Botón de descartar por el usuario" },
  "Branding de Estúdio": { en: "Studio Branding", es: "Branding de Estudio" },
  "Broadcast:": { en: "Broadcast:", es: "Difusión:" },
  "Buscar": { en: "Search", es: "Buscar" },
  "Buscar por assunto, e-mail ou estúdio...": { en: "Search by subject, email or studio...", es: "Buscar por asunto, correo o estudio..." },
  "Buscar por nome, e-mail ou telefone...": { en: "Search by name, email or phone...", es: "Buscar por nombre, correo o teléfono..." },
  "Buscar...": { en: "Search...", es: "Buscar..." },
  "CEP": { en: "Zip Code", es: "Código Postal" },
  "CPF / CNPJ": { en: "Tax ID / SSN", es: "NIF / CIF" },
  "Cadastrar Cliente": { en: "Register Client", es: "Registrar Cliente" },
  "Cadastre seus filamentos e resinas para controle automático de estoque e precificação.": { en: "Register your filaments and resins for automated inventory and pricing control.", es: "Registre sus filamentos y resinas para control automático de stock y precios." },
  "Cadastre sua primeira impressora para calcular custos reais de depreciação e energia.": { en: "Register your first printer to calculate real depreciation and energy costs.", es: "Registre su primera impresora para calcular costes reales de depreciación y energía." },
  "Cadastros ilimitados de Impressoras e Materiais": { en: "Unlimited Printers and Materials registrations", es: "Registros ilimitados de Impresoras y Materiales" },
  "Calculadora": { en: "Calculator", es: "Calculadora" },
  "Calculadora 3D": { en: "3D Calculator", es: "Calculadora 3D" },
  "Calculadora Técnica de Custos": { en: "Technical Cost Calculator", es: "Calculadora Técnica de Costes" },
  "Calculadora de Custos": { en: "Cost Calculator", es: "Calculadora de Costes" },
  "Calculadora de Impressão 3D": { en: "3D Printing Calculator", es: "Calculadora de Impresión 3D" },
  "Calcular Preço": { en: "Calculate Price", es: "Calcular Precio" },
  "Calcule custos reais de energia, resina, filamento e margem líquida com precisão e dignidade.": { en: "Calculate real costs of energy, resin, filament, and net margin with precision and dignity.", es: "Calcule costes reales de energía, resina, filamento y margen neto con precisión y dignidad." },
  "Camada": { en: "Layer", es: "Capa" },
  "Cancelado": { en: "Cancelled", es: "Cancelado" },
  "Cancelar": { en: "Cancel", es: "Cancelar" },
  "Carregando": { en: "Loading", es: "Cargando" },
  "Carregando fila de chamados...": { en: "Loading ticket queue...", es: "Cargando cola de tickets..." },
  "Carregando gráfico de consumo...": { en: "Loading consumption chart...", es: "Cargando gráfico de consumo..." },
  "Carregando usuários cadastrados...": { en: "Loading registered users...", es: "Cargando usuarios registrados..." },
  "Carregando...": { en: "Loading...", es: "Cargando..." },
  "Carretel": { en: "Spool", es: "Carrete" },
  "Categoria": { en: "Category", es: "Categoría" },
  "Central Maker": { en: "Maker Hub", es: "Centro Maker" },
  "Central de Acessibilidade": { en: "Accessibility Center", es: "Centro de Accesibilidad" },
  "Central de Comando, Gestão de Acessos e Conformidade LGPD": { en: "Command Center, Access Management and LGPD Compliance", es: "Centro de Mando, Gestión de Accesos y Cumplimiento RGPD" },
  "Central de Suporte": { en: "Support Center", es: "Centro de Soporte" },
  "Chutômetro": { en: "Guesswork", es: "Estimaciones a ojo" },
  "Ciclo": { en: "Cycle", es: "Ciclo" },
  "Ciclo de pagamento atualizado!": { en: "Payment cycle updated!", es: "¡Ciclo de pago actualizado!" },
  "Cidade": { en: "City", es: "Ciudad" },
  "Clientes": { en: "Clients", es: "Clientes" },
  "Clique para carregar parâmetros prontos": { en: "Click to load preset parameters", es: "Haga clic para cargar parámetros predefinidos" },
  "Clique para filtrar usuários que expiram em até 7 dias": { en: "Click to filter users expiring within 7 days", es: "Haga clic para filtrar usuarios que vencen en 7 días" },
  "Clique para gerenciar o Broadcast no topo do app": { en: "Click to manage top banner Broadcast", es: "Haga clic para gestionar el aviso superior" },
  "Clube Fundador (Vagas)": { en: "Founder Club (Slots)", es: "Club Fundador (Plazas)" },
  "Comercial": { en: "Commercial", es: "Comercial" },
  "Começar Agora": { en: "Get Started Now", es: "Comenzar Ahora" },
  "Começar Grátis": { en: "Start Free", es: "Comenzar Gratis" },
  "Compartilhar": { en: "Share", es: "Compartir" },
  "Compromisso Ético PrintLog": { en: "PrintLog Ethical Commitment", es: "Compromiso Ético PrintLog" },
  "Conceder 7 dias de PRO gratuito (Degustação)": { en: "Grant 7 days of free PRO trial", es: "Conceder 7 días de prueba PRO gratis" },
  "Conceder Degustação PRO:": { en: "Grant PRO Trial:", es: "Conceder Prueba PRO:" },
  "Concluir": { en: "Complete", es: "Concluir" },
  "Concluir Projeto & Liberar": { en: "Complete Project & Release", es: "Finalizar Proyecto y Liberar" },
  "Concluído": { en: "Completed", es: "Completado" },
  "Condições do Ambiente de Impressão": { en: "Printing Environment Conditions", es: "Condiciones del Entorno de Impresión" },
  "Configuração Ausente": { en: "Missing Configuration", es: "Configuración Ausente" },
  "Configurações": { en: "Settings", es: "Configuración" },
  "Configurações de acessibilidade restauradas para o padrão.": { en: "Accessibility settings restored to default.", es: "Ajustes de accesibilidad restaurados a los valores predeterminados." },
  "Confirmar": { en: "Confirm", es: "Confirmar" },
  "Conforto & Leitura Nítida": { en: "Comfort & Clear Reading", es: "Comodidad y Lectura Nítida" },
  "Console": { en: "Console", es: "Consola" },
  "Console do Dono": { en: "Owner Console", es: "Consola del Propietario" },
  "Consumo": { en: "Consumption", es: "Consumo" },
  "Consumo Filamento": { en: "Filament Used", es: "Consumo de Filamento" },
  "Conta ativa e confirmada no Firebase Authentication": { en: "Active and verified account in Firebase Authentication", es: "Cuenta activa y confirmada en Firebase Authentication" },
  "Contato": { en: "Contact", es: "Contacto" },
  "Continuar": { en: "Continue", es: "Continuar" },
  "Continuar com E-mail": { en: "Continue with Email", es: "Continuar con Correo" },
  "Continuar com GitHub": { en: "Continue with GitHub", es: "Continuar con GitHub" },
  "Continuar com Google": { en: "Continue with Google", es: "Continuar con Google" },
  "Continuar conectado": { en: "Stay logged in", es: "Mantener sesión iniciada" },
  "Controle total sobre custos, materiais e produção. Deixe o PrintLog calcular enquanto você cria.": { en: "Complete control over costs, materials, and production. Let PrintLog calculate while you create.", es: "Control total sobre costes, materiales y producción. Deje que PrintLog calcule mientras usted crea." },
  "Copiado para a área de transferência!": { en: "Copied to clipboard!", es: "¡Copiado al portapapeles!" },
  "Copiar E-mail": { en: "Copy Email", es: "Copiar Correo" },
  "Copiar Link": { en: "Copy Link", es: "Copiar Enlace" },
  "Copiar UID completo": { en: "Copy full UID", es: "Copiar UID completo" },
  "Copiar e-mail real": { en: "Copy actual email", es: "Copiar correo real" },
  "Cor": { en: "Color", es: "Color" },
  "Criar Conta": { en: "Create Account", es: "Crear Cuenta" },
  "Criptografia AES-256": { en: "AES-256 Encryption", es: "Cifrado AES-256" },
  "Cursor Ampliado": { en: "Enlarged Cursor", es: "Cursor Ampliado" },
  "Custo Total": { en: "Total Cost", es: "Coste Total" },
  "Custo de Energia": { en: "Energy Cost", es: "Coste de Energía" },
  "Custo do Material": { en: "Material Cost", es: "Coste del Material" },
  "Custo por Grama": { en: "Cost per Gram", es: "Coste por Gramo" },
  "Custo por Kg": { en: "Cost per Kg", es: "Coste por Kg" },
  "Câmbio Comercial Oficial:": { en: "Official Exchange Rate:", es: "Tipo de Cambio Oficial:" },
  "DINHEIRO FORA": { en: "MONEY AWAY", es: "EL DINERO" },
  "DRE": { en: "P&L Statement", es: "Estado de Resultados" },
  "Dashboard": { en: "Dashboard", es: "Panel de Control" },
  "Dashboard de performance financeira": { en: "Financial performance dashboard", es: "Panel de rendimiento financiero" },
  "Data": { en: "Date", es: "Fecha" },
  "Data de Pagamento": { en: "Payment Date", es: "Fecha de Pago" },
  "Data de Vencimento": { en: "Due Date", es: "Fecha de Vencimiento" },
  "Define ícone e paleta de cores": { en: "Defines icon and color palette", es: "Define icono y paleta de colores" },
  "Degustação": { en: "Trial", es: "Prueba" },
  "Demonstração": { en: "Demo", es: "Demostración" },
  "Demonstração do Sistema": { en: "System Demo", es: "Demostración del Sistema" },
  "Descartar": { en: "Discard", es: "Descartar" },
  "Descreva sua experiência...": { en: "Describe your experience...", es: "Describa su experiencia..." },
  "Descrição": { en: "Description", es: "Descripción" },
  "Desperdício Oculto": { en: "Hidden Waste", es: "Desperdicio Oculto" },
  "Despesa": { en: "Expense", es: "Gasto" },
  "Despesas": { en: "Expenses", es: "Gastos" },
  "Detalhes": { en: "Details", es: "Detalles" },
  "Dica: Tarifas de Energia": { en: "Tip: Electricity Tariffs", es: "Consejo: Tarifas de Energía" },
  "Digite o e-mail...": { en: "Type an email...", es: "Escriba un correo..." },
  "Digite o nome...": { en: "Type a name...", es: "Escriba un nombre..." },
  "Digite o telefone...": { en: "Type a phone...", es: "Escriba un teléfono..." },
  "Digite uma mensagem ou clique em um dos Modelos Rápidos acima.": { en: "Enter a message or click one of the Quick Templates above.", es: "Escriba un mensaje o elija una de las Plantillas Rápidas superiores." },
  "Divulgar atualização e novas fórmulas": { en: "Announce update and new formulas", es: "Divulgar actualización y nuevas fórmulas" },
  "Documento": { en: "Document", es: "Documento" },
  "Dê adeus ao": { en: "Say goodbye to", es: "Diga adiós a las" },
  "Dê adeus ao \\\\\\\\\\\\\\\"chutômetro\\\\\\\\\\\\\\\". Calcule custos reais de energia, resina, filamento e margem líquida com precisão e dignidade.": { en: "Say goodbye to \\\\\\\\\\\\\\\"guesswork\\\\\\\\\\\\\\\". Calculate real costs of energy, resin, filament, and net margin with precision and dignity.", es: "Diga adiós a las \\\\\\\\\\\\\\\"estimaciones a ojo\\\\\\\\\\\\\\\". Calcule costes reales de energía, resina, filamento y margen neto con precisión y dignidad." },
  "E-mail": { en: "Email", es: "Correo" },
  "EM CURSO": { en: "IN PROGRESS", es: "EN CURSO" },
  "EM LUCRO": { en: "INTO PROFIT", es: "EN BENEFICIO" },
  "EM LUCRO.": { en: "INTO PROFIT.", es: "EN BENEFICIO." },
  "EM REVISÃO": { en: "UNDER REVIEW", es: "EN REVISIÓN" },
  "ENERGIA": { en: "ENERGY", es: "ENERGÍA" },
  "Ecossistema de Clientes": { en: "Customer Ecosystem", es: "Ecosistema de Clientes" },
  "Editando Precificação": { en: "Editing Pricing", es: "Editando Precios" },
  "Editar": { en: "Edit", es: "Editar" },
  "Editar Cliente": { en: "Edit Client", es: "Editar Cliente" },
  "Em Análise": { en: "In Review", es: "En Revisión" },
  "Em Análise (Investigando)": { en: "In Review (Investigating)", es: "En Revisión (Investigando)" },
  "Em Produção": { en: "In Production", es: "En Producción" },
  "Em estoque": { en: "In stock", es: "En stock" },
  "Endereço": { en: "Address", es: "Dirección" },
  "Energia": { en: "Energy", es: "Energía" },
  "Energia Ignorada": { en: "Ignored Energy", es: "Energía Ignorada" },
  "Entrada": { en: "Inflow", es: "Entrada" },
  "Entrar": { en: "Sign In", es: "Iniciar Sesión" },
  "Enviar e-mail de contato / suporte": { en: "Send contact / support email", es: "Enviar correo de contacto / soporte" },
  "Erro": { en: "Error", es: "Error" },
  "Erro ao alocar pedido.": { en: "Error allocating order.", es: "Error al asignar pedido." },
  "Erro ao alterar estado da impressora.": { en: "Error changing printer state.", es: "Error al cambiar estado de la impresora." },
  "Erro ao carregar clima local": { en: "Error loading local weather", es: "Error al cargar el clima local" },
  "Erro ao carregar lista de chamados de suporte.": { en: "Error loading support ticket list.", es: "Error al cargar lista de tickets de soporte." },
  "Erro ao carregar lista de usuários da base.": { en: "Error loading registered user list.", es: "Error al cargar lista de usuarios." },
  "Erro ao concluir projeto.": { en: "Error completing project.", es: "Error al finalizar proyecto." },
  "Erro ao desalocar pedido.": { en: "Error deallocating order.", es: "Error al desasignar pedido." },
  "Erro ao reordenar a fila.": { en: "Error reordering queue.", es: "Error al reordenar la cola." },
  "Erro durante a exclusão de registros órfãos.": { en: "Error while deleting orphan records.", es: "Error durante la eliminación de registros huérfanos." },
  "Erro inesperado no servidor.": { en: "Unexpected server error.", es: "Error inesperado en el servidor." },
  "Escala de Cinza": { en: "Grayscale", es: "Escala de Grises" },
  "Escassez Hídrica": { en: "Water Scarcity Tariff", es: "Tarifa de Escasez Hídrica" },
  "Escolha o Plano Ideal para sua": { en: "Choose the Ideal Plan for Your", es: "Elija el Plan Ideal para su" },
  "Esconder detalhes": { en: "Hide details", es: "Ocultar detalles" },
  "Escreva sua resposta de forma clara, prestativa e orientada à solução...": { en: "Write your answer clearly, helpfully and solution-oriented...", es: "Escriba su respuesta de forma clara, servicial y orientada a la solución..." },
  "Esgotado": { en: "Out of stock", es: "Agotado" },
  "Esperar a máquina quebrar custa caro. Organize revisões e evite o downtime.": { en: "Waiting for the machine to break is costly. Schedule checkups and prevent downtime.", es: "Esperar a que la máquina se rompa cuesta caro. Organice revisiones y evite el downtime." },
  "Estado": { en: "State", es: "Provincia / Estado" },
  "Este usuário não possui e-mail cadastrado.": { en: "This user has no registered email.", es: "Este usuario no tiene correo registrado." },
  "Estoque": { en: "Inventory", es: "Stock" },
  "Estoque Baixo": { en: "Low Stock", es: "Stock Bajo" },
  "Estoque Parado": { en: "Idle Inventory", es: "Stock Parado" },
  "Estoque em dia": { en: "Stock up to date", es: "Stock al día" },
  "Estúdio": { en: "Studio", es: "Estudio" },
  "Estúdio removido com sucesso.": { en: "Studio removed successfully.", es: "Estudio eliminado con éxito." },
  "Evite paradas não planejadas monitorando a saúde do seu parque.": { en: "Prevent unplanned downtime by monitoring fleet health.", es: "Evite paradas no planificadas monitoreando la salud de su parque." },
  "Ex:": { en: "e.g.:", es: "Ej.:" },
  "Excluir": { en: "Delete", es: "Eliminar" },
  "Excluir Cliente": { en: "Delete Client", es: "Eliminar Cliente" },
  "Excluir este registro órfão permanentemente do banco D1": { en: "Permanently delete this orphan record from D1", es: "Eliminar este registro huérfano permanentemente de D1" },
  "Exemplo de Data": { en: "Date Example", es: "Ejemplo de Fecha" },
  "Exemplo de Data:": { en: "Date Example:", es: "Ejemplo de Fecha:" },
  "Exemplo de Moeda": { en: "Currency Example", es: "Ejemplo de Moneda" },
  "Exemplo de Moeda:": { en: "Currency Example:", es: "Ejemplo de Moneda:" },
  "Exemplo de Temp.:": { en: "Temp. Example:", es: "Ejemplo de Temp.:" },
  "Exemplo de Temperatura:": { en: "Temperature Example:", es: "Ejemplo de Temperatura:" },
  "Exportar": { en: "Export", es: "Exportar" },
  "Exportar CSV": { en: "Export CSV", es: "Exportar CSV" },
  "Exportar base de usuários essencial para planilha CSV": { en: "Export core user base to CSV", es: "Exportar base esencial de usuarios a CSV" },
  "Exportação de Orçamentos Simples": { en: "Simple Quote Export", es: "Exportación de Presupuestos Simples" },
  "Exportação em PDF White-label e Link Mágico": { en: "White-label PDF Export & Magic Link", es: "Exportación en PDF Marca Blanca y Enlace Mágico" },
  "Express ⚡": { en: "Express ⚡", es: "Express ⚡" },
  "Extrusora": { en: "Extruder", es: "Extrusor" },
  "FILAMENTO": { en: "FILAMENT", es: "FILAMENTO" },
  "FINAL PRICE": { en: "FINAL PRICE", es: "PRECIO FINAL" },
  "Fabricante": { en: "Manufacturer", es: "Fabricante" },
  "Falha": { en: "Failure", es: "Fallo" },
  "Falha ao atualizar ciclo.": { en: "Failed to update cycle.", es: "Fallo al actualizar ciclo." },
  "Falha ao atualizar plano.": { en: "Failed to update plan.", es: "Fallo al actualizar plan." },
  "Falha ao carregar fila de produção": { en: "Failed to load production queue", es: "Fallo al cargar cola de producción" },
  "Falha ao carregar perfil do operador.": { en: "Failed to load operator profile.", es: "Fallo al cargar perfil del operador." },
  "Falha ao carregar prévia.": { en: "Failed to load preview.", es: "Fallo al cargar vista previa." },
  "Falha ao conceder degustação.": { en: "Failed to grant trial.", es: "Fallo al conceder prueba." },
  "Falha ao executar limpeza legal de logs.": { en: "Failed to run statutory log cleanup.", es: "Fallo al ejecutar limpieza legal de registros." },
  "Falha ao renovar plano.": { en: "Failed to renew plan.", es: "Fallo al renovar plan." },
  "Falha ao salvar aviso global.": { en: "Failed to save global notice.", es: "Fallo al guardar aviso global." },
  "Falha ao sincronizar dados": { en: "Failed to sync data", es: "Fallo al sincronizar datos" },
  "Falha ao sincronizar dados do painel.": { en: "Failed to sync dashboard data.", es: "Fallo al sincronizar datos del panel." },
  "Falhas de Impressão": { en: "Print Failures", es: "Fallos de Impresión" },
  "Farm": { en: "Farm", es: "Granja" },
  "Faturado Mês": { en: "Monthly Revenue", es: "Facturado Mes" },
  "Faturamento": { en: "Revenue", es: "Facturación" },
  "Faturamento Total": { en: "Total Revenue", es: "Facturación Total" },
  "Favicon": { en: "Favicon", es: "Favicón" },
  "Fechado": { en: "Closed", es: "Cerrado" },
  "Fechar": { en: "Close", es: "Cerrar" },
  "Fechar Modal": { en: "Close Modal", es: "Cerrar Modal" },
  "Feito por Makers, Para Makers — Junte-se à Missão": { en: "Made by Makers, For Makers — Join the Mission", es: "Hecho por Makers, Para Makers — Únase a la Misión" },
  "Fila de Impressão": { en: "Print Queue", es: "Cola de Impresión" },
  "Fila de Produção": { en: "Print Queue", es: "Cola de Producción" },
  "Fila de produção reordenada!": { en: "Production queue reordered!", es: "¡Cola de producción reordenada!" },
  "Filamento": { en: "Filament", es: "Filamento" },
  "Filamento velho absorve umidade e estraga suas peças. Controle seu giro.": { en: "Old filament absorbs moisture and ruins your prints. Control your turnover.", es: "El filamento viejo absorbe humedad y estropea sus piezas. Controle su rotación." },
  "Filamentos": { en: "Filaments", es: "Filamentos" },
  "Filamentos (FDM)": { en: "Filaments (FDM)", es: "Filamentos (FDM)" },
  "Filtrar": { en: "Filter", es: "Filtrar" },
  "Filtrar por e-mail, ID ou estúdio...": { en: "Filter by email, ID or studio...", es: "Filtrar por correo, ID o estudio..." },
  "Filtros": { en: "Filters", es: "Filtros" },
  "Filtros Rápidos": { en: "Quick Filters", es: "Filtros Rápidos" },
  "Final": { en: "Final", es: "Final" },
  "Financeiro": { en: "Financial", es: "Financiero" },
  "Fixar no topo": { en: "Pin to top", es: "Fijar arriba" },
  "Fluxo Financeiro": { en: "Financial Flow", es: "Flujo Financiero" },
  "Fluxo de Caixa": { en: "Cash Flow", es: "Flujo de Caja" },
  "Fluxo de Produção": { en: "Production Flow", es: "Flujo de Producción" },
  "Forma de Pagamento": { en: "Payment Method", es: "Forma de Pago" },
  "Fundadores (Clube 51)": { en: "Founders (Club 51)", es: "Fundadores (Club 51)" },
  "GESTÃO TÉCNICA DE IMPRESSÃO 3D": { en: "TECHNICAL 3D PRINTING MANAGEMENT", es: "GESTIÓN TÉCNICA DE IMPRESIÓN 3D" },
  "Geral": { en: "General", es: "General" },
  "Gerar Orçamento": { en: "Generate Quote", es: "Generar Presupuesto" },
  "Gerenciar Acessos": { en: "Manage Access", es: "Gestionar Accesos" },
  "Gerencie peças e outros materiais logísticos": { en: "Manage parts and logistics materials", es: "Gestione piezas y otros materiales logísticos" },
  "Gerencie seu parque de máquinas": { en: "Manage your printer fleet and maintenance", es: "Gestione su parque de máquinas y mantenimiento" },
  "Gerencie seus pedidos no Kanban": { en: "Manage your orders in the Kanban board", es: "Gestione sus pedidos en el tablero Kanban" },
  "Gestão": { en: "Management", es: "Gestión" },
  "Gestão Manual": { en: "Manual Management", es: "Gestión Manual" },
  "Gestão Técnica de Impressão 3D": { en: "Technical 3D Printing Management", es: "Gestión Técnica de Impresión 3D" },
  "Gestão comercial, CRM e acompanhamento de parceiros": { en: "Commercial management, CRM and client tracking", es: "Gestión comercial, CRM y seguimiento de clientes" },
  "Gestão de Impressão 3D": { en: "3D Printing Management", es: "Gestión de Impresión 3D" },
  "Gestão de Materiais e Insumos": { en: "Materials & Supplies Management", es: "Gestión de Materiales e Insumos" },
  "Gestão de filamentos, resinas e patrimônio técnico": { en: "Filament, resin and technical asset inventory", es: "Gestión de filamentos, resinas y patrimonio técnico" },
  "Gestão de receitas, custos operacionais, despesas e DRE": { en: "Revenue, operating costs, expenses, and P&L management", es: "Gestión de ingresos, costes operativos, gastos y pérdidas y ganancias" },
  "Gestão inteligente de filamentos": { en: "Smart filament and inventory management", es: "Gestión inteligente de filamentos" },
  "Gestão operacional e proteção de dados (LGPD)": { en: "Operational management and data privacy (LGPD)", es: "Gestión operativa y protección de datos (LGPD)" },
  "Gratuito": { en: "Free", es: "Gratuito" },
  "Gráfico de Pizza (Custos 360º)": { en: "Pie Chart (360° Cost Breakdown)", es: "Gráfico de Sectores (Costes 360º)" },
  "Histórico Limpo": { en: "Clean History", es: "Historial Limpio" },
  "Histórico de Pedidos": { en: "Order History", es: "Historial de Pedidos" },
  "Hora Máquina": { en: "Machine Hour", es: "Hora Máquina" },
  "Hora Operador": { en: "Operator Hour", es: "Hora Operario" },
  "Horas": { en: "Hours", es: "Horas" },
  "Ideal para hobbistas e quem está começando agora.": { en: "Ideal for hobbyists and makers just getting started.", es: "Ideal para aficionados y quienes están comenzando ahora." },
  "Identidade Visual do seu Estúdio": { en: "Studio Visual Identity", es: "Identidad Visual de su Estudio" },
  "Idioma": { en: "Language", es: "Idioma" },
  "Importar": { en: "Import", es: "Importar" },
  "Impressoras": { en: "3D Printers", es: "Impresoras 3D" },
  "Imprimir Orçamento": { en: "Print Quote", es: "Imprimir Presupuesto" },
  "Inativo": { en: "Inactive", es: "Inactivo" },
  "Incentivar upgrade para plano vitalício": { en: "Promote lifetime plan upgrade", es: "Promover actualización al plan vitalicio" },
  "Informativo / Novidade": { en: "Informative / News", es: "Informativo / Novedad" },
  "Informação técnica validada": { en: "Technical info verified", es: "Información técnica validada" },
  "Iniciar Impressão": { en: "Start Printing", es: "Iniciar Impresión" },
  "Insights de Mercado e Dicas da IA": { en: "Market Insights & AI Tips", es: "Insights de Mercado y Consejos de IA" },
  "Insumos": { en: "Supplies", es: "Insumos" },
  "Insumos Críticos": { en: "Critical Supplies", es: "Insumos Críticos" },
  "Intenção Visual & Estilo": { en: "Visual Intent & Style", es: "Intención Visual y Estilo" },
  "Ir para o Dashboard": { en: "Go to Dashboard", es: "Ir al Panel" },
  "Item": { en: "Item", es: "Elemento" },
  "LUCRO REAL": { en: "NET PROFIT", es: "BENEFICIO REAL" },
  "Labs Center": { en: "Labs Center", es: "Centro de Laboratorio" },
  "Lançamento / Sucesso": { en: "Launch / Success", es: "Lanzamiento / Éxito" },
  "Lançamentos": { en: "Transactions", es: "Movimientos" },
  "Latência Global": { en: "Global Latency", es: "Latencia Global" },
  "Lead": { en: "Lead", es: "Prospecto" },
  "Leitura Dislexia": { en: "Dyslexia Friendly Font", es: "Fuente para Dislexia" },
  "Leitura do título e resumo em Português": { en: "Voice reading in system language", es: "Lectura por voz en el idioma del sistema" },
  "Leitura por áudio não suportada neste navegador.": { en: "Text-to-speech not supported in this browser.", es: "Lectura por voz no soportada en este navegador." },
  "Lembrar usuários de atualizar kWh": { en: "Remind users to update kWh rate", es: "Recordar actualizar tarifa de kWh" },
  "Limpar": { en: "Clear", es: "Limpiar" },
  "Limpar busca": { en: "Clear search", es: "Limpiar búsqueda" },
  "Limpeza Legal de Logs com mais de 180 dias (Marco Civil Art. 15)": { en: "Statutory Log Cleanup older than 180 days", es: "Limpieza Legal de Registros de más de 180 días" },
  "Live Monitor": { en: "Live Monitor", es: "Monitor en Vivo" },
  "Login Google": { en: "Google Sign-In", es: "Iniciar sesión con Google" },
  "Logo": { en: "Logo", es: "Logotipo" },
  "Logo PrintLog": { en: "PrintLog Logo", es: "Logo de PrintLog" },
  "Logo do Estúdio": { en: "Studio Logo", es: "Logo del Estudio" },
  "Lucro": { en: "Profit", es: "Beneficio" },
  "Lucro Acumulado": { en: "Accumulated Profit", es: "Beneficio Acumulado" },
  "Lucro Estimado": { en: "Estimated Profit", es: "Beneficio Estimado" },
  "Lucro Garantido": { en: "Guaranteed Profit", es: "Beneficio Garantizado" },
  "Lucro Líquido": { en: "Net Profit", es: "Beneficio Neto" },
  "Lucro Real": { en: "Net Profit", es: "Beneficio Real" },
  "Lucro Real Médio": { en: "Avg Real Profit", es: "Beneficio Real Medio" },
  "Lucro Real.": { en: "Real Profit.", es: "Beneficio Real." },
  "MAIS QUE UM SOFTWARE,": { en: "MORE THAN SOFTWARE,", es: "MÁS QUE UN SOFTWARE," },
  "MAKER FUNDADOR": { en: "FOUNDER MAKER", es: "CREADOR FUNDADOR" },
  "MATERIAL": { en: "MATERIAL", es: "MATERIAL" },
  "Maker (E-mail & ID)": { en: "Maker (Email & ID)", es: "Maker (Correo e ID)" },
  "Maker Fundador": { en: "Founder Maker", es: "Creador Fundador" },
  "Makers & Planos": { en: "Makers & Plans", es: "Makers y Planes" },
  "Makers Pro": { en: "Makers Pro", es: "Makers Pro" },
  "Manutenção Necessária": { en: "Maintenance Required", es: "Mantenimiento Requerido" },
  "Manutenção Reativa": { en: "Reactive Maintenance", es: "Mantenimiento Reactivo" },
  "Manutenção preventiva recomendada": { en: "Preventative maintenance recommended", es: "Mantenimiento preventivo recomendado" },
  "Marca": { en: "Brand", es: "Marca" },
  "Margem de Lucro": { en: "Profit Margin", es: "Margen de Beneficio" },
  "Materiais": { en: "Materials", es: "Materiales" },
  "Materiais Críticos": { en: "Critical Materials", es: "Materiales Críticos" },
  "Material": { en: "Material", es: "Material" },
  "Membro Fundador": { en: "Founding Member", es: "Miembro Fundador" },
  "Mensal": { en: "Monthly", es: "Mensual" },
  "Mesa": { en: "Bed", es: "Cama" },
  "Meus Insumos": { en: "My Supplies", es: "Mis Insumos" },
  "Meus Materiais": { en: "My Materials", es: "Mis Materiales" },
  "Minhas Impressoras": { en: "My 3D Printers", es: "Mis Impresoras 3D" },
  "Minimização de Dados": { en: "Data Minimization", es: "Minimización de Datos" },
  "Minutos": { en: "Minutes", es: "Minutos" },
  "Modelo": { en: "Model", es: "Modelo" },
  "Modo Silencioso": { en: "Silent Mode", es: "Modo Silencioso" },
  "Monitor de Reposição": { en: "Replenishment Monitor", es: "Monitor de Reposición" },
  "Monitore falhas e sucatas para otimizar sua margem de lucro.": { en: "Monitor failures and scrap to optimize your profit margin.", es: "Supervise fallos y desperdicios para optimizar su margen de beneficio." },
  "Motor de Orçamentação Avançado": { en: "Advanced Quotation Engine", es: "Motor de Presupuestos Avanzado" },
  "Mover para baixo": { en: "Move down", es: "Mover hacia abajo" },
  "Mover para cima": { en: "Move up", es: "Mover hacia arriba" },
  "Métricas Básicas de Lucratividade": { en: "Basic Profitability Metrics", es: "Métricas Básicas de Rentabilidad" },
  "Navegação & Foco": { en: "Navigation & Focus", es: "Navegación y Foco" },
  "Nenhum alerta recente": { en: "No recent alerts", es: "Ninguna alerta reciente" },
  "Nenhum aviso configurado": { en: "No notices configured", es: "Ningún aviso configurado" },
  "Nenhum aviso no quadro.": { en: "No notices on board.", es: "Ningún aviso en el tablón." },
  "Nenhum chamado encontrado": { en: "No tickets found", es: "Ningún ticket encontrado" },
  "Nenhum cliente cadastrado": { en: "No clients registered yet", es: "Ningún cliente registrado" },
  "Nenhum cliente encontrado": { en: "No clients found", es: "Ningún cliente encontrado" },
  "Nenhum cliente no radar": { en: "No clients on radar", es: "Ningún cliente en el radar" },
  "Nenhum insumo cadastrado": { en: "No supplies registered", es: "Ningún insumo registrado" },
  "Nenhum material cadastrado": { en: "No materials registered", es: "Ningún material registrado" },
  "Nenhum pedido na fila": { en: "No orders in queue", es: "Ningún pedido en cola" },
  "Nenhum registro": { en: "No records", es: "Ningún registro" },
  "Nenhum usuário encontrado": { en: "No users found", es: "Ningún usuario encontrado" },
  "Nenhum usuário para exportar.": { en: "No users to export.", es: "Ningún usuario para exportar." },
  "Nenhuma impressora cadastrada": { en: "No 3D printers registered", es: "Ninguna impresora registrada" },
  "Nenhuma transação encontrada": { en: "No transactions found", es: "Ninguna transacción encontrada" },
  "Nome": { en: "Name", es: "Nombre" },
  "Nome Completo": { en: "Full Name", es: "Nombre Completo" },
  "Nome do Estúdio": { en: "Studio Name", es: "Nombre del Estudio" },
  "Normal": { en: "Normal", es: "Normal" },
  "Notificações": { en: "Notifications", es: "Notificaciones" },
  "Nova Calculadora Maker": { en: "New Maker Calculator", es: "Nueva Calculadora Maker" },
  "Nova Máquina": { en: "New Printer", es: "Nueva Máquina" },
  "Novo": { en: "New", es: "Nuevo" },
  "Novo Cadastro": { en: "New Client", es: "Nuevo Registro" },
  "Novo Cadastro Manual": { en: "New Manual Client", es: "Nuevo Registro Manual" },
  "Novo Cliente": { en: "New Client", es: "Nuevo Cliente" },
  "Novo Estúdio (Fase 3)": { en: "New Studio (Phase 3)", es: "Nuevo Estudio (Fase 3)" },
  "Novo Insumo": { en: "New Supply", es: "Nuevo Insumo" },
  "Novo Lançamento": { en: "New Transaction", es: "Nuevo Movimiento" },
  "Novo Material": { en: "New Material", es: "Nuevo Material" },
  "Novo Orçamento": { en: "New Quote", es: "Nuevo Presupuesto" },
  "Novo Pedido": { en: "New Order", es: "Nuevo Pedido" },
  "Novos Clientes": { en: "New Clients", es: "Nuevos Clientes" },
  "Não configurado": { en: "Not configured", es: "No configurado" },
  "Não foi possível ativar seu plano agora.": { en: "Could not activate your plan right now.", es: "No fue posible activar su plan ahora." },
  "Não foi possível carregar as informações do servidor. Verifique sua conexão com a internet e tente novamente.": { en: "Could not load server information. Check your internet connection and try again.", es: "No se pudo cargar la información del servidor. Verifique su conexión y vuelva a intentarlo." },
  "Não foi possível copiar.": { en: "Could not copy.", es: "No se pudo copiar." },
  "Não há registros correspondentes aos filtros selecionados.": { en: "No records match the selected filters.", es: "No hay registros que coincidan con los filtros." },
  "Não é possível remover o único estúdio existente.": { en: "Cannot remove the only existing studio.", es: "No es posible eliminar el único estudio existente." },
  "O Cérebro da sua": { en: "The Brain Behind Your", es: "El Cerebro de su" },
  "O PrintLog nasceu da vontade de ver a comunidade 3D brasileira crescer com dignidade. Não estamos aqui pelo lucro, mas para manter este sistema vivo e ajudar você a eliminar o chutômetro. Junte-se a nós para manter este projeto online e evoluindo para todos.": { en: "PrintLog was born from the desire to see the 3D printing community grow with dignity. We are not here for profit, but to keep this system alive and help you eliminate guesswork. Join us to keep this project online and evolving for everyone.", es: "PrintLog nació del deseo de ver crecer a la comunidad de impresión 3D con dignidad. No estamos aquí por el lucro, sino para mantener este sistema vivo y ayudarle a eliminar las dudas. Únase a nosotros para mantener este proyecto en línea y evolucionando para todos." },
  "O PrintLog utiliza a autenticação segura do Google e GitHub para login ou cadastro simplificado em poucos cliques.": { en: "PrintLog uses secure Google and GitHub authentication for simple sign-in in just a few clicks.", es: "PrintLog utiliza autenticación segura de Google y GitHub para iniciar sesión o registrarse en pocos clics." },
  "O PrintLog é um projeto independente. Comece grátis e, se precisar de mais recursos, assine o plano PRO para ajudar a manter o servidor online.": { en: "PrintLog is an independent project. Start free, and if you need more features, subscribe to PRO to help keep the server online.", es: "PrintLog es un proyecto independiente. Comience gratis y, si necesita más funciones, suscríbase al plan PRO para ayudar a mantener el servidor en línea." },
  "Observações": { en: "Notes", es: "Observaciones" },
  "Oferta de Lançamento": { en: "Launch Offer", es: "Oferta de Lanzamiento" },
  "Operação Concluída": { en: "Operation Completed", es: "Operación Completada" },
  "Operação de Impressão.": { en: "3D Printing Operations.", es: "Operación de Impresión." },
  "Orçamento Rápido": { en: "Quick Quote", es: "Presupuesto Rápido" },
  "Orçamentos Profissionais Personalizados": { en: "Custom Professional Proposals", es: "Presupuestos Profesionales Personalizados" },
  "Orçamentos Recentes": { en: "Recent Quotes", es: "Presupuestos Recientes" },
  "Otimizar Preço com IA": { en: "Optimize Price with AI", es: "Optimizar Precio con IA" },
  "Otimização": { en: "Optimization", es: "Optimización" },
  "Otimização Avançada de Preço com IA": { en: "Advanced AI Pricing Optimization", es: "Optimización Avanzada de Precios con IA" },
  "PARE DE JOGAR": { en: "STOP THROWING", es: "DEJE DE TIRAR" },
  "PESQUISAR EM TODA A PLATAFORMA...": { en: "SEARCH ACROSS THE ENTIRE PLATFORM...", es: "BUSCAR EN TODA LA PLATAFORMA..." },
  "PLA Silk Dourado": { en: "Silk Gold PLA", es: "PLA Seda Dorado" },
  "PRINTLOG MOBILE": { en: "PRINTLOG MOBILE", es: "PRINTLOG MOBILE" },
  "PRONTA": { en: "READY", es: "LISTA" },
  "Pago": { en: "Paid", es: "Pagado" },
  "Painel Master": { en: "Master Panel", es: "Panel Master" },
  "Painel de Controle": { en: "Control Panel", es: "Panel de Control" },
  "Para profissionais que querem escalar seu estúdio 3D.": { en: "For professionals looking to scale their 3D studio.", es: "Para profesionales que quieren escalar su estudio 3D." },
  "Pare de perder dinheiro": { en: "Stop losing money", es: "Deje de perder dinero" },
  "Patrimônio": { en: "Asset Value", es: "Patrimonio" },
  "Pausado": { en: "Paused", es: "Pausado" },
  "Pausar Impressão": { en: "Pause Printing", es: "Pausar Impresión" },
  "Pedido Atrasado 🚨": { en: "Delayed Order 🚨", es: "Pedido Retrasado 🚨" },
  "Pedido alocado na fila de produção!": { en: "Order allocated to production queue!", es: "¡Pedido asignado a la cola de producción!" },
  "Pedido removido da fila de produção.": { en: "Order removed from production queue.", es: "Pedido eliminado de la cola de producción." },
  "Pedidos Ativos": { en: "Active Orders", es: "Pedidos Activos" },
  "Pendente": { en: "Pending", es: "Pendiente" },
  "Pequenos erros de cálculo destroem sua margem de lucro. O PrintLog elimina as variáveis invisíveis.": { en: "Small calculation errors destroy your profit margin. PrintLog eliminates invisible variables.", es: "Pequeños errores de cálculo destruyen su margen de beneficio. PrintLog elimina las variables invisibles." },
  "Perfil": { en: "Profile", es: "Perfil" },
  "Peso": { en: "Weight", es: "Peso" },
  "Pesquisar": { en: "Search", es: "Buscar" },
  "Pesquisar por nome, e-mail ou status...": { en: "Search by name, email or status...", es: "Buscar por nombre, correo o estado..." },
  "Peça Final": { en: "Final Part", es: "Pieza Final" },
  "Pink": { en: "Pink", es: "Rosa" },
  "Planilhas e cadernos perdem dados. Centralize sua produção e ganhe tempo.": { en: "Spreadsheets and notebooks lose data. Centralize your production and save time.", es: "Hojas de cálculo y cuadernos pierden datos. Centralice su producción y gane tiempo." },
  "Plano / Vencimento": { en: "Plan / Expiration", es: "Plan / Vencimiento" },
  "Plano Gratuito": { en: "Free Plan", es: "Plan Gratuito" },
  "Plano Maker Pro Vitalício": { en: "Lifetime Maker Pro Plan", es: "Plan Maker Pro Vitalicio" },
  "Plano PRO": { en: "PRO Plan", es: "Plan PRO" },
  "Plano renovado com sucesso!": { en: "Plan renewed successfully!", es: "¡Plan renovado con éxito!" },
  "Política de Cookies": { en: "Cookie Policy", es: "Política de Cookies" },
  "Política de Privacidade": { en: "Privacy Policy", es: "Política de Privacidad" },
  "Por favor, digite a mensagem do aviso antes de publicar.": { en: "Please enter the notice message before publishing.", es: "Por favor, introduzca el mensaje del aviso antes de publicar." },
  "Por favor, digite a resposta para o usuário.": { en: "Please enter a response for the user.", es: "Por favor, introduzca una respuesta para el usuario." },
  "Potencial": { en: "Pipeline", es: "Potencial" },
  "Precificação Errada": { en: "Wrong Pricing", es: "Precios Incorrectos" },
  "Precificação automática em segundos": { en: "Automated pricing in seconds", es: "Precios automáticos en segundos" },
  "Precisão Custos": { en: "Cost Accuracy", es: "Precisión de Costes" },
  "Preenchimento": { en: "Infill", es: "Relleno" },
  "Premium": { en: "Premium", es: "Premium" },
  "Preparando sua Farm...": { en: "Preparing your Print Farm...", es: "Preparando su Print Farm..." },
  "Preço Final": { en: "Final Price", es: "Precio Final" },
  "Preço Sugerido": { en: "Suggested Price", es: "Precio Sugerido" },
  "Preço de Venda": { en: "Sale Price", es: "Precio de Venta" },
  "Preços": { en: "Pricing", es: "Precios" },
  "PrintLog • Acessibilidade Universal": { en: "PrintLog • Universal Accessibility", es: "PrintLog • Accesibilidad Universal" },
  "Privacidade": { en: "Privacy", es: "Privacidad" },
  "Produção": { en: "Production", es: "Producción" },
  "Produção Ativa": { en: "Active Production", es: "Producción Activa" },
  "Projeto concluído! Impressora liberada.": { en: "Project completed! Printer released.", es: "¡Proyecto finalizado! Impresora liberada." },
  "Projetos": { en: "Projects", es: "Proyectos" },
  "Proteção de Dados (AES-256)": { en: "Data Protection (AES-256)", es: "Protección de Datos (AES-256)" },
  "Público Ativo": { en: "Active Audience", es: "Público Activo" },
  "Quadro de Avisos": { en: "Notice Board", es: "Tablón de Anuncios" },
  "R$ 12.840": { en: "$2,560", es: "2.560 €" },
  "R$ 7.120": { en: "$1,420", es: "1.420 €" },
  "REPOR": { en: "RESTOCK", es: "REPONER" },
  "ROI Estimado": { en: "Estimated ROI", es: "ROI Estimado" },
  "ROLE PARA DESCOBRIR": { en: "SCROLL TO DISCOVER", es: "DESLICE PARA DESCUBRIR" },
  "Real-time": { en: "Real-time", es: "Tiempo real" },
  "Realçar Links": { en: "Highlight Links", es: "Resaltar Enlaces" },
  "Recarregar base de dados": { en: "Reload database", es: "Recargar base de datos" },
  "Recarregar chamados": { en: "Reload tickets", es: "Recargar tickets" },
  "Receita": { en: "Income", es: "Ingreso" },
  "Receita Total": { en: "Total Revenue", es: "Ingresos Totales" },
  "Receitas": { en: "Incomes", es: "Ingresos" },
  "Reduzir Animações": { en: "Reduce Animations", es: "Reducir Animaciones" },
  "Registrar Lançamento": { en: "Record Transaction", es: "Registrar Movimiento" },
  "Registrar Transação": { en: "Record Transaction", es: "Registrar Transacción" },
  "Registre as falhas e inclua na margem de risco automaticamente no preço.": { en: "Record failures and automatically include them in your pricing risk margin.", es: "Registre los fallos e inclúyalos en el margen de riesgo automáticamente en el precio." },
  "Registro órfão excluído com sucesso.": { en: "Orphan record deleted successfully.", es: "Registro huérfano eliminado con éxito." },
  "Remover": { en: "Remove", es: "Quitar" },
  "Remover da fila": { en: "Remove from queue", es: "Quitar de la cola" },
  "Renovar ciclo atual": { en: "Renew current cycle", es: "Renovar ciclo actual" },
  "Repor": { en: "Restock", es: "Reponer" },
  "Repor Insumo (Resina/Peças)": { en: "Restock Supply (Resin/Parts)", es: "Reponer Insumo (Resina/Piezas)" },
  "Repor Material (Filamento)": { en: "Restock Material (Filament)", es: "Reponer Material (Filamento)" },
  "Reposição": { en: "Restock", es: "Reposición" },
  "Reposição de Estoque": { en: "Restock Inventory", es: "Reposición de Stock" },
  "Resina": { en: "Resin", es: "Resina" },
  "Resinas": { en: "Resins", es: "Resinas" },
  "Resinas (SLA)": { en: "Resins (SLA)", es: "Resinas (SLA)" },
  "Resolvido (Finalizado com sucesso)": { en: "Resolved (Successfully completed)", es: "Resuelto (Finalizado con éxito)" },
  "Resolvidos": { en: "Resolved", es: "Resueltos" },
  "Respondido (Aguardando cliente)": { en: "Answered (Awaiting client)", es: "Respondido (Esperando al cliente)" },
  "Respondidos": { en: "Answered", es: "Respondidos" },
  "Resposta gravada com sucesso! O usuário já pode vê-la no app.": { en: "Response saved successfully! The user can now view it.", es: "¡Respuesta guardada con éxito! El usuario ya puede verla en la app." },
  "Restaurar Padrão": { en: "Restore Defaults", es: "Restablecer Valores" },
  "Role para descobrir": { en: "Scroll to discover", es: "Deslice para descobrir" },
  "Rolo no Fim": { en: "Spool Low", es: "Bobina al Final" },
  "SETUP": { en: "SETUP", es: "AJUSTE" },
  "SEUS DADOS.": { en: "YOUR DATA.", es: "SUS DATOS." },
  "Sair": { en: "Sign Out", es: "Cerrar Sesión" },
  "Sair da Conta": { en: "Sign Out", es: "Cerrar Sesión" },
  "Salvando alterações em background...": { en: "Saving changes in background...", es: "Guardando cambios en segundo plano..." },
  "Salvando...": { en: "Saving...", es: "Guardando..." },
  "Salvar": { en: "Save", es: "Guardar" },
  "Salvar Alterações": { en: "Save Changes", es: "Guardar Cambios" },
  "Saída": { en: "Outflow", es: "Salida" },
  "Segurança": { en: "Security", es: "Seguridad" },
  "Segurança e Privacidade": { en: "Security and Privacy", es: "Seguridad y Privacidad" },
  "Selecione um operador": { en: "Select an operator", es: "Seleccione un operador" },
  "Selecione uma opção": { en: "Select an option", es: "Seleccione una opción" },
  "Sem acréscimo tarifário (condições normais)": { en: "No tariff surcharge (normal conditions)", es: "Sin recargo de tarifa (condiciones normales)" },
  "Sem e-mail registrado": { en: "No email recorded", es: "Sin correo registrado" },
  "Sem máquinas ativas": { en: "No active machines", es: "Sin máquinas activas" },
  "Sem vencimento": { en: "No expiration", es: "Sin vencimiento" },
  "Semestral": { en: "Semi-annual", es: "Semestral" },
  "Sequenciamento visual e planejamento de impressões por máquina": { en: "Visual sequencing and machine print job scheduling", es: "Secuenciación visual y planificación de impresiones por máquina" },
  "Ser um Maker Fundador": { en: "Become a Founding Maker", es: "Ser un Maker Fundador" },
  "Sessão expirada ou não autorizada. Por favor, logue novamente.": { en: "Session expired or unauthorized. Please log in again.", es: "Sesión caducada o no autorizada. Por favor, inicie sesión de nuevo." },
  "Setup": { en: "Setup", es: "Ajuste" },
  "Seu melhor e-mail corporativo": { en: "Your business email address", es: "Su mejor correo electrónico" },
  "Simular em Computador / Telas Grandes": { en: "Simulate on Desktop / Large Screens", es: "Simular en Ordenador / Pantallas Grandes" },
  "Simular em Smartphone": { en: "Simulate on Smartphone", es: "Simular en Smartphone" },
  "Sincronização imediata na Edge via Cloudflare D1": { en: "Immediate Edge sync via Cloudflare D1", es: "Sincronización inmediata en el Edge vía Cloudflare D1" },
  "Sistema": { en: "System", es: "Sistema" },
  "Sistema de gestão para makers 3D. Calcule com precisão seus custos de impressão e maximize seus lucros.": { en: "Management platform for 3D makers. Accurately calculate printing costs and maximize your profits.", es: "Sistema de gestión para makers 3D. Calcule con precisión sus costes de impresión y maximice sus beneficios." },
  "Slogan": { en: "Slogan", es: "Eslogan" },
  "Slogan do Estúdio": { en: "Studio Slogan", es: "Slogan del Estudio" },
  "Solicitante": { en: "Requester", es: "Solicitante" },
  "Status": { en: "Status", es: "Estado" },
  "Status das Máquinas": { en: "Machine Status", es: "Estado de las Máquinas" },
  "Status de Matéria-Prima": { en: "Raw Material Status", es: "Estado de Materias Primas" },
  "Studio": { en: "Studio", es: "Estudio" },
  "Sua Farm,": { en: "Your Print Farm,", es: "Su Print Farm," },
  "Sua base de clientes está vazia. Comece cadastrando um cliente VIP para iniciar seu ecossistema.": { en: "Your customer base is empty. Start by registering a VIP customer to kick off your ecosystem.", es: "Su base de clientes está vacía. Comience registrando un cliente VIP para iniciar su ecosistema." },
  "Sua opinião molda o futuro do PrintLog.": { en: "Your feedback shapes the future of PrintLog.", es: "Su opinión da forma al futuro de PrintLog." },
  "Sua sessão irá expirar em 1 minuto por inatividade.": { en: "Your session will expire in 1 minute due to inactivity.", es: "Su sesión caducará en 1 minuto por inactividad." },
  "Subtotal": { en: "Subtotal", es: "Subtotal" },
  "Sucesso": { en: "Success", es: "Éxito" },
  "Suficiente para esta impressão": { en: "Sufficient for this print", es: "Suficiente para esta impressão" },
  "Suficiente para esta impressão (112g)": { en: "Sufficient for this print (112g)", es: "Suficiente para esta impressão (112g)" },
  "Sugestões de Preço via IA (Llama 3)": { en: "AI Price Suggestions (Llama 3)", es: "Sugerencias de Precio con IA (Llama 3)" },
  "Suggested Price": { en: "Suggested Price", es: "Precio Sugerido" },
  "Suporte via e-mail": { en: "Email Support", es: "Soporte por correo" },
  "Suportes e sobras de filamento são lucro indo para o lixo. Controle cada grama.": { en: "Supports and filament scraps are profits going to waste. Track every gram.", es: "Soportes y restos de filamento son beneficios yendo a la basura. Controle cada gramo." },
  "TRANSFORME": { en: "TRANSFORM", es: "TRANSFORME" },
  "Tamanho do Texto": { en: "Text Size", es: "Tamaño del Texto" },
  "Taxa Sucesso": { en: "Success Rate", es: "Tasa de Éxito" },
  "Telefone": { en: "Phone", es: "Teléfono" },
  "Tema Claro": { en: "Light Mode", es: "Modo Claro" },
  "Tema Escuro": { en: "Dark Mode", es: "Modo Oscuro" },
  "Temperatura": { en: "Temperature", es: "Temperatura" },
  "Tempo Estimado": { en: "Estimated Time", es: "Tiempo Estimado" },
  "Tempo de Impressão": { en: "Print Time", es: "Tiempo de Impresión" },
  "Tente ajustar os filtros ou cadastrar um novo cliente": { en: "Try adjusting filters or registering a new client", es: "Intente ajustar los filtros o registrar un nuevo cliente" },
  "Termos de Serviço": { en: "Terms of Service", es: "Términos de Servicio" },
  "Ticket Médio": { en: "Average Ticket", es: "Ticket Medio" },
  "Tipo": { en: "Type", es: "Tipo" },
  "Todas as Categorias": { en: "All Categories", es: "Todas las Categorías" },
  "Todas as alterações foram salvas automaticamente": { en: "All changes were automatically saved", es: "Todos los cambios se guardaron automáticamente" },
  "Todos os Status": { en: "All Statuses", es: "Todos los Estados" },
  "Todos os direitos reservados.": { en: "All rights reserved.", es: "Todos los derechos reservados." },
  "Total": { en: "Total", es: "Total" },
  "Total Impresso": { en: "Total Printed", es: "Total Impreso" },
  "Total Makers": { en: "Total Makers", es: "Total de Makers" },
  "Total de Projetos": { en: "Total Projects", es: "Total de Proyectos" },
  "Transforme": { en: "Transform", es: "Transforme" },
  "Transforme cálculos em propostas profissionais com a identidade do seu estúdio.": { en: "Turn calculations into professional proposals with your studio's brand identity.", es: "Transforme cálculos en presupuestos profesionales con la identidad de su estudio." },
  "Transparência em primeiro lugar — 100% gratuito e em constante evolução junto com a comunidade 3D brasileira.": { en: "Transparency first — 100% free and constantly evolving together with the 3D maker community.", es: "Transparencia ante todo — 100% gratuito y en constante evolución junto con la comunidad 3D." },
  "Transparência é Tudo.": { en: "Transparency is Everything.", es: "La Transparencia lo es Todo." },
  "Trimestral": { en: "Quarterly", es: "Trimestral" },
  "Tudo do plano Gratuito": { en: "Everything in Free plan", es: "Todo lo del plan Gratuito" },
  "Tudo limpo por aqui, Maker!": { en: "All clear here, Maker!", es: "¡Todo limpio por aquí, Maker!" },
  "Tudo sob controle.": { en: "All under control.", es: "Todo bajo control." },
  "Tudo sob controle. Nenhum aviso no quadro.": { en: "All under control. No notices on the board.", es: "Todo bajo control. Ningún aviso en el tablón." },
  "Técnico / Atualização": { en: "Technical / Update", es: "Técnico / Actualización" },
  "UMA MISSÃO.": { en: "A MISSION.", es: "UNA MISIÓN." },
  "Urgente": { en: "Urgent", es: "Urgente" },
  "User": { en: "User", es: "Usuario" },
  "VER DETALHES": { en: "VIEW DETAILS", es: "VER DETALLES" },
  "VER TODOS": { en: "VIEW ALL", es: "VER TODOS" },
  "VERIFICAR AGORA": { en: "CHECK NOW", es: "VERIFICAR AHORA" },
  "Valor": { en: "Value", es: "Valor" },
  "Valor em Estoque": { en: "Inventory Value", es: "Valor en Stock" },
  "Variáveis Obrigatórias:": { en: "Required Variables:", es: "Variables Obligatorias:" },
  "Vaso Decorativo (PLA)": { en: "Decorative Vase (PLA)", es: "Jarrón Decorativo (PLA)" },
  "Velocidade": { en: "Speed", es: "Velocidad" },
  "Vender barato demais e pagar para trabalhar? Nunca mais. Saiba seu custo real.": { en: "Selling too cheap and paying to work? Never again. Know your real cost.", es: "¿Vender demasiado barato y pagar por trabajar? Nunca más. Conozca su coste real." },
  "Ver Detalhes": { en: "View Details", es: "Ver Detalles" },
  "Ver Fila de Produção": { en: "View Print Queue", es: "Ver Cola de Producción" },
  "Ver Todos": { en: "View All", es: "Ver Todos" },
  "Ver todos": { en: "View all", es: "Ver todos" },
  "Verificando credenciais do Dono...": { en: "Verifying Owner credentials...", es: "Comprobando credenciales de Propietario..." },
  "Verificar E-mail": { en: "Verify Email", es: "Verificar Correo" },
  "Viper Core 01": { en: "Viper Core 01", es: "Viper Core 01" },
  "Viper Core 03": { en: "Viper Core 03", es: "Viper Core 03" },
  "Visualizar": { en: "View", es: "Visualizar" },
  "Visão Geral e Métricas em Tempo Real": { en: "Overview & Real-Time Metrics", es: "Visión General y Métricas en Tiempo Real" },
  "Vitalício": { en: "Lifetime", es: "Vitalicio" },
  "Vocalizando conteúdo da tela...": { en: "Reading screen content...", es: "Leyendo contenido de pantalla..." },
  "Vocalizar Tela": { en: "Screen Reader / Text to Speech", es: "Lector de Pantalla" },
  "Você precisa verificar seu e-mail no Perfil antes de ativar este plano.": { en: "You need to verify your email in Profile before activating this plan.", es: "Debe verificar su correo electrónico en su Perfil antes de activar este plan." },
  "Voltar": { en: "Back", es: "Volver" },
  "Voltar ao Painel": { en: "Back to Dashboard", es: "Volver al Panel" },
  "Voltar ao site": { en: "Back to website", es: "Volver al sitio web" },
  "Volume de Pedidos": { en: "Order Volume", es: "Volumen de Pedidos" },
  "WCAG 2.1 AA • Lei nº 13.146/2015 (LBI)": { en: "WCAG 2.1 AA • Accessibility Standards", es: "WCAG 2.1 AA • Estándares de Accesibilidad" },
  "WhatsApp": { en: "WhatsApp", es: "WhatsApp" },
  "WhatsApp (Link)": { en: "WhatsApp (Link)", es: "WhatsApp (Enlace)" },
  "WhatsApp (PDF)": { en: "WhatsApp (PDF)", es: "WhatsApp (PDF)" },
  "Zero": { en: "Zero", es: "Cero" },
  "\\\\\\\\\\\\\\\"Transparência em primeiro lugar — 100% gratuito e em constante evolução junto com a comunidade 3D brasileira.\\\\\\\\\\\\\\\"": { en: "\\\\\\\\\\\\\\\"Transparency first — 100% free and constantly evolving together with the 3D maker community.\\\\\\\\\\\\\\\"", es: "\\\\\\\\\\\\\\\"Transparencia ante todo — 100% gratuito y en constante evolución junto con la comunidad 3D.\\\\\\\\\\\\\\\"" },
  "\\\\\\\\\\\\\\\"chutômetro\\\\\\\\\\\\\\\"": { en: "\\\\\\\\\\\\\\\"guesswork\\\\\\\\\\\\\\\"", es: "\\\\\\\\\\\\\\\"estimaciones a ojo\\\\\\\\\\\\\\\"" },
  "chutômetro": { en: "guesswork", es: "estimaciones a ojo" },
  "e com a": { en: "and our", es: "y la" },
  "em Lucro": { en: "into Profit", es: "en Beneficio" },
  "em Lucro.": { en: "into Profit.", es: "en Beneficio." },
  "em até 7d": { en: "within 7d", es: "en hasta 7d" },
  "em conformidade com a LGPD (Art. 7º, V).": { en: "in compliance with LGPD (Art. 7, V).", es: "en conformidad con la LGPD (Art. 7º, V)." },
  "entradas este mês": { en: "new this month", es: "entradas este mes" },
  "faturamento LTV": { en: "LTV revenue", es: "facturación LTV" },
  "parceiros ativos": { en: "active partners", es: "socios activos" },
  "projetos entregues": { en: "delivered projects", es: "proyectos entregados" },
  "sempre": { en: "forever", es: "siempre" },
  "tempo limitado": { en: "limited time", es: "tiempo limitado" },
  "~25ms (Edge D1)": { en: "~25ms (Edge D1)", es: "~25ms (Edge D1)" },
  "Última Atividade": { en: "Last Activity", es: "Última Actividad" },
  "Últimos 30 dias": { en: "Last 30 days", es: "Últimos 30 días" },
  "⚠️ Manutenção preventiva programada para hoje às 23h. Duração estimada: 15 minutos.": { en: "⚠️ Scheduled preventative maintenance tonight at 11 PM. Estimated duration: 15 mins.", es: "⚠️ Mantenimiento programado hoy a las 23:00. Duración estimada: 15 minutos." },
  "❓ Dúvidas": { en: "❓ Questions", es: "❓ Dudas" },
  "🐛 Bugs / Falhas": { en: "🐛 Bugs / Issues", es: "🐛 Errores / Fallos" },
  "👑 Restam poucas vagas no Clube Fundador Vitalício com suporte prioritário e sem mensalidades!": { en: "👑 Few spots left in the Lifetime Founder Club with priority support and no monthly fees!", es: "👑 ¡Pocas plazas en el Club Fundador Vitalicio con soporte prioritario y sin mensualidades!" },
  "💡 Dica Maker: Atualize o valor do kWh da sua região em Configurações para orçamentos sem prejuízo.": { en: "💡 Maker Tip: Update your regional kWh rate in Settings for accurate quotes.", es: "💡 Consejo Maker: Actualice la tarifa de kWh en Configuración para presupuestos precisos." },
  "💡 Sugestões": { en: "💡 Suggestions", es: "💡 Sugerencias" },
  "💳 Financeiro": { en: "💳 Financial", es: "💳 Financiero" },
  "🚀 Nova Calculadora Maker 2.0 liberada! Simule custos com energia e desgaste precisos.": { en: "🚀 New Maker Calculator 2.0 released! Simulate costs with precise energy and wear.", es: "🚀 ¡Nueva Calculadora Maker 2.0 lanzada! Simule costes con consumo y desgaste precisos." },
  "🚨 Emergência": { en: "🚨 Emergency", es: "🚨 Emergencia" },
};
