import { DicionarioTraducao } from "./tipos";

export const dicionarioSistema: DicionarioTraducao = {
  "• Regra de Avaliação (Trial Sem Cartão):": { en: "• Evaluation Policy (Cardless Trial):", es: "• Regla de Evaluación (Prueba Sin Tarjeta):" },
  "• Renovação e Cancelamento:": { en: "• Renewal & Cancellation:", es: "• Renovación y Cancelación:" },
  "• Segurança Financeira:": { en: "• Financial Security:", es: "• Seguridad Financiera:" },
  "⚠️ Alerta Técnico de Operação:": { en: "⚠️ Operational Technical Warning:", es: "⚠️ Alerta Técnica de Operación:" },
  "⚠️ Cláusula Pro-Maker:": { en: "⚠️ Pro-Maker Clause:", es: "⚠️ Cláusula Pro-Maker:" },
  "❓ Dúvida de Uso do Sistema": { en: "❓ Question about System Usage", es: "❓ Duda sobre el Uso del Sistema" },
  "🐛 Relato de Bug / Erro Técnico": { en: "🐛 Bug Report / Technical Error", es: "🐛 Reporte de Fallo / Error Técnico" },
  "💡 Como exercer seus direitos:": { en: "💡 How to exercise your rights:", es: "💡 Cómo ejercer sus derechos:" },
  "💡 Sugestão de Nova Funcionalidade": { en: "💡 Feature Suggestion", es: "💡 Sugerencia de Nueva Función" },
  "💬 Outro Assunto": { en: "💬 Other Subject", es: "💬 Otro Asunto" },
  "💳 Plano / Pagamento": { en: "💳 Plan / Billing", es: "💳 Plan / Facturación" },
  "🚨 Emergência Operacional": { en: "🚨 Operational Emergency", es: "🚨 Emergencia Operativa" },
  "1. Introdução": { en: "1. Introduction", es: "1. Introducción" },
  "1. Objeto do Contrato": { en: "1. Contract Scope", es: "1. Objeto del Contrato" },
  "2. Filosofia de Uso no PrintLog": { en: "2. Usage Philosophy at PrintLog", es: "2. Filosofía de Uso en PrintLog" },
  "2. Fornecimento \"AS IS\" (Como Está) e Disponibilidade": { en: "2. \"AS IS\" Provision and Availability", es: "2. Suministro \"AS IS\" (Tal Cual) y Disponibilidad" },
  "2. Sobre o PrintLog e Responsáveis": { en: "2. About PrintLog and Parties Involved", es: "2. Acerca de PrintLog y Responsables" },
  "2FA desativado com sucesso.": { en: "2FA disabled successfully.", es: "¡2FA desactivado con éxito!" },
  "3. Dados Coletados e Finalidades": { en: "3. Collected Data and Purposes", es: "3. Datos Recopilados y Finalidades" },
  "3. Inventário de Cookies Utilizados": { en: "3. Inventory of Cookies Used", es: "3. Inventario de Cookies Utilizadas" },
  "3. Propriedade Intelectual e Restrições": { en: "3. Intellectual Property and Restrictions", es: "3. Propiedad Intelectual y Restricciones" },
  "3.2. Dados de Negócio (Impressão 3D)": { en: "3.2. Business Data (3D Printing)", es: "3.2. Datos de Negocio (Impresión 3D)" },
  "3.3. Dados Financeiros (Plano Maker Pro)": { en: "3.3. Financial Data (Maker Pro Plan)", es: "3.3. Datos Financieros (Plan Maker Pro)" },
  "4. Base Legal para o Tratamento": { en: "4. Legal Basis for Processing", es: "4. Base Legal para el Tratamiento" },
  "4. Gerenciamento e Revogação": { en: "4. Management and Revocation", es: "4. Gestión y Revocación" },
  "4. Isenção Total de Responsabilidade Comercial e Física": { en: "4. Full Disclaimer of Commercial and Physical Liability", es: "4. Exención Total de Responsabilidad Comercial y Física" },
  "5. Planos, Cobrança e Política de Não-Surpresa": { en: "5. Plans, Billing and No-Surprise Policy", es: "5. Planes, Facturación y Política de No-Sorpresas" },
  "5. Seus Direitos (LGPD)": { en: "5. Your Privacy Rights", es: "5. Sus Derechos de Privacidad" },
  "6. Rescisão e Limpeza de Dados": { en: "6. Termination and Data Deletion", es: "6. Rescisión y Limpieza de Datos" },
  "6. Segurança e Isolamento de Dados": { en: "6. Security and Data Isolation", es: "6. Seguridad y Aislamiento de Datos" },
  "7. Cookies Essenciais": { en: "7. Essential Cookies", es: "7. Cookies Esenciales" },
  "7. Modificações, Contato Legal e Foro": { en: "7. Modifications, Legal Contact and Jurisdiction", es: "7. Modificaciones, Contacto Legal y Jurisdicción" },
  "8. Retenção e Exclusão": { en: "8. Retention and Deletion", es: "8. Retención y Eliminación" },
  "Abrindo prévia no WhatsApp!": { en: "Opening WhatsApp preview!", es: "¡Abriendo vista previa en WhatsApp!" },
  "Abrir Chamado": { en: "Open Ticket", es: "Abrir Ticket" },
  "Abrir menu de opções": { en: "Open options menu", es: "Abrir menú de opciones" },
  "Acesse funcionalidades experimentais antecipadas. Disponível nos planos": { en: "Access early experimental features. Available on plans", es: "Acceda a funciones experimentales anticipadas. Disponible en los planes" },
  "Acesse ou Crie sua conta": { en: "Sign In or Create Account", es: "Inicie Sesión o Cree su Cuenta" },
  "Acesso antecipado a novas funcionalidades experimentais": { en: "Early access to new experimental features", es: "Acceso anticipado a nuevas funcionalidades experimentales" },
  "Acesso Antecipado e Experimental": { en: "Early & Experimental Access", es: "Acceso Anticipado y Experimental" },
  "Acesso Negado: Faça login novamente para exportar seus dados.": { en: "Access Denied: Log in again to export your data.", es: "Acceso Denegado: Inicie sesión nuevamente para exportar sus datos." },
  "Acesso Restrito ao Dono": { en: "Owner Restricted Access", es: "Acceso Restringido al Propietario" },
  "Administrador": { en: "Administrator", es: "Administrador" },
  "Agrupar por Cores": { en: "Group by Colors", es: "Agrupar por Colores" },
  "Alta (Impacta minha rotina)": { en: "High (Impacts my workflow)", es: "Alta (Afecta mi rutina)" },
  "Alta (Impacta produção)": { en: "High (Impacts production)", es: "Alta (Afecta la producción)" },
  "Alta Performance": { en: "High Performance", es: "Alto Rendimiento" },
  "Alterações Frequentes": { en: "Frequent Changes", es: "Cambios Frecuentes" },
  "Alterações pendentes": { en: "Pending changes", es: "Cambios pendientes" },
  "Alterações salvas com sucesso!": { en: "Changes saved successfully!", es: "¡Cambios guardados con éxito!" },
  "Alterar Foto": { en: "Change Photo", es: "Cambiar Foto" },
  "Alterne entre múltiplas contas do PrintLog de forma isolada.": { en: "Switch between multiple PrintLog accounts in isolation.", es: "Alterne entre múltiples cuentas de PrintLog de forma aislada." },
  "Âmbar": { en: "Amber", es: "Ámbar" },
  "AO VIVO NO APP": { en: "LIVE IN APP", es: "EN VIVO EN LA APP" },
  "Aparência Visual": { en: "Visual Appearance", es: "Apariencia Visual" },
  "Ardósia": { en: "Slate", es: "Pizarra" },
  "Arquitetura de banco de dados projetada para garantir que seus custos de materiais, margens de lucro e projetos sejam tecnicamente invisíveis e inacessíveis para qualquer outro usuário.": { en: "Database architecture designed to ensure material costs, margins and projects are strictly inaccessible to other users.", es: "Arquitectura de base de datos diseñada para garantizar que sus costes, márgenes y proyectos sean inaccesibles para otros usuarios." },
  "Arquivo de códigos baixado com sucesso!": { en: "Recovery codes file downloaded successfully!", es: "¡Archivo de códigos descargado con éxito!" },
  "Artigos e Guias": { en: "Articles & Guides", es: "Artículos y Guías" },
  "Ativar 2FA (Recomendado)": { en: "Enable 2FA (Recommended)", es: "Activar 2FA (Recomendado)" },
  "Ativo agora": { en: "Active now", es: "Activo ahora" },
  "Autenticação em 2 Etapas (Google Authenticator) ativada com sucesso!": { en: "Two-Factor Authentication (Authenticator) enabled successfully!", es: "¡Autenticación en 2 pasos activada con éxito!" },
  "Autenticação em 2 Etapas (TOTP)": { en: "2-Step Authentication (TOTP)", es: "Autenticación en 2 Pasos (TOTP)" },
  "Autenticação em Duas Etapas (2FA)": { en: "Two-Factor Authentication (2FA)", es: "Autenticación en Dos Pasos (2FA)" },
  "Autenticação em duas etapas (2FA) e sessões ativas": { en: "Two-factor authentication (2FA) and active sessions", es: "Autenticación en dos pasos (2FA) y sesiones activas" },
  "Autenticação. Mantém a sessão do usuário ativa e conectada de forma segura.": { en: "Authentication. Keeps user session active and securely connected.", es: "Autenticación. Mantiene la sesión del usuario activa de forma segura." },
  "Aviso da plataforma": { en: "Platform notice", es: "Aviso de la plataforma" },
  "Azul": { en: "Blue", es: "Azul" },
  "Backups:": { en: "Backups:", es: "Copias de Seguridad:" },
  "Baixa (Posso aguardar)": { en: "Low (Can wait)", es: "Baja (Puedo esperar)" },
  "Baixe um arquivo JSON com seus metadados de cadastro (Art. 18, V).": { en: "Download a JSON file containing your account metadata (Art. 18, V).", es: "Descargue un archivo JSON con los metadatos de su cuenta (Art. 18, V)." },
  "Base de Conhecimento": { en: "Knowledge Base", es: "Base de Conocimiento" },
  "Base de conhecimento dinâmica para otimização de frotas 3D e processos de manufatura.": { en: "Dynamic knowledge base for 3D fleet optimization and manufacturing processes.", es: "Base de conocimiento dinámica para optimización de flotas 3D y procesos de manufactura." },
  "Bico Entupido (Clog)": { en: "Clogged Nozzle", es: "Boquilla Obstruida (Clog)" },
  "Brasília - DF": { en: "Brasília - DF", es: "Brasilia - DF" },
  "Cálculo de Preço Real": { en: "Real Price Calculation", es: "Cálculo de Precio Real" },
  "Calibração de E-Steps": { en: "E-Steps Calibration", es: "Calibración de E-Steps" },
  "Calibração de Máquina": { en: "Machine Calibration", es: "Calibración de Máquina" },
  "Calibração de Precisão": { en: "Precision Calibration", es: "Calibración de Precisión" },
  "Canais de Suporte": { en: "Support Channels", es: "Canales de Soporte" },
  "Cancelar Plano": { en: "Cancel Plan", es: "Cancelar Plan" },
  "Carregando dados...": { en: "Loading data...", es: "Cargando datos..." },
  "Carregando seus chamados...": { en: "Loading your tickets...", es: "Cargando sus tickets..." },
  "Caso seja oferecido um período de testes premium gratuito, o encerramento do prazo não gerará cobrança automática. O acesso aos recursos Pro será suspenso até que o usuário decida assinar um plano pago de forma ativa.": { en: "If a free trial is offered, expiry will not trigger automatic billing. Pro access pauses until active subscription.", es: "Si se ofrece prueba gratuita, el vencimiento no generará cobro automático. El acceso Pro se suspende hasta suscripción activa." },
  "Central Maker": { en: "Maker Hub", es: "Central Maker" },
  "Céu": { en: "Sky", es: "Cielo" },
  "Chamado enviado diretamente para a equipe técnica!": { en: "Ticket sent directly to technical team!", es: "¡Ticket enviado directamente al equipo técnico!" },
  "Chave / Nome": { en: "Key / Name", es: "Clave / Nombre" },
  "Ciano": { en: "Cyan", es: "Cian" },
  "Clique nas tags para copiar": { en: "Click tags to copy", es: "Haga clic en las etiquetas para copiar" },
  "Cloudflare": { en: "Cloudflare", es: "Cloudflare" },
  "Cloudflare (hospedagem, banco de dados e segurança de rede), Google Firebase (autenticação) e Stripe (processamento de pagamentos).": { en: "Cloudflare (hosting, DB and network security), Google Firebase (auth) and Stripe (payment processing).", es: "Cloudflare (alojamiento y seguridad), Google Firebase (autenticación) y Stripe (pagos)." },
  "Clube dos 50: Makers Fundadores": { en: "Club 50: Founding Makers", es: "Club de los 50: Makers Fundadores" },
  "Código incorreto ou expirado. Verifique os 6 dígitos gerados pelo seu aplicativo.": { en: "Incorrect or expired code. Verify the 6 digits generated by your app.", es: "Código incorrecto o caducado. Verifique los 6 dígitos generados por su app." },
  "Códigos de Recuperação": { en: "Recovery Codes", es: "Códigos de Recuperación" },
  "Compartilhar credenciais de acesso para uso coletivo de uma conta individual.": { en: "Sharing access credentials for collective use of an individual account.", es: "Compartir credenciales de acceso para uso colectivo de una cuenta individual." },
  "Comunidade Maker": { en: "Maker Community", es: "Comunidad Maker" },
  "Concordo:": { en: "I agree:", es: "De acuerdo:" },
  "Configurações": { en: "Settings", es: "Configuración" },
  "Configurações do Estúdio": { en: "Studio Settings", es: "Ajustes del Estudio" },
  "Configurar Alertas": { en: "Configure Alerts", es: "Configurar Alertas" },
  "Configurar Mensagem": { en: "Configure Message", es: "Configurar Mensaje" },
  "Confirmar Exclusão": { en: "Confirm Deletion", es: "Confirmar Eliminación" },
  "Confirme o código do aplicativo": { en: "Confirm app code", es: "Confirme el código de la app" },
  "Console Master — Dono": { en: "Master Console — Owner", es: "Consola Master — Propietario" },
  "Contato de Privacidade:": { en: "Privacy Contact:", es: "Contacto de Privacidad:" },
  "Continuar com E-mail": { en: "Continue with Email", es: "Continuar con Correo" },
  "Continuar com GitHub": { en: "Continue with GitHub", es: "Continuar con GitHub" },
  "Continuar com Google": { en: "Continue with Google", es: "Continuar con Google" },
  "Controlador": { en: "Data Controller", es: "Responsable del Tratamiento" },
  "Controlador dos Dados:": { en: "Data Controller:", es: "Responsable de Datos:" },
  "Cookie (365 dias)": { en: "Cookie (365 days)", es: "Cookie (365 días)" },
  "Copiar Chave": { en: "Copy Key", es: "Copiar Clave" },
  "Criação de Projetos": { en: "Project Creation", es: "Creación de Proyectos" },
  "Criar Novo Estúdio": { en: "Create New Studio", es: "Crear Nuevo Estudio" },
  "Criar Primeiro Chamado": { en: "Create First Ticket", es: "Crear Primer Ticket" },
  "Criptografia de Ponta a Ponta": { en: "End-to-End Encryption", es: "Cifrado de Extremo a Extremo" },
  "Criptografia:": { en: "Encryption:", es: "Cifrado:" },
  "Cuidado com Peças Longas": { en: "Caution with Long Parts", es: "Cuidado con Piezas Largas" },
  "Cuidados de Longo Prazo": { en: "Long-Term Care", es: "Cuidados a Largo Plazo" },
  "Cumprimento de obrigação legal (Art. 7º, II):": { en: "Compliance with legal obligations:", es: "Cumplimiento de obligación legal:" },
  "Custo Padrão do KWh": { en: "Default KWh Cost", es: "Coste Predeterminado de KWh" },
  "Custos & Margens": { en: "Costs & Margins", es: "Costes y Márgenes" },
  "Dados criptografados e processados sob rigorosos padrões de segurança.": { en: "Data encrypted and processed under strict security standards.", es: "Datos encriptados y procesados bajo estrictos estándares de seguridad." },
  "Dados do Estúdio": { en: "Studio Details", es: "Datos del Estudio" },
  "Dados Pessoais": { en: "Personal Details", es: "Datos Personales" },
  "Dados sobre materiais, consumo, energia e configurações de maquinário inseridos por você.": { en: "Data on materials, consumption, power and machinery configurations entered by you.", es: "Datos sobre materiales, consumo, energía y configuración de máquinas introducidos por usted." },
  "decidindo sobre o tratamento. Nossos parceiros atuam como": { en: "deciding on processing. Our partners act as", es: "decidiendo sobre el tratamiento. Nuestros socios actúan como" },
  "Desativa desfoque e física gráfica em tempo real": { en: "Disables blur and real-time graphic physics", es: "Desactiva desenfoque y física gráfica en tiempo real" },
  "Desativar Agora": { en: "Disable Now", es: "Desactivar Ahora" },
  "Descreva com detalhes o que aconteceu, o que esperava ou sua sugestão. Se for um erro, informe os passos que executou...": { en: "Describe in detail what happened, what was expected or your suggestion. If an error, list the steps...", es: "Describa detalladamente lo sucedido, lo que esperaba o su sugerencia. Si fue un error, indique los pasos..." },
  "Desenvolvedor Local": { en: "Local Developer", es: "Desarrollador Local" },
  "Dicas de Fatiamento": { en: "Slicing Tips", es: "Consejos de Laminado" },
  "Diferenças entre as projeções matemáticas simuladas pela plataforma (ex: tempo estimado de impressão e peso de material) e a produção real verificada fisicamente no maquinário.": { en: "Differences between simulated projections and physical production on machinery.", es: "Diferencias entre proyecciones simuladas y la producción física real en la maquinaria." },
  "Digite o código de 6 dígitos do seu aplicativo autenticador (ou um dos seus códigos de recuperação):": { en: "Enter the 6-digit code from your authenticator app (or one of your recovery codes):", es: "Ingrese el código de 6 dígitos de su aplicación autenticadora (o uno de sus códigos de recuperación):" },
  "Direito à Portabilidade": { en: "Right to Portability", es: "Derecho a la Portabilidad" },
  "Direito ao Esquecimento": { en: "Right to be Forgotten", es: "Derecho al Olvido" },
  "Direito de Acesso e Retificação": { en: "Right of Access & Rectification", es: "Derecho de Acceso y Rectificación" },
  "Dispensar aviso": { en: "Dismiss notice", es: "Descartar aviso" },
  "Divergência de Medição:": { en: "Measurement Divergence:", es: "Divergencia de Medición:" },
  "Dono Ativo": { en: "Active Owner", es: "Propietario Activo" },
  "E-mail de Acesso": { en: "Access Email", es: "Correo de Acceso" },
  "E-mail de redefinição enviado com sucesso!": { en: "Password reset email sent successfully!", es: "¡Correo de restablecimiento enviado con éxito!" },
  "E-mail de Segurança Enviado": { en: "Security Email Sent", es: "Correo de Seguridad Enviado" },
  "E-mail de verificação enviado!": { en: "Verification email sent!", es: "¡Correo de verificación enviado!" },
  "E-mail de verificação enviado! Verifique sua caixa de entrada e spam.": { en: "Verification email sent! Check your inbox and spam folder.", es: "¡Correo de verificación enviado! Revise su bandeja de entrada y spam." },
  "E-mail Principal": { en: "Primary Email", es: "Correo Principal" },
  "Economia e Mercado": { en: "Economics & Market", es: "Economía y Mercado" },
  "Eficiência e Oficina": { en: "Efficiency & Workshop", es: "Eficiencia y Taller" },
  "eliminação irreversível": { en: "irreversible deletion", es: "eliminación irreversible" },
  "Em resumo:": { en: "In summary:", es: "En resumen:" },
  "EM TOTAL CONFORMIDADE COM A LEI GERAL DE PROTEÇÃO DE DADOS (LEI Nº 13.709/2018)": { en: "IN FULL COMPLIANCE WITH DATA PROTECTION REGULATIONS (LGPD / GDPR)", es: "EN PLENA CONFORMIDAD CON LA LEGISLACIÓN DE PROTECCIÓN DE DATOS (RGPD)" },
  "EM TOTAL CONFORMIDADE COM AS DIRETRIZES DE COOKIES DA LGPD (LEI Nº 13.709/2018)": { en: "IN FULL COMPLIANCE WITH COOKIE COMPLIANCE GUIDELINES", es: "EN PLENA CONFORMIDAD CON LAS DIRECTRICES DE COOKIES" },
  "Encarregado de Dados (DPO)": { en: "Data Protection Officer (DPO)", es: "Delegado de Protección de Datos (DPO)" },
  "Encerrar Todas as Sessões": { en: "Terminate All Sessions", es: "Cerrar Todas las Sesiones" },
  "Entrada autorizada com código de recuperação!": { en: "Entry authorized with recovery code!", es: "¡Entrada autorizada con código de recuperación!" },
  "Enviamos um link mágico seguro para": { en: "We sent a secure magic link to", es: "Enviamos un enlace mágico seguro a" },
  "Erro ao enviar e-mail de redefinicao.": { en: "Error sending reset email.", es: "Error al enviar correo de restablecimiento." },
  "Erro ao enviar e-mail de verificação.": { en: "Error sending verification email.", es: "Error al enviar correo de verificación." },
  "Erro durante o cálculo criptográfico do código.": { en: "Error during cryptographic code calculation.", es: "Error durante el cálculo criptográfico del código." },
  "Erros Humanos de Digitação/Cálculo:": { en: "Human Input/Calculation Errors:", es: "Errores Humanos de Entrada/Cálculo:" },
  "Esmeralda": { en: "Emerald", es: "Esmeralda" },
  "Esqueceu a senha?": { en: "Forgot password?", es: "¿Olvidó su contraseña?" },
  "Essa ação é definitiva": { en: "This action is permanent", es: "Esta acción es definitiva" },
  "Esta ação não pode ser desfeita.": { en: "This action cannot be undone.", es: "Esta acción no se puede deshacer." },
  "Estamos construindo algo revolucionário. Como parte da nossa estratégia, apenas os primeiros": { en: "We are building something revolutionary. As part of our strategy, only the first", es: "Estamos construyendo algo revolucionario. Como parte de nuestra estrategia, solo los primeros" },
  "Estúdio de Transmissão Global (Broadcast)": { en: "Global Broadcast Studio", es: "Estudio de Transmisión Global (Broadcast)" },
  "Ex: 5511999999999": { en: "e.g.: +12025550123", es: "Ej: +34600000000" },
  "Ex: Criando suas ideias": { en: "e.g.: Crafting your ideas", es: "Ej: Creando tus ideas" },
  "Ex: Dúvida sobre cálculo de kWh ou Erro ao concluir pedido...": { en: "e.g.: Question about kWh calculation or error completing order...", es: "Ej: Duda sobre cálculo de kWh o error al finalizar pedido..." },
  "Ex: MalleVi 3D": { en: "e.g.: MalleVi 3D", es: "Ej: MalleVi 3D" },
  "Ex: PrintLog Filial Sul": { en: "e.g.: PrintLog South Branch", es: "Ej: PrintLog Sucursal Sur" },
  "Exclua sua conta e todos os seus dados permanentemente (Art. 18, VI).": { en: "Permanently delete your account and all data (Art. 18, VI).", es: "Elimine su cuenta y todos sus datos de forma permanente (Art. 18, VI)." },
  "Excluir estúdio": { en: "Delete studio", es: "Eliminar estudio" },
  "Excluir Todos os Meus Dados Permanentemente": { en: "Permanently Delete All My Data", es: "Eliminar Todos Mis Datos Permanentemente" },
  "exclusivamente cookies estritamente necessários": { en: "strictly necessary cookies only", es: "exclusivamente cookies estrictamente necesarias" },
  "Exclusivo": { en: "Exclusive", es: "Exclusivo" },
  "Execução de contrato (Art. 7º, V):": { en: "Performance of contract:", es: "Ejecución de contrato:" },
  "Exerça seus direitos garantidos pela LGPD": { en: "Exercise your rights protected by privacy regulations (LGPD)", es: "Ejerza sus derechos garantizados por la normativa de privacidad (LGPD)" },
  "Exige um código de segurança de 6 dígitos gerado no seu celular ao fazer login, protegendo sua conta mesmo que sua senha seja comprometida.": { en: "Requires a 6-digit security code generated on your mobile device when logging in, protecting your account even if your password is compromised.", es: "Requiere un código de seguridad de 6 dígitos generado en su móvil al iniciar sesión, protegiendo su cuenta incluso si su contraseña se ve comprometida." },
  "Expandir menu": { en: "Expand menu", es: "Expandir menú" },
  "Exportar Meus Dados (JSON)": { en: "Export My Data (JSON)", es: "Exportar Mis Datos (JSON)" },
  "Exportar todos os dados do estúdio": { en: "Export all studio data", es: "Exportar todos los datos del estudio" },
  "Falar com Suporte": { en: "Contact Support", es: "Hablar con Soporte" },
  "Fale diretamente com os fundadores e engenheiros da plataforma.": { en: "Talk directly with the platform founders and engineers.", es: "Hable directamente con los fundadores e ingenieros de la plataforma." },
  "Falha ao enviar e-mail de verificação. Tente novamente mais tarde.": { en: "Failed to send verification email. Please try again later.", es: "Fallo al enviar correo de verificación. Intente nuevamente más tarde." },
  "Falha ao exportar dados.": { en: "Failed to export data.", es: "Fallo al exportar datos." },
  "Falha ao gerar chaves criptográficas. Tente novamente.": { en: "Failed to generate cryptographic keys. Try again.", es: "Fallo al generar claves criptográficas. Inténtelo de nuevo." },
  "Falha ao salvar configurações.": { en: "Failed to save settings.", es: "Fallo al guardar configuraciones." },
  "Falhas Físicas da Manufatura:": { en: "Physical Manufacturing Failures:", es: "Fallos Físicos de Fabricación:" },
  "Faturas e Pagamentos": { en: "Invoices & Payments", es: "Facturas y Pagos" },
  "Fechar aviso": { en: "Close notice", es: "Cerrar aviso" },
  "Finalidade Técnica": { en: "Technical Purpose", es: "Finalidad Técnica" },
  "Firmware Klipper": { en: "Klipper Firmware", es: "Firmware Klipper" },
  "Foto de Perfil": { en: "Profile Picture", es: "Foto de Perfil" },
  "Foto de perfil (opcional):": { en: "Profile photo (optional):", es: "Foto de perfil (opcional):" },
  "Foto que Vende": { en: "Photos that Sell", es: "Fotos que Venden" },
  "Fúcsia": { en: "Fuchsia", es: "Fucsia" },
  "Fumaça Tóxica (VOCs)": { en: "Toxic Fumes (VOCs)", es: "Humos Tóxicos (VOCs)" },
  "Funcional. Lembra as preferências e flags de participação em recursos beta do sistema.": { en: "Functional. Remembers preferences and beta flags.", es: "Funcional. Recuerda preferencias y participación en funciones beta." },
  "Funcional. Mantém a lista de estúdios locais criados pelo usuário.": { en: "Functional. Maintains the list of user studios.", es: "Funcional. Mantiene la lista de estudios del usuario." },
  "Funcional. Registra qual estúdio/ambiente de gerenciamento está ativo.": { en: "Functional. Tracks the active management studio.", es: "Funcional. Registra qué estudio de gestión está activo." },
  "Garantia de Sigilo:": { en: "Confidentiality Guarantee:", es: "Garantía de Confidencialidad:" },
  "garantirão o título vitalício de": { en: "will secure the lifetime title of", es: "garantizarán el título vitalicio de" },
  "Gerando Chaves Seguras...": { en: "Generating Secure Keys...", es: "Generando Claves Seguras..." },
  "Gerenciar Assinatura": { en: "Manage Subscription", es: "Gestionar Suscripción" },
  "Gestão de Dados": { en: "Data Management", es: "Gestión de Datos" },
  "Gestão de Umidade": { en: "Humidity Management", es: "Gestión de Humedad" },
  "Google Authenticator, Authy ou 1Password": { en: "Google Authenticator, Authy, or 1Password", es: "Google Authenticator, Authy o 1Password" },
  "Google Firebase": { en: "Google Firebase", es: "Google Firebase" },
  "Guarda Legal de Registros": { en: "Legal Records Retention", es: "Retención Legal de Registros" },
  "Hardware e Mecânica": { en: "Hardware & Mechanics", es: "Hardware y Mecánica" },
  "Hub de inteligência técnica e suporte estratégico": { en: "Technical intelligence hub and strategic support", es: "Centro de inteligencia técnica y soporte estratégico" },
  "Identidade Visual": { en: "Visual Identity", es: "Identidad Visual" },
  "Identidade Visual Exclusiva": { en: "Exclusive Visual Identity", es: "Identidad Visual Exclusiva" },
  "Importada apenas para personalização visual caso utilize login via Google.": { en: "Imported solely for visual avatar when signing in with Google.", es: "Importada solo para avatar si inicia sesión con Google." },
  "IndexedDB / Storage": { en: "IndexedDB / Storage", es: "IndexedDB / Almacenamiento" },
  "Índigo": { en: "Indigo", es: "Índigo" },
  "Informação Validada pela Engenharia": { en: "Engineering Validated Information", es: "Información Validada por Ingeniería" },
  "Iniciativa Limitada": { en: "Limited Initiative", es: "Iniciativa Limitada" },
  "Inicie um ticket de suporte prioritário para análise técnica individualizada.": { en: "Open a priority support ticket for individualized technical analysis.", es: "Inicie un ticket de soporte prioritario para análisis técnico personalizado." },
  "Input Shaper e Pressure Advance": { en: "Input Shaper & Pressure Advance", es: "Input Shaper y Pressure Advance" },
  "Insira o código de 6 dígitos gerado no seu aplicativo autenticador.": { en: "Enter the 6-digit code generated by your authenticator app.", es: "Introduzca el código de 6 dígitos generado en su aplicación de autenticación." },
  "Insira o nome do estúdio.": { en: "Enter studio name.", es: "Introduzca el nombre del estudio." },
  "Insira um e-mail válido.": { en: "Enter a valid email.", es: "Introduzca un correo válido." },
  "Inter": { en: "Inter", es: "Inter" },
  "Isolamento Garantido": { en: "Guaranteed Isolation", es: "Aislamiento Garantizado" },
  "Isolamento Multi-tenant:": { en: "Multi-tenant Isolation:", es: "Aislamiento Multi-inquilino:" },
  "Isolamento Multilocatário": { en: "Multi-Tenant Isolation", es: "Aislamiento Multi-inquilino" },
  "Lab Ativo": { en: "Active Lab", es: "Laboratorio Activo" },
  "Laranja": { en: "Orange", es: "Naranja" },
  "Layer Shift (Degraus)": { en: "Layer Shift (Steps)", es: "Desplazamiento de Capas (Layer Shift)" },
  "Layout. Salva o estado de abertura/colapso da barra lateral do menu.": { en: "Layout. Saves sidebar open/collapsed state.", es: "Diseño. Guarda el estado de la barra lateral." },
  "Legacy Badge": { en: "Legacy Badge", es: "Insignia Legacy" },
  "Legítimo interesse (Art. 7º, IX):": { en: "Legitimate interest:", es: "Interés legítimo:" },
  "Lei nº 13.709/2018 — Sua privacidade é um direito": { en: "Data Protection Law — Your privacy is a fundamental right", es: "Ley de Protección de Datos — Su privacidad es un derecho" },
  "Lembrar deste dispositivo": { en: "Remember this device", es: "Recordar este dispositivo" },
  "Licenciamento e Direitos": { en: "Licensing & Rights", es: "Licencias y Derechos" },
  "Limão": { en: "Lime", es: "Lima" },
  "Local Storage": { en: "Local Storage", es: "Almacenamiento Local" },
  "Login com 2FA validado com sucesso!": { en: "2FA Login verified successfully!", es: "¡Inicio de sesión 2FA validado con éxito!" },
  "Login com Link Mágico realizado com sucesso!": { en: "Magic Link login successful!", es: "¡Inicio de sesión con Enlace Mágico realizado con éxito!" },
  "Logotipo do Estúdio": { en: "Studio Logo", es: "Logotipo del Estudio" },
  "Logs de acesso em IP e UTC mantidos por 6 meses": { en: "Access logs with IP and UTC kept for 6 months", es: "Registros de acceso con IP y UTC mantenidos durante 6 meses" },
  "Longevidade da Máquina": { en: "Machine Longevity", es: "Longevidad de la Máquina" },
  "Lucros Cessantes e Prejuízos Comerciais:": { en: "Lost Profits & Commercial Damages:", es: "Lucro Cesante y Daños Comerciales:" },
  "MAIS INDICADORES EM BREVE": { en: "MORE INDICATORS COMING SOON", es: "MÁS INDICADORES PRÓXIMAMENTE" },
  "Maker Pro": { en: "Maker Pro", es: "Maker Pro" },
  "Manutenção Corretiva": { en: "Corrective Maintenance", es: "Mantenimiento Correctivo" },
  "Manutenção de 100-200 Horas": { en: "100-200 Hours Maintenance", es: "Mantenimiento de 100-200 Horas" },
  "Máquinas": { en: "Machines", es: "Máquinas" },
  "Marco Civil da Internet (Art. 15)": { en: "Internet Civil Rights Framework", es: "Marco Civil de Internet" },
  "Margem Padrão de Lucro": { en: "Default Profit Margin", es: "Margen Predeterminado de Beneficio" },
  "Máx: 2kg": { en: "Max: 2kg", es: "Máx: 2kg" },
  "Mensagens configuradas aqui aparecem instantaneamente como um banner flutuante no topo de todas as páginas para 100% dos usuários ativos na plataforma.": { en: "Messages configured here appear instantly as a floating banner at the top of all pages for 100% of active platform users.", es: "Los mensajes configurados aquí aparecen instantáneamente como un banner flotante en la parte superior de todas las páginas para el 100% de los usuarios activos." },
  "Meus Chamados": { en: "My Tickets", es: "Mis Tickets" },
  "Mín: 50g": { en: "Min: 50g", es: "Mín: 50g" },
  "Modelagem Maker": { en: "Maker Modeling", es: "Modelado Maker" },
  "Modelos Rápidos (1-Click Presets)": { en: "Quick Presets (1-Click)", es: "Plantillas Rápidas (1-Click)" },
  "Modo Desempenho": { en: "Performance Mode", es: "Modo Rendimiento" },
  "Moeda Padrão": { en: "Default Currency", es: "Moneda Predeterminada" },
  "Montserrat": { en: "Montserrat", es: "Montserrat" },
  "não": { en: "no", es: "no" },
  "não armazena": { en: "does not store", es: "no almacena" },
  "Não encontrou sua resposta?": { en: "Didn't find your answer?", es: "¿No encontró su respuesta?" },
  "Não foi possível copiar automaticamente.": { en: "Could not copy automatically.", es: "No se pudo copiar automáticamente." },
  "Nenhum chamado aberto": { en: "No open tickets", es: "Ningún ticket abierto" },
  "Nenhum resultado encontrado": { en: "No results found", es: "No se encontraron resultados" },
  "Nivelamento da Mesa": { en: "Bed Leveling", es: "Nivelación de la Cama" },
  "Nome Comercial": { en: "Business Name", es: "Nombre Comercial" },
  "Nome Completo": { en: "Full Name", es: "Nombre Completo" },
  "Nome e E-mail:": { en: "Name & Email:", es: "Nombre y Correo:" },
  "Nome no Perfil": { en: "Profile Name", es: "Nombre de Perfil" },
  "Normal (Fluxo regular)": { en: "Normal (Regular flow)", es: "Normal (Flujo habitual)" },
  "Novo Chamado": { en: "New Ticket", es: "Nuevo Ticket" },
  "O link é inválido ou já expirou. Tente gerar um novo.": { en: "The link is invalid or expired. Please generate a new one.", es: "El enlace no es válido o ha expirado. Intente generar uno nuevo." },
  "O PrintLog utiliza a autenticação segura do Google e GitHub para login ou cadastro simplificado em poucos cliques.": { en: "PrintLog uses secure Google and GitHub authentication for quick, one-click sign in.", es: "PrintLog utiliza la autenticación segura de Google y GitHub para iniciar sesión o registrarse en pocos clics." },
  "Ocorreu um erro ao tentar deslogar.": { en: "An error occurred while logging out.", es: "Ocurrió un error al intentar cerrar sesión." },
  "Operação concluída com sucesso!": { en: "Operation completed successfully!", es: "¡Operación completada con éxito!" },
  "Operadores": { en: "Operators", es: "Operadores" },
  "Operadores Técnicos (Parceiros):": { en: "Technical Operators (Partners):", es: "Operadores Técnicos (Socios):" },
  "Orçamentos:": { en: "Quotes:", es: "Presupuestos:" },
  "Os planos pagos renovam automaticamente no ciclo contratado (mensal/anual). O cancelamento pode ser efetuado de forma autônoma pelo painel do usuário a qualquer momento, interrompendo cobranças futuras.": { en: "Paid plans renew automatically. Cancellation can be completed anytime in the user dashboard.", es: "Los planes de pago se renuevan automáticamente. Puede cancelar en cualquier momento desde su panel." },
  "Outfit": { en: "Outfit", es: "Outfit" },
  "Painel do Estúdio": { en: "Studio Dashboard", es: "Panel del Estudio" },
  "Para criação de conta, autenticação e comunicações críticas do sistema.": { en: "For account creation, authentication and critical system notifications.", es: "Para creación de cuenta, autenticación y notificaciones críticas." },
  "Para prestação do serviço SaaS de gestão.": { en: "For the provision of the SaaS management service.", es: "Para la prestación del servicio de gestión SaaS." },
  "Para segurança, prevenção de fraudes e auditoria de logs.": { en: "For security, fraud prevention and log auditing.", es: "Para seguridad, prevención de fraudes y auditoría." },
  "Para sua segurança, confirme pela última vez se deseja encerrar sua conta.": { en: "For your security, please confirm one last time that you wish to close your account.", es: "Por su seguridad, confirme por última vez que desea cerrar su cuenta." },
  "Parâmetros e Custos:": { en: "Parameters & Costs:", es: "Parámetros y Costes:" },
  "Parâmetros Operacionais": { en: "Operational Parameters", es: "Parámetros Operativos" },
  "Parar Leitura": { en: "Stop Reading", es: "Detener Lectura" },
  "Participar de Protótipos (Programa Beta)": { en: "Join Prototypes (Beta Program)", es: "Participar en Prototipos (Programa Beta)" },
  "Peça Soltando (Warping)": { en: "Part Detaching (Warping)", es: "Pieza Despegándose (Warping)" },
  "Perfil Maker": { en: "Maker Profile", es: "Perfil Maker" },
  "Perguntas Frequentes (FAQ)": { en: "Frequently Asked Questions (FAQ)", es: "Preguntas Frecuentes (FAQ)" },
  "Personalize a marca do seu estúdio": { en: "Customize your studio branding", es: "Personalice la marca de su estudio" },
  "Personalize o estúdio, preferências visuais, idioma e integrações": { en: "Customize your studio, visual preferences, language, and integrations", es: "Personalice su estudio, preferencias visuales, idioma e integraciones" },
  "Personalize o nome, slogan e logo do seu estúdio. Disponível nos planos": { en: "Customize your studio's name, slogan, and logo. Available on plans", es: "Personalice el nombre, eslogan y logotipo de su estudio. Disponible en los planes" },
  "Pink": { en: "Pink", es: "Rosa Fuerte" },
  "PLA vs PETG vs ABS": { en: "PLA vs PETG vs ABS", es: "PLA vs PETG vs ABS" },
  "Plano Atual": { en: "Current Plan", es: "Plan Actual" },
  "Plano de Manutenção": { en: "Maintenance Plan", es: "Plan de Mantenimiento" },
  "Poppins": { en: "Poppins", es: "Poppins" },
  "Por favor, faça login para gerenciar seus dados.": { en: "Please log in to manage your personal data.", es: "Por favor, inicie sesión para gestionar sus datos personales." },
  "Prazo legal de resposta: até 15 dias úteis (Art. 19 LGPD)": { en: "Legal response timeframe: up to 15 business days (Art. 19 LGPD)", es: "Plazo legal de respuesta: hasta 15 días laborables (Art. 19 LGPD)" },
  "Preencha o assunto e a descrição da sua solicitação.": { en: "Fill in the subject and description of your request.", es: "Rellene el asunto y la descripción de su solicitud." },
  "Preferência. Armazena as configurações de vida útil dos equipamentos.": { en: "Preference. Stores equipment lifespan settings.", es: "Preferencia. Guarda ajustes de vida útil de equipos." },
  "Preferência. Armazena as escolhas e aceites do usuário referentes a cookies.": { en: "Preference. Stores cookie choices and consent.", es: "Preferencia. Guarda opciones y consentimiento de cookies." },
  "Preferência. Armazena o modo visual (tema, cores e fontes) escolhido pelo usuário.": { en: "Preference. Stores chosen visual theme, colors and fonts.", es: "Preferencia. Guarda tema visual, colores y fuentes elegidos." },
  "Preferência. Lembra o ID do último equipamento selecionado no simulador.": { en: "Preference. Remembers last selected machine ID in simulator.", es: "Preferencia. Recuerda el ID del último equipo seleccionado." },
  "Preparando sua Farm...": { en: "Preparing your Farm...", es: "Preparando su Farm..." },
  "Preview da Logo": { en: "Logo Preview", es: "Vista previa del Logo" },
  "PrintLog (Desenvolvedor Independente)": { en: "PrintLog (Independent Developer)", es: "PrintLog (Desarrollador Independiente)" },
  "Privacidade (LGPD)": { en: "Privacy (LGPD / GDPR)", es: "Privacidad (RGPD)" },
  "Privacidade por Design": { en: "Privacy by Design", es: "Privacidad por Diseño" },
  "Processando solicitação de exclusão...": { en: "Processing account deletion request...", es: "Procesando solicitud de eliminación..." },
  "Programa Beta": { en: "Beta Program", es: "Programa Beta" },
  "Programa Beta Exclusivo": { en: "Exclusive Beta Program", es: "Programa Beta Exclusivo" },
  "Projetos, informações de clientes finais e valores gerados no sistema.": { en: "Projects, client info and figures generated in the system.", es: "Proyectos, datos de clientes y cifras generadas en el sistema." },
  "Provedor": { en: "Provider", es: "Proveedor" },
  "Publicar no Topo do App": { en: "Publish at Top of App", es: "Publicar en la Parte Superior" },
  "QR Code TOTP": { en: "TOTP QR Code", es: "Código QR TOTP" },
  "Quase lá...": { en: "Almost there...", es: "Casi listo..." },
  "Química e Aplicação": { en: "Chemistry & Application", es: "Química y Aplicación" },
  "Recolher menu": { en: "Collapse menu", es: "Plegar menú" },
  "Recorrentes.": { en: "Recurring.", es: "Recurrentes." },
  "Recuperar Senha": { en: "Reset Password", es: "Recuperar Contraseña" },
  "Regra dos 45 Graus": { en: "45-Degree Rule", es: "Regla de los 45 Grados" },
  "Remover operador": { en: "Remove operator", es: "Eliminar operador" },
  "Repositório Vazio": { en: "Empty Repository", es: "Repositorio Vacío" },
  "Resolução de Problemas": { en: "Troubleshooting", es: "Resolución de Problemas" },
  "Resolução de Problemas (Troubleshooting)": { en: "Troubleshooting", es: "Resolución de Problemas (Troubleshooting)" },
  "Resumo geral e exportação de dados": { en: "General summary and data export", es: "Resumen general y exportación de datos" },
  "Retenção de logs de acesso (Marco Civil da Internet) e notas fiscais.": { en: "Retention of access logs and tax invoices.", es: "Retención de registros de acceso y facturas." },
  "REVISADO SEGUNDO O CÓDIGO CIVIL E A LEI DO SOFTWARE (LEI Nº 9.609/98)": { en: "REVIEWED UNDER CIVIL AND SOFTWARE REGULATIONS", es: "REVISADO SEGÚN LA NORMATIVA LEGAL Y DE SOFTWARE" },
  "Revisão de 50-100 Horas": { en: "50-100 Hours Service", es: "Revisión de 50-100 Horas" },
  "Risco de Instabilidade": { en: "Instability Risk", es: "Riesgo de Inestabilidad" },
  "Risco Elétrico e Incêndio": { en: "Electrical & Fire Hazard", es: "Riesgo Eléctrico e Incendio" },
  "Riscos da Oficina": { en: "Workshop Hazards", es: "Riesgos del Taller" },
  "Roadmap Priority": { en: "Roadmap Priority", es: "Prioridad en la Hoja de Ruta" },
  "Rosa": { en: "Rose", es: "Rosa" },
  "Rotina por Impressão": { en: "Per-Print Routine", es: "Rutina por Impresión" },
  "Rotinas automatizadas de redundância para evitar perda de dados.": { en: "Automated redundancy routines to prevent data loss.", es: "Rutinas automáticas de redundancia para prevenir pérdidas de datos." },
  "SaaS": { en: "SaaS", es: "SaaS" },
  "Sair da Conta": { en: "Log Out", es: "Cerrar Sesión" },
  "Salvar Alterações": { en: "Save Changes", es: "Guardar Cambios" },
  "Segredos dos Materiais": { en: "Material Secrets", es: "Secretos de los Materiales" },
  "Segundo fator confirmado com sucesso!": { en: "Second factor confirmed successfully!", es: "¡Segundo factor confirmado con éxito!" },
  "Segurança & Gestão de Acesso": { en: "Security & Access Management", es: "Seguridad y Gestión de Acceso" },
  "Segurança e Saúde": { en: "Safety & Health", es: "Seguridad y Salud" },
  "Segurança. Turnstile antibot para proteção contra acessos automatizados.": { en: "Security. Turnstile antibot protection against automated attacks.", es: "Seguridad. Protección Turnstile contra accesos automatizados." },
  "Segurança. Validação antibot na camada de firewall e rede.": { en: "Security. Antibot verification at firewall and network layer.", es: "Seguridad. Validación antibot en firewall y red." },
  "Selecione o Estúdio Ativo": { en: "Select Active Studio", es: "Seleccione el Estudio Activo" },
  "Selecione...": { en: "Select...", es: "Seleccione..." },
  "Sem resultados": { en: "No results", es: "Sin resultados" },
  "Sessões Ativas": { en: "Active Sessions", es: "Sesiones Activas" },
  "Seu e-mail já está verificado!": { en: "Your email is already verified!", es: "¡Su correo electrónico ya está verificado!" },
  "Seu Feedback é Ouro": { en: "Your Feedback is Gold", es: "Su Opinión es Oro" },
  "Seu melhor e-mail corporativo": { en: "Your best email address", es: "Su mejor correo electrónico" },
  "Seu nome maker": { en: "Your maker name", es: "Su nombre maker" },
  "Slogan": { en: "Slogan", es: "Eslogan" },
  "Solicitação Concluída": { en: "Request Completed", es: "Solicitud Completada" },
  "Solicitar Exclusão da Conta": { en: "Request Account Deletion", es: "Solicitar Eliminación de Cuenta" },
  "Status do Suporte": { en: "Support Status", es: "Estado del Soporte" },
  "Sua conta de acesso e segurança": { en: "Your account access and security", es: "Su cuenta de acceso y seguridad" },
  "Sua conta está protegida com Google Authenticator / Authy": { en: "Your account is protected with Google Authenticator / Authy", es: "Su cuenta está protegida con Google Authenticator / Authy" },
  "Sua conta ficará menos protegida": { en: "Your account will be less protected", es: "Su cuenta estará menos protegida" },
  "Sua conta foi excluída com sucesso.": { en: "Your account was deleted successfully.", es: "Su cuenta fue eliminada con éxito." },
  "Sua sessão expirou por segurança. Faça login novamente.": { en: "Your session expired for security. Please sign in again.", es: "Su sesión ha expirado por seguridad. Inicie sesión nuevamente." },
  "Suporte Interno PrintLog": { en: "PrintLog Internal Support", es: "Soporte Interno PrintLog" },
  "Suporte Técnico": { en: "Technical Support", es: "Soporte Técnico" },
  "Técnica": { en: "Technical", es: "Técnica" },
  "Telefone de Contato": { en: "Contact Phone", es: "Teléfono de Contacto" },
  "Tem certeza?": { en: "Are you sure?", es: "¿Está seguro?" },
  "Tema, cores e tipografia": { en: "Theme, colors, and typography", es: "Tema, colores y tipografía" },
  "Tente buscar por termos técnicos diferentes ou consulte as categorias abaixo.": { en: "Try searching for different technical terms or browse categories below.", es: "Intente buscar otros términos técnicos o consulte las categorías inferiores." },
  "Termos do Programa Beta": { en: "Beta Program Terms", es: "Términos del Programa Beta" },
  "Tipo / Duração": { en: "Type / Duration", es: "Tipo / Duración" },
  "Todas as outras sessões ativas foram desconectadas.": { en: "All other active sessions have been disconnected.", es: "Todas las demás sesiones activas han sido desconectadas." },
  "Todo o processamento financeiro ocorre via gateways de pagamento certificados (PCI-DSS), isentando o PrintLog de armazenar dados de cartões de crédito.": { en: "All financial transactions use PCI-DSS gateways; PrintLog never stores credit card details.", es: "Las transacciones usan pasarelas PCI-DSS; PrintLog nunca guarda datos de tarjetas de crédito." },
  "Tolerância de Encaixes": { en: "Fit & Clearance Tolerances", es: "Tolerancia de Encajes" },
  "Torre de Temperatura e PID": { en: "Temperature Tower & PID", es: "Torre de Temperatura y PID" },
  "TPU: Estratégia Flexível": { en: "TPU: Flexible Strategy", es: "TPU: Estrategia Flexible" },
  "Tráfego de dados protegido (HTTPS/TLS) e criptografia em repouso nos servidores (AES-256).": { en: "Data protected in transit (HTTPS/TLS) and at rest (AES-256).", es: "Datos protegidos en tránsito (HTTPS/TLS) y en reposo (AES-256)." },
  "TRANSMISSÃO DESATIVADA": { en: "BROADCAST DISABLED", es: "TRANSMISIÓN DESACTIVADA" },
  "Tuning e Velocidade": { en: "Tuning & Speed", es: "Ajuste y Velocidad" },
  "Turquesa": { en: "Turquoise", es: "Turquesa" },
  "Unidade de Medida": { en: "Unit of Measurement", es: "Unidad de Medida" },
  "Upload do Logo": { en: "Upload Logo", es: "Subir Logo" },
  "Urgente (Bloqueou minha produção)": { en: "Urgent (Blocked my production)", es: "Urgente (Bloqueó mi producción)" },
  "Urgente (Farm parada)": { en: "Urgent (Farm is down)", es: "Urgente (Granja detenida)" },
  "URL da Logo": { en: "Logo URL", es: "URL del Logo" },
  "Utilizar robôs,": { en: "Using automated bots,", es: "Utilizar bots automatizados," },
  "Vagas Restantes": { en: "Remaining Spots", es: "Plazas Restantes" },
  "Validado pela Engenharia": { en: "Engineering Validated", es: "Validado por Ingeniería" },
  "Vendas e Negócios": { en: "Sales & Business", es: "Ventas y Negocios" },
  "Ver Códigos de Backup": { en: "View Backup Codes", es: "Ver Códigos de Respaldo" },
  "Verificando Acesso...": { en: "Verifying Access...", es: "Verificando Acceso..." },
  "Verifique seu E-mail": { en: "Check your Email", es: "Revise su Correo" },
  "Verifique sua caixa de entrada e spam para redefinir sua credencial.": { en: "Check your inbox and spam to reset your password.", es: "Revise su bandeja y spam para restablecer su contraseña." },
  "Violeta": { en: "Violet", es: "Violeta" },
  "Vocalizando Tela": { en: "Screen Vocalization Active", es: "Lectura de Pantalla Activa" },
  "Você foi deslogado com sucesso.": { en: "You have been logged out successfully.", es: "Ha cerrado sesión con éxito." },
  "Voltar ao site": { en: "Back to website", es: "Volver al sitio" },
  "Padrão (100%)": { en: "Default (100%)", es: "Estándar (100%)" },
  "Grande (112%)": { en: "Large (112%)", es: "Grande (112%)" },
  "Extra (125%)": { en: "Extra (125%)", es: "Extra (125%)" },
  "Ativos Firebase": { en: "Firebase Active", es: "Activos Firebase" },
  "Fundador": { en: "Founder", es: "Fundador" },
  "Pro": { en: "Pro", es: "Pro" },
  "Free": { en: "Free", es: "Gratis" },
  "A Vencer (7d)": { en: "Expiring (7d)", es: "Por Vencer (7d)" },
  "Órfãos / Sem Firebase": { en: "Orphans / Without Firebase", es: "Huérfanos / Sin Firebase" },
  "Parque de Máquinas": { en: "Machine Fleet", es: "Parque de Máquinas" },
  "Estoque de Materiais": { en: "Materials Stock", es: "Stock de Materiales" },
  "Pedidos & Kanban": { en: "Orders & Kanban", es: "Pedidos y Kanban" },
  "Central Maker & FAQ": { en: "Maker Hub & FAQ", es: "Central Maker y FAQ" },
  "claro": { en: "light", es: "claro" },
  "escuro": { en: "dark", es: "oscuro" },
};
