import { DicionarioTraducao } from "./tipos";

export const dicionarioLanding: DicionarioTraducao = {
  "* Plano 100% OFF válido por tempo limitado.": { en: "* 100% OFF Plan valid for a limited time.", es: "* Plan 100% OFF válido por tiempo limitado." },
  "A conta de luz pode representar uma parcela significativa do custo. Ignorar isso é fatal.": { en: "Electricity can represent a significant share of the cost. Ignoring it is fatal.", es: "La factura eléctrica puede representar una parte significativa del coste. Ignorarlo es fatal." },
  "A parte jurídica, sem exageros.": { en: "The legal part, without fluff.", es: "La parte legal, sin exageraciones." },
  "A primeira plataforma de engenharia de custos desenvolvida exclusivamente para estúdios de impressão 3D e farms de manufatura aditiva.": { en: "The premier cost engineering platform developed exclusively for 3D printing studios and additive manufacturing farms.", es: "La primera plataforma de ingeniería de costes desarrollada exclusivamente para estudios de impresión 3D y granjas de fabricación aditiva." },
  "Acesso total gratuito para quem apoia o início do projeto": { en: "Full free access for early project supporters", es: "Acceso total gratuito para quienes apoyan el inicio del proyecto" },
  "Action Figure 30cm": { en: "30cm Action Figure", es: "Figura de Acción 30cm" },
  "Adesivo de Mesa": { en: "Bed Adhesive", es: "Adhesivo de Cama" },
  "Alternar menu": { en: "Toggle menu", es: "Alternar menú" },
  "Antes de ler os documentos oficiais": { en: "Before reading official documents", es: "Antes de leer los documentos oficiales" },
  "Aprovado": { en: "Approved", es: "Aprobado" },
  "Assinar Plano PRO": { en: "Subscribe to PRO Plan", es: "Suscribirse al Plan PRO" },
  "Atlas Mega 02": { en: "Atlas Mega 02", es: "Atlas Mega 02" },
  "Atlas Mega 02 precisa de lubrificação em 2h de uso.": { en: "Atlas Mega 02 requires lubrication in 2h of use.", es: "Atlas Mega 02 necesita lubricación en 2h de uso." },
  "Bambu X1C • Vaso PLA": { en: "Bambu X1C • PLA Vase", es: "Bambu X1C • Jarrón PLA" },
  "Branding de Estúdio": { en: "Studio Branding", es: "Branding del Estudio" },
  "Caixa de Envio G": { en: "Large Shipping Box", es: "Caja de Envío G" },
  "Case Gaming Custom": { en: "Custom Gaming Case", es: "Carcasa Gaming Personalizada" },
  "Começar Agora": { en: "Get Started Now", es: "Comenzar Ahora" },
  "COMEÇAR GRATUITAMENTE": { en: "GET STARTED FOR FREE", es: "COMENZAR GRATIS" },
  "Consumo Total": { en: "Total Consumption", es: "Consumo Total" },
  "Contato": { en: "Contact", es: "Contacto" },
  "Contrato de Licença": { en: "License Agreement", es: "Contrato de Licencia" },
  "Criar Conta": { en: "Create Account", es: "Crear Cuenta" },
  "Dê adeus ao chutômetro.": { en: "Say goodbye to guesswork.", es: "Diga adiós a las conjeturas." },
  "De quem é o risco?": { en: "Whose risk is it?", es: "¿De quién es el riesgo?" },
  "Demonstração do Sistema": { en: "System Demo", es: "Demostración del Sistema" },
  "Desperdício Oculto": { en: "Hidden Waste", es: "Desperdicio Oculto" },
  "DINHEIRO FORA": { en: "MONEY AWAY", es: "DINERO A LA BASURA" },
  "Documentação Completa": { en: "Complete Documentation", es: "Documentación Completa" },
  "Ender 3 S1 • Engrenagem": { en: "Ender 3 S1 • Gear", es: "Ender 3 S1 • Engranaje" },
  "Energia": { en: "Electricity", es: "Energía" },
  "ENERGIA": { en: "ELECTRICITY", es: "ENERGÍA" },
  "Energia Ignorada": { en: "Ignored Electricity", es: "Energía Ignorada" },
  "Entrar": { en: "Sign In", es: "Iniciar Sesión" },
  "Escolha o Plano Ideal para sua": { en: "Choose the Ideal Plan for your", es: "Elija el Plan Ideal para su" },
  "Esperar a máquina quebrar custa caro. Organize revisões e evite o downtime.": { en: "Waiting for the machine to break is costly. Schedule checkups and prevent downtime.", es: "Esperar a que la máquina se rompa cuesta caro. Organice revisiones y evite el downtime." },
  "Estoque Parado": { en: "Idle Inventory", es: "Stock Parado" },
  "Falhas de Impressão": { en: "Print Failures", es: "Fallos de Impresión" },
  "Farm": { en: "Farm", es: "Farm" },
  "Faturado Mês": { en: "Monthly Invoiced", es: "Facturado en el Mes" },
  "Feito por Makers, Para Makers — Junte-se à Missão": { en: "Made by Makers, For Makers — Join the Mission", es: "Hecho por Makers, Para Makers — Únase a la Misión" },
  "Fila de Orçamentos": { en: "Quote Queue", es: "Cola de Presupuestos" },
  "Fila em Tempo Real": { en: "Real-Time Queue", es: "Cola en Tiempo Real" },
  "Filamento velho absorve umidade e estraga suas peças. Controle seu giro.": { en: "Old filament absorbs moisture and ruins your prints. Control your turnover.", es: "El filamento viejo absorbe humedad y estropea sus piezas. Controle su rotación." },
  "Final": { en: "Final", es: "Final" },
  "Fios e Resinas": { en: "Filaments & Resins", es: "Filamentos y Resinas" },
  "Gestão Manual": { en: "Manual Management", es: "Gestión Manual" },
  "Gestão Técnica de Impressão 3D": { en: "Technical 3D Printing Management", es: "Gestión Técnica de Impresión 3D" },
  "Horas de Voo": { en: "Flight Hours", es: "Horas de Vuelo" },
  "Imprimindo": { en: "Printing", es: "Imprimiendo" },
  "Insumos Críticos": { en: "Critical Supplies", es: "Insumos Críticos" },
  "Ir para o Dashboard": { en: "Go to Dashboard", es: "Ir al Panel" },
  "Livre": { en: "Idle", es: "Libre" },
  "Lucro Garantido": { en: "Guaranteed Profit", es: "Beneficio Garantizado" },
  "Lucro Real": { en: "Real Profit", es: "Beneficio Real" },
  "LUCRO REAL": { en: "REAL PROFIT", es: "BENEFICIO REAL" },
  "MAIS QUE UM SOFTWARE,": { en: "MORE THAN A SOFTWARE,", es: "MÁS QUE UN SOFTWARE," },
  "Manutenção Preditiva": { en: "Predictive Maintenance", es: "Mantenimiento Predictivo" },
  "Manutenção Reativa": { en: "Reactive Maintenance", es: "Mantenimiento Reactivo" },
  "Monitor Live": { en: "Live Monitor", es: "Monitor en Vivo" },
  "Nossa Ética na Prática": { en: "Our Ethics in Practice", es: "Nuestra Ética en la Práctica" },
  "O Cérebro da sua": { en: "The Brain of your", es: "El Cerebro de su" },
  "O Ciclo de Vida do seu Dado": { en: "Your Data Lifecycle", es: "El Ciclo de Vida de sus Datos" },
  "O PrintLog é um projeto independente. Comece grátis e, se precisar de mais recursos, assine o plano PRO para ajudar a manter o servidor online.": { en: "PrintLog is an independent project. Start free, and if you need more features, subscribe to PRO to help keep the server online.", es: "PrintLog es un proyecto independiente. Comience gratis y, si necesita más funciones, suscríbase al plan PRO para ayudar a mantener el servidor en línea." },
  "O PrintLog nasceu da vontade de ver a comunidade 3D brasileira crescer com dignidade. Não estamos aqui pelo lucro, mas para manter este sistema vivo e ajudar você a eliminar o chutômetro. Junte-se a nós para manter este projeto online e evoluindo para todos.": { en: "PrintLog was born from the desire to see the 3D maker community grow with dignity. We are here to keep this platform alive and help you eliminate guesswork. Join us in keeping this project online and evolving for everyone.", es: "PrintLog nació del deseo de ver crecer a la comunidad maker 3D con dignidad. Estamos aquí para mantener este sistema activo y ayudarle a eliminar las conjeturas. Únase a nosotros para mantener este proyecto en línea y evolucionando para todos." },
  "Oferta de Lançamento": { en: "Launch Special Offer", es: "Oferta de Lanzamiento" },
  "Olá, Maker! 👋": { en: "Hello, Maker! 👋", es: "¡Hola, Maker! 👋" },
  "Operação de Impressão.": { en: "Printing Operation.", es: "Operación de Impresión." },
  "Otimização": { en: "Optimization", es: "Optimización" },
  "Padrão Formal ABNT": { en: "Formal Standard", es: "Estándar Formal" },
  "Painel Completo": { en: "Full Dashboard", es: "Panel Completo" },
  "Painel de Controle": { en: "Control Panel", es: "Panel de Control" },
  "Painel de Operações • Outubro 2026": { en: "Operations Dashboard • October 2026", es: "Panel de Operaciones • Octubre 2026" },
  "PARE DE JOGAR": { en: "STOP THROWING", es: "DEJE DE TIRAR" },
  "Pare de perder dinheiro": { en: "Stop losing money", es: "Deje de perder dinero" },
  "Peça Final": { en: "Finished Part", es: "Pieza Final" },
  "PEÇA FINAL": { en: "FINISHED PART", es: "PIEZA FINAL" },
  "Peças Industriais": { en: "Industrial Parts", es: "Piezas Industriales" },
  "Pendente": { en: "Pending", es: "Pendiente" },
  "Pequenos erros de cálculo destroem sua margem de lucro. O PrintLog elimina as variáveis invisíveis.": { en: "Small calculation errors destroy your profit margin. PrintLog eliminates invisible variables.", es: "Pequeños errores de cálculo destruyen su margen de beneficio. PrintLog elimina las variables invisibles." },
  "PLA Silk Dourado": { en: "Silk Gold PLA", es: "PLA Seda Dorado" },
  "Planilhas e cadernos perdem dados. Centralize sua produção e ganhe tempo.": { en: "Spreadsheets and notebooks lose data. Centralize your production and save time.", es: "Hojas de cálculo y cuadernos pierden datos. Centralice su producción y gane tiempo." },
  "Política de Cookies": { en: "Cookie Policy", es: "Política de Cookies" },
  "Política de Privacidade": { en: "Privacy Policy", es: "Política de Privacidad" },
  "Por que coletamos?": { en: "Why do we collect?", es: "¿Por qué recopilamos?" },
  "Precificação Errada": { en: "Wrong Pricing", es: "Fijación Errónea de Precios" },
  "PRINTLOG MOBILE": { en: "PRINTLOG MOBILE", es: "PRINTLOG MOBILE" },
  "Produção": { en: "Production", es: "Producción" },
  "Protótipo Drone V4": { en: "Drone Prototype V4", es: "Prototipo Dron V4" },
  "Quadro de Avisos": { en: "Notice Board", es: "Tablón de Anuncios" },
  "Quem manda no dado?": { en: "Who owns the data?", es: "¿Quién manda en los datos?" },
  "Rascunho": { en: "Draft", es: "Borrador" },
  "Registre as falhas e inclua na margem de risco automaticamente no preço.": { en: "Record failures and automatically include them in your pricing risk margin.", es: "Registre los fallos e inclúyalos en el margen de riesgo automáticamente en el precio." },
  "Respostas Diretas": { en: "Direct Answers", es: "Respuestas Directas" },
  "Role para descobrir": { en: "Scroll to discover", es: "Deslice para descubrir" },
  "ROLE PARA DESCOBRIR": { en: "SCROLL TO DISCOVER", es: "DESLICE PARA DESCUBRIR" },
  "Rolo no Fim": { en: "Spool Low", es: "Bobina al Final" },
  "Segurança e Privacidade": { en: "Security and Privacy", es: "Seguridad y Privacidad" },
  "Sem Espionagem": { en: "No Spying", es: "Sin Espionaje" },
  "Sem Spam ou Venda": { en: "No Spam or Selling", es: "Sin Spam ni Venta" },
  "sempre": { en: "forever", es: "siempre" },
  "Ser um Maker Fundador": { en: "Become a Founding Maker", es: "Ser un Maker Fundador" },
  "SEUS DADOS.": { en: "YOUR DATA.", es: "SUS DATOS." },
  "Sistema de gestão para makers 3D. Calcule com precisão seus custos de impressão e maximize seus lucros.": { en: "Management system for 3D makers. Accurately calculate your 3D printing costs and maximize profits.", es: "Sistema de gestión para makers 3D. Calcule con precisión sus costes de impresión y maximice sus beneficios." },
  "Sistemas Online": { en: "Systems Online", es: "Sistemas en Línea" },
  "Suficiente para esta impressão": { en: "Sufficient for this print", es: "Suficiente para esta impresión" },
  "Suficiente para esta impressão (112g)": { en: "Sufficient for this print (112g)", es: "Suficiente para esta impresión (112g)" },
  "Suportes e sobras de filamento são lucro indo para o lixo. Controle cada grama.": { en: "Supports and filament scraps are profits going to waste. Track every gram.", es: "Soportes y restos de filamento son beneficios yendo a la basura. Controle cada gramo." },
  "tempo limitado": { en: "limited time", es: "tiempo limitado" },
  "Termos de Serviço": { en: "Terms of Service", es: "Términos de Servicio" },
  "Todos os direitos reservados.": { en: "All rights reserved.", es: "Todos los derechos reservados." },
  "Transforme cálculos em propostas profissionais com a identidade do seu estúdio.": { en: "Turn calculations into professional proposals with your studio's brand identity.", es: "Transforme cálculos en presupuestos profesionales con la identidad de su estudio." },
  "TRANSFORME FILAMENTO EM LUCRO": { en: "TRANSFORM FILAMENT INTO PROFIT", es: "TRANSFORME FILAMENTO EN BENEFICIO" },
  "Transparência é Tudo.": { en: "Transparency is Everything.", es: "La Transparencia lo es Todo." },
  "UMA MISSÃO.": { en: "A MISSION.", es: "UNA MISIÓN." },
  "Vender barato demais e pagar para trabalhar? Nunca mais. Saiba seu custo real.": { en: "Selling too cheap and paying to work? Never again. Know your real cost.", es: "¿Vender demasiado barato y pagar por trabajar? Nunca más. Conozca su coste real." },
  "VER DEMONSTRAÇÃO": { en: "WATCH DEMO", es: "VER DEMOSTRACIÓN" },
  "Ver Detalhes": { en: "View Details", es: "Ver Detalles" },
  "VER DETALHES": { en: "VIEW DETAILS", es: "VER DETALLES" },
  "Ver Todos": { en: "View All", es: "Ver Todos" },
  "Viper Core 01": { en: "Viper Core 01", es: "Viper Core 01" },
  "Viper Core 03": { en: "Viper Core 03", es: "Viper Core 03" },
  "Sistema 100% Gratuito e Ilimitado para Todos os Makers": { en: "100% Free and Unlimited System for All Makers", es: "Sistema 100% Gratuito e Ilimitado para Todos los Makers" },
  "SISTEMA 100% GRATUITO E ILIMITADO PARA TODOS OS MAKERS": { en: "100% FREE AND UNLIMITED SYSTEM FOR ALL MAKERS", es: "SISTEMA 100% GRATUITO E ILIMITADO PARA TODOS LOS MAKERS" },
  "Começar Gratuitamente": { en: "Get Started for Free", es: "Comenzar Gratis" },
  "Abandone as planilhas. Gerencie custos, prazos e hardware em uma interface industrial de alta densidade.": { en: "Abandon spreadsheets. Manage costs, deadlines, and hardware in a high-density industrial interface.", es: "Abandone las hojas de cálculo. Gestione costes, plazos y hardware en una interfaz industrial de alta densidad." },
  "Produção Ativa": { en: "Active Production", es: "Producción Activa" },
  "Peças": { en: "Parts", es: "Piezas" },
  "Lucro Líquido": { en: "Net Profit", es: "Beneficio Neto" },
  "Taxa Sucesso": { en: "Success Rate", es: "Tasa de Éxito" },
  "Alertas Estoque": { en: "Stock Alerts", es: "Alertas de Stock" },
  "Patrimônio": { en: "Total Assets", es: "Patrimonio" },
  "Ticket Médio": { en: "Average Ticket", es: "Ticket Medio" },
  "Clientes": { en: "Clients", es: "Clientes" },
  "Potencial": { en: "Potential", es: "Potencial" },
  "ROI": { en: "ROI", es: "ROI" },
  "Transforme": { en: "Transform", es: "Transforme" },
  "Filamento": { en: "Filament", es: "Filamento" },
  "em Lucro.": { en: "into Profit.", es: "en Beneficio." },
  "chutômetro": { en: "guesswork", es: "conjeturas" },
  "Calcule custos reais de energia, resina, filamento e margem líquida com precisão e dignidade.": { en: "Calculate real costs of electricity, resin, filament, and net margin with precision and dignity.", es: "Calcule costes reales de energía, resina, filamento y margen neto con precisión y dignidad." },
  "Começar Grátis": { en: "Start for Free", es: "Comenzar Gratis" },
  "Precisão Custos": { en: "Cost Accuracy", es: "Precisión de Costes" },
  "Lucro Real Médio": { en: "Avg Real Profit", es: "Beneficio Real Medio" },
  "Zero": { en: "Zero", es: "Cero" },
  "Chutômetro": { en: "Guesswork", es: "Conjeturas" },
  "Compromisso Ético PrintLog": { en: "PrintLog Ethical Commitment", es: "Compromiso Ético PrintLog" },
  "Transparência em primeiro lugar — 100% gratuito e em constante evolução junto com a comunidade 3D brasileira.": { en: "Transparency first — 100% free and constantly evolving together with the 3D maker community.", es: "Transparencia ante todo — 100% gratuito y en constante evolución junto con la comunidad 3D." },
  "Benefícios": { en: "Benefits", es: "Beneficios" },
  "Demonstração": { en: "Demo", es: "Demostración" },
  "Privacidade e Respeito": { en: "Privacy and Respect", es: "Privacidad y Respeto" },
  "A VERDADE SOBRE": { en: "THE TRUTH ABOUT", es: "LA VERDAD SOBRE" },
  "Privacidade não deveria ser um labirinto jurídico. Abaixo, explico de forma direta o que você realmente precisa saber sobre como o PrintLog funciona.": { en: "Privacy shouldn't be a legal maze. Below, I explain directly what you truly need to know about how PrintLog works.", es: "La privacidad no debería ser un laberinto jurídico. A continuación, explico de forma directa lo que realmente necesita saber sobre cómo funciona PrintLog." },
  "Você. Os orçamentos, custos e projetos são seus. Eu apenas forneço a \"caixa\" (software) para você guardá-los e processá-los. Se você decidir sair, pode levar tudo ou apagar tudo.": { en: "You. The quotes, costs, and projects are yours. I only provide the box (software) for you to store and process them. If you decide to leave, you can take everything or delete everything.", es: "Usted. Los presupuestos, costes y proyectos son suyos. Yo solo proporciono la caja (software) para que los guarde y procese. Si decide irse, puede llevarse todo o borrarlo todo." },
  "O PrintLog é uma ferramenta de auxílio. Os cálculos são precisos, mas a decisão final do preço de venda e o risco do seu negócio são seus. Eu não garanto lucro, eu garanto a ferramenta.": { en: "PrintLog is an assistive tool. The calculations are accurate, but the final pricing decision and the risk of your business are yours. I do not guarantee profit, I guarantee the tool.", es: "PrintLog es una herramienta de ayuda. Los cálculos son precisos, pero la decisión final del precio de venta y el riesgo de su negocio son suyos. No garantizo beneficios, garantizo la herramienta." },
  "Pela lei (LGPD), nossa base legal é a \"Execução de Contrato\". Ou seja, só pegamos seu nome (ou apelido) e e-mail porque sem eles você não conseguiria logar e salvar seus orçamentos. Simples assim.": { en: "Under the law (LGPD), our legal basis is 'Contract Execution'. That is, we only collect your name (or nickname) and email because without them you couldn't log in and save your quotes. Simple as that.", es: "Por ley (LGPD), nuestra base legal es la 'Ejecución de Contrato'. Es decir, solo recopilamos su nombre (o apodo) y correo electrónico porque sin ellos no podría iniciar sesión y guardar sus presupuestos. Así de simple." },
  "Criptografia AES-256": { en: "AES-256 Encryption", es: "Cifrado AES-256" },
  "Seus orçamentos são protegidos por criptografia AES-256. Isso significa que eles são transformados em códigos ilegíveis no banco de dados e só o seu login consegue \"desmontar\" essa proteção.": { en: "Your quotes are protected by AES-256 encryption. This means they are turned into unreadable codes in the database and only your login can decrypt that protection.", es: "Sus presupuestos están protegidos mediante cifrado AES-256. Esto significa que se transforman en códigos ilegibles en la base de datos y solo su inicio de sesión puede descifrar esa protección." },
  "Login Google": { en: "Google Sign-In", es: "Inicio de Sesión con Google" },
  "Delego a segurança da sua senha para o Google. Assim, eu foco em fazer a melhor ferramenta de 3D e eles focam em proteger sua conta com o que há de melhor.": { en: "I delegate your password security to Google. That way, I focus on building the best 3D tool and they focus on protecting your account with the best security available.", es: "Delego la seguridad de su contraseña a Google. Así, yo me enfoco en crear la mejor herramienta 3D y ellos se enfocan en proteger su cuenta con lo mejor del mercado." },
  "Eu não fico olhando quanto você fatura ou quais são seus clientes. O sistema é automatizado para você, não para mim.": { en: "I do not look at your revenue or who your clients are. The system is automated for you, not for me.", es: "No me pongo a mirar cuánto factura ni quiénes son sus clientes. El sistema está automatizado para usted, no para mí." },
  "Seu e-mail é sagrado. Nunca vou vendê-lo para terceiros ou te encher de propagandas que você não pediu. E se você observar, o sistema nem tem anúncios; meu foco é 100% na ferramenta.": { en: "Your email is sacred. I will never sell it to third parties or spam you with unsolicited ads. The system has zero advertisements; my focus is 100% on the tool.", es: "Su correo electrónico es sagrado. Nunca lo venderé a terceros ni le enviaré publicidad no solicitada. El sistema no contiene anuncios; mi enfoque está al 100% en la herramienta." },
  "1. Cadastro": { en: "1. Registration", es: "1. Registro" },
  "Nome/Apelido e e-mail via Google.": { en: "Name/Nickname and email via Google.", es: "Nombre/Apodo y correo vía Google." },
  "2. Registro": { en: "2. Logging", es: "2. Registro Técnico" },
  "IP e Data criptografados com AES-GCM (Lei 12.965).": { en: "IP and Date encrypted with AES-GCM (Law 12,965).", es: "IP y Fecha cifrados con AES-GCM (Ley 12.965)." },
  "3. Uso": { en: "3. Usage", es: "3. Uso" },
  "Orçamentos salvos só para você.": { en: "Quotes saved exclusively for you.", es: "Presupuestos guardados solo para usted." },
  "4. Purga": { en: "4. Purge", es: "4. Purga" },
  "Limpeza automática após 180 dias.": { en: "Automatic cleanup after 180 days.", es: "Limpieza automática tras 180 días." },
  "O que acontece se eu apagar minha conta?": { en: "What happens if I delete my account?", es: "¿Qué sucede si elimino mi cuenta?" },
  "Eu não fico com uma 'cópia de segurança' secreta. Seus orçamentos e dados pessoais são deletados dos nossos servidores de forma definitiva em poucos segundos. Além disso, os logs técnicos de acesso são limpos automaticamente por um robô após o prazo legal de 180 dias.": { en: "I don't keep a secret 'backup copy'. Your quotes and personal data are permanently deleted from our servers within seconds. In addition, technical access logs are automatically cleaned up by a bot after the 180-day legal period.", es: "No conservo ninguna 'copia de seguridad' secreta. Sus presupuestos y datos personales se eliminan definitivamente de nuestros servidores en segundos. Además, los registros técnicos de acceso son purgados automáticamente por un robot tras el plazo legal de 180 días." },
  "Onde meus dados ficam fisicamente?": { en: "Where are my data physically stored?", es: "¿Dónde residen físicamente mis datos?" },
  "Eles moram nos servidores da Cloudflare e Google, geralmente nos EUA ou Europa. Eles são gigantes da tecnologia que possuem uma segurança física que eu nunca conseguiria ter sozinho.": { en: "They reside on Cloudflare and Google servers, usually in the US or Europe. They are tech giants with physical security levels I could never provide alone.", es: "Residen en los servidores de Cloudflare y Google, generalmente en EE. UU. o Europa. Son gigantes tecnológicos con una seguridad física que jamás podría alcanzar en solitario." },
  "Meus dados podem ser usados para IA?": { en: "Can my data be used to train AI?", es: "¿Pueden usarse mis datos para IA?" },
  "De forma alguma. O PrintLog não treina modelos de IA com seus custos ou projetos. Seus dados são processados apenas para te dar os resultados dos orçamentos.": { en: "Absolutely not. PrintLog does not train AI models with your costs or projects. Your data is processed solely to calculate your quote results.", es: "En absoluto. PrintLog no entrena modelos de IA con sus costes o proyectos. Sus datos se procesan únicamente para entregarle los resultados de los presupuestos." },
  "E se você desistir do projeto?": { en: "What if you give up on the project?", es: "¿Y si abandonas el proyecto?" },
  "Sinceramente, pretendo manter o PrintLog por anos. Mas se um dia eu parar, avisarei a todos com antecedência para que possam exportar seus dados com calma.": { en: "Honestly, I intend to maintain PrintLog for years. But if I ever stop, I will notify everyone well in advance so you can export your data calmly.", es: "Sinceramente, pretendo mantener PrintLog durante años. Pero si algún día decido parar, avisaré a todos con suficiente antelación para que puedan exportar sus datos con total calma." },
  "Se você leu até aqui, percebeu que não tem segredo. Eu cuido do código e da segurança para você cuidar das suas impressões. Se sobrar alguma dúvida, me chama.": { en: "If you've read this far, you noticed there are no secrets. I handle the code and security so you can focus on your 3D prints. If you have any questions, reach out.", es: "Si ha leído hasta aquí, habrá notado que no hay secretos. Yo me ocupo del código y la seguridad para que usted se enfoque en sus impresiones. Si le queda alguna duda, contácteme." },
  "Falar comigo": { en: "Contact me", es: "Hablar conmigo" },
  "PrintLog © 2026 // Em conformidade com a LGPD (Lei 13.709/2018).": { en: "PrintLog © 2026 // In compliance with LGPD (Law 13,709/2018).", es: "PrintLog © 2026 // En conformidad con la LGPD (Ley 13.709/2018)." },
  "Dados protegidos com criptografia e transparência por um desenvolvedor solo.": { en: "Data protected with encryption and transparency by a solo developer.", es: "Datos protegidos con cifrado y transparencia por un desarrollador solo." },
  "Declaração de Cookies Essenciais": { en: "Essential Cookies Declaration", es: "Declaración de Cookies Esenciales" },
  "1. O que são Cookies?": { en: "1. What are Cookies?", es: "1. ¿Qué son las Cookies?" },
  "2. Filosofia de Uso no PrintLog": { en: "2. Usage Philosophy at PrintLog", es: "2. Filosofía de Uso en PrintLog" },
  "3. Inventário de Cookies Utilizados": { en: "3. Inventory of Used Cookies", es: "3. Inventario de Cookies Utilizadas" },
  "4. Gerenciamento e Revogação": { en: "4. Management and Revocation", es: "4. Gestión y Revocación" },
  "Chave / Nome": { en: "Key / Name", es: "Clave / Nombre" },
  "Provedor": { en: "Provider", es: "Proveedor" },
  "Tipo / Duração": { en: "Type / Duration", es: "Tipo / Duración" },
  "Finalidade Técnica": { en: "Technical Purpose", es: "Finalidad Técnica" },
  "1. Introdução": { en: "1. Introduction", es: "1. Introducción" },
  "2. Sobre o PrintLog e Responsáveis": { en: "2. About PrintLog and Controllers", es: "2. Acerca de PrintLog y Responsables" },
  "3. Dados Coletados e Finalidades": { en: "3. Collected Data and Purposes", es: "3. Datos Recopilados y Finalidades" },
  "3.1. Dados de Identificação": { en: "3.1. Identification Data", es: "3.1. Datos de Identificación" },
  "3.2. Dados de Negócio (Impressão 3D)": { en: "3.2. Business Data (3D Printing)", es: "3.2. Datos de Negocio (Impresión 3D)" },
  "3.3. Dados Financeiros (Plano Maker Pro)": { en: "3.3. Financial Data (Maker Pro Plan)", es: "3.3. Datos Financieros (Plan Maker Pro)" },
  "4. Base Legal para o Tratamento": { en: "4. Legal Basis for Processing", es: "4. Base Legal para el Tratamiento" },
  "5. Seus Direitos (LGPD)": { en: "5. Your Rights (LGPD)", es: "5. Sus Derechos (LGPD)" },
  "6. Segurança e Isolamento de Dados": { en: "6. Security and Data Isolation", es: "6. Seguridad y Aislamiento de Datos" },
  "7. Cookies Essenciais": { en: "7. Essential Cookies", es: "7. Cookies Esenciales" },
  "8. Retenção e Exclusão": { en: "8. Retention and Deletion", es: "8. Retención y Eliminación" },
  "Contrato de Licença de Uso de Software (EULA)": { en: "End User License Agreement (EULA)", es: "Contrato de Licencia de Uso de Software (EULA)" },
  "1. Objeto do Contrato": { en: "1. Subject of Agreement", es: "1. Objeto del Contrato" },
  "2. Fornecimento \"AS IS\" (Como Está) e Disponibilidade": { en: "2. 'AS IS' Provision and Availability", es: "2. Suministro 'AS IS' (Tal Cual) y Disponibilidad" },
  "3. Propriedade Intelectual e Restrições": { en: "3. Intellectual Property and Restrictions", es: "3. Propiedad Intelectual y Restricciones" },
  "4. Isenção Total de Responsabilidade Comercial e Física": { en: "4. Total Disclaimer of Commercial and Physical Liability", es: "4. Exención Total de Responsabilidad Comercial y Física" },
  "5. Planos, Cobrança e Política de Não-Surpresa": { en: "5. Plans, Billing and No-Surprise Policy", es: "5. Planes, Facturación y Política de Cero Sorpresas" },
  "6. Rescisão e Limpeza de Dados": { en: "6. Termination and Data Cleanup", es: "6. Rescisión y Limpieza de Dados" },
  "7. Modificações, Contato Legal e Foro": { en: "7. Modifications, Legal Contact and Jurisdiction", es: "7. Modificaciones, Contacto Legal y Jurisdicción" },
  "Controlador dos Dados:": { en: "Data Controller:", es: "Responsable del Tratamiento:" },
  "Contato de Privacidade:": { en: "Privacy Contact:", es: "Contacto de Privacidad:" },
  "Operadores Técnicos (Parceiros):": { en: "Technical Processors (Partners):", es: "Encargados del Tratamiento (Socios):" },
};
