import { DicionarioTraducao } from "./tipos";

export const dicionarioProducao: DicionarioTraducao = {
  "💡 Como Funciona:": { en: "💡 How It Works:", es: "💡 Cómo Funciona:" },
  "💡 Dica:": { en: "💡 Tip:", es: "💡 Consejo:" },
  "A Fazer": { en: "To Do", es: "Por Hacer" },
  "A linha do tempo está vazia.": { en: "The timeline is empty.", es: "La línea de tiempo está vacía." },
  "A peça está na impressora": { en: "The part is on the printer", es: "La pieza está en la impresora" },
  "Abortar Alterações": { en: "Abort Changes", es: "Abortar Cambios" },
  "Ação Imediata Recomendada": { en: "Immediate Action Recommended", es: "Acción Inmediata Recomendada" },
  "Acompanhamento Online": { en: "Online Tracking", es: "Seguimiento en Línea" },
  "Acumulado": { en: "Cumulative", es: "Acumulado" },
  "Adicionar Filamento": { en: "Add Filament", es: "Añadir Filamento" },
  "Adicione itens como": { en: "Add items such as", es: "Añada elementos como" },
  "Adicione o seu primeiro material para gerenciar o seu estoque de matéria prima.": { en: "Add your first material to manage your raw material inventory.", es: "Añada su primer material para gestionar su stock de materia prima." },
  "Aguardando novos projetos": { en: "Waiting for new projects", es: "Esperando nuevos proyectos" },
  "Alertas Críticos": { en: "Critical Alerts", es: "Alertas Críticas" },
  "Alertas de Estoque": { en: "Stock Alerts", es: "Alertas de Stock" },
  "Almoxarifado de Apoio Logístico": { en: "Logistics Support Stockroom", es: "Almacén de Apoyo Logístico" },
  "Aposentar Impressora": { en: "Decommission Printer", es: "Retirar Impresora" },
  "Arquivado/Cancelado": { en: "Archived/Canceled", es: "Archivado/Cancelado" },
  "Arquivo de Projetos": { en: "Project Archive", es: "Archivo de Proyectos" },
  "Atrasados": { en: "Overdue", es: "Atrasados" },
  "Auto-Alocação (Fila)": { en: "Auto-Allocation (Queue)", es: "Auto-Asignación (Cola)" },
  "AUTO-ALOCAÇÃO (SISTEMA)": { en: "AUTO-ALLOCATION (SYSTEM)", es: "AUTO-ASIGNACIÓN (SISTEMA)" },
  "Avisos Preventivos": { en: "Preventative Notices", es: "Avisos Preventivos" },
  "Buscando status do seu projeto...": { en: "Fetching your project status...", es: "Consultando el estado de su proyecto..." },
  "BUSCAR NO HISTÓRICO...": { en: "SEARCH IN HISTORY...", es: "BUSCAR EN EL HISTORIAL..." },
  "Buscar ou digitar cliente...": { en: "Search or enter customer...", es: "Buscar o escribir cliente..." },
  "Cadastre os materiais que você costuma usar para contabilizá-los em seus orçamentos.": { en: "Register the supplies you frequently use to account for them in quotes.", es: "Registre los materiales que suele usar para contabilizarlos en sus presupuestos." },
  "Carregando projetos...": { en: "Loading projects...", es: "Cargando proyectos..." },
  "Carregando Quadro de Produção...": { en: "Loading Production Board...", es: "Cargando Tablero de Producción..." },
  "Cliente": { en: "Customer", es: "Cliente" },
  "Cliente avulso": { en: "One-off Customer", es: "Cliente Ocasional" },
  "Clique para vincular um filamento do seu armazém": { en: "Click to link a filament from your stock", es: "Haga clic para vincular un filamento de su almacén" },
  "Clique para vincular um insumo do seu armazém": { en: "Click to link a supply from your stock", es: "Haga clic para vincular un insumo de su almacén" },
  "Código de Envio": { en: "Tracking Code", es: "Código de Envío" },
  "Código de Rastreamento / Entrega": { en: "Tracking / Delivery Code", es: "Código de Seguimiento / Entrega" },
  "Com base no consumo médio dos últimos 30 dias e na fila ativa, alguns materiais atingirão nível crítico em breve.": { en: "Based on average consumption over the last 30 days and the active queue, some materials will reach critical levels soon.", es: "Según el consumo medio de los últimos 30 días y la cola activa, algunos materiales alcanzarán un nivel crítico pronto." },
  "Como calculamos a previsão?": { en: "How do we calculate the forecast?", es: "¿Cómo calculamos la previsión?" },
  "Composição de Materiais": { en: "Materials Composition", es: "Composición de Materiales" },
  "Composição Fina de Setup": { en: "Fine Setup Composition", es: "Composición Fina de Setup" },
  "Concluídos Hoje": { en: "Completed Today", es: "Completados Hoy" },
  "Conclusão de Impressão": { en: "Print Completion", es: "Finalización de Impresión" },
  "Confirmar & Fechar": { en: "Confirm & Close", es: "Confirmar y Cerrar" },
  "Confirmar Baixa": { en: "Confirm Disposal/Issue", es: "Confirmar Baja" },
  "Confirmar Reposição": { en: "Confirm Restock", es: "Confirmar Reposición" },
  "Consumido": { en: "Consumed", es: "Consumido" },
  "Copiar Link do Portal": { en: "Copy Portal Link", es: "Copiar Enlace del Portal" },
  "Cronograma de Manutenção": { en: "Maintenance Schedule", es: "Cronograma de Mantenimiento" },
  "Custo Total da Sucata:": { en: "Total Scrap Cost:", es: "Coste Total de Chatarra:" },
  "Dados de Engenharia Estimados": { en: "Estimated Engineering Specs", es: "Datos Técnicos Estimados" },
  "Dar Baixa": { en: "Write-off / Deduct", es: "Dar de Baja" },
  "Dar Baixa em Estoque": { en: "Deduct from Stock", es: "Dar de Baja en Stock" },
  "Data de Início": { en: "Start Date", es: "Fecha de Inicio" },
  "Data de Registro": { en: "Registration Date", es: "Fecha de Registro" },
  "Defina o equipamento e o deadline técnico": { en: "Define equipment and technical deadline", es: "Defina el equipo y el plazo técnico" },
  "Defina os materiais gastos nesta impressão": { en: "Specify the materials used in this print", es: "Defina los materiales utilizados en esta impresión" },
  "Desconhecido": { en: "Unknown", es: "Desconocido" },
  "Descreva detalhadamente o que foi realizado nesta intervenção...": { en: "Describe in detail what was performed in this intervention...", es: "Describa detalladamente lo que se realizó en esta intervención..." },
  "Descrição do Item": { en: "Item Description", es: "Descripción del Artículo" },
  "Descrição do Job": { en: "Job Description", es: "Descripción del Trabajo" },
  "Desgaste": { en: "Wear and Tear", es: "Desgaste" },
  "Desgaste Máquina": { en: "Machine Wear", es: "Desgaste de Máquina" },
  "Disponível": { en: "Available", es: "Disponible" },
  "Downtime Total": { en: "Total Downtime", es: "Tiempo de Inactividad Total" },
  "Enviado para Produção": { en: "Sent to Production", es: "Enviado a Producción" },
  "Equipamento Alocado": { en: "Allocated Equipment", es: "Equipo Asignado" },
  "Equipamento Ativo": { en: "Active Equipment", es: "Equipo Activo" },
  "Erro ao abater o estoque. Alteração revertida.": { en: "Error deducting stock. Change reverted.", es: "Error al descontar el stock. Cambio revertido." },
  "Erro ao arquivar impressora.": { en: "Error archiving printer.", es: "Error al archivar la impresora." },
  "Erro ao arquivar material. Alteração revertida.": { en: "Error archiving material. Change reverted.", es: "Error al archivar el material. Cambio revertido." },
  "Erro ao atualizar observações. Alteração revertida.": { en: "Error updating notes. Change reverted.", es: "Error al actualizar las notas. Cambio revertido." },
  "Erro ao carregar dados de manutenção.": { en: "Error loading maintenance data.", es: "Error al cargar los datos de mantenimiento." },
  "Erro ao carregar impressoras.": { en: "Error loading 3D printers.", es: "Error al cargar las impresoras 3D." },
  "Erro ao carregar pedidos.": { en: "Error loading orders.", es: "Error al cargar pedidos." },
  "Erro ao criar pedido. Alteração revertida.": { en: "Error creating order. Change reverted.", es: "Error al crear el pedido. Cambio revertido." },
  "Erro ao deletar. Alteração revertida.": { en: "Error deleting. Change reverted.", es: "Error al eliminar. Cambio revertido." },
  "Erro ao excluir pedido. Alteração revertida.": { en: "Error deleting order. Change reverted.", es: "Error al eliminar el pedido. Cambio revertido." },
  "Erro ao registrar manutenção. Alteração revertida.": { en: "Error logging maintenance. Change reverted.", es: "Error al registrar el mantenimiento. Cambio revertido." },
  "Erro ao registrar no financeiro.": { en: "Error recording in financials.", es: "Error al registrar en finanzas." },
  "Erro ao registrar reposição. Alteração revertida.": { en: "Error logging restocking. Change reverted.", es: "Error al registrar la reposición. Cambio revertido." },
  "Erro ao salvar acompanhamento.": { en: "Error saving tracking info.", es: "Error al guardar seguimiento." },
  "Erro ao salvar impressora. Alteração revertida.": { en: "Error saving printer. Change reverted.", es: "Error al guardar la impresora. Cambio revertido." },
  "Erro ao salvar material no banco de dados. Alteração revertida.": { en: "Error saving material to database. Change reverted.", es: "Error al guardar el material en la base de datos. Cambio revertido." },
  "Erro ao salvar o insumo. Alteração revertida.": { en: "Error saving supply item. Change reverted.", es: "Error al guardar el insumo. Cambio revertido." },
  "Erro ao salvar peças. Alteração revertida.": { en: "Error saving parts. Change reverted.", es: "Error al guardar las piezas. Cambio revertido." },
  "Erro ao salvar preferência.": { en: "Error saving preference.", es: "Error al guardar la preferencia." },
  "Erro inesperado.": { en: "Unexpected error.", es: "Error inesperado." },
  "Estoque de material renovado!": { en: "Material stock replenished!", es: "¡Stock de material renovado!" },
  "Estoque saudável e dimensionado para a produção atual.": { en: "Healthy stock tailored for current production.", es: "Stock saludable y dimensionado para la producción actual." },
  "Eventos de Produção": { en: "Production Events", es: "Eventos de Producción" },
  "Ex: 50": { en: "e.g.: 50", es: "Ej: 50" },
  "Ex: Álcool Isopropílico, Fita Blue Tape...": { en: "e.g.: Isopropyl Alcohol, Blue Painter's Tape...", es: "Ej: Alcohol Isopropílico, Cinta Azul..." },
  "Ex: BR876543210BR": { en: "e.g.: US123456789BR", es: "Ej: ES123456789BR" },
  "Ex: Fornecedor, NF...": { en: "e.g.: Supplier, Invoice...", es: "Ej: Proveedor, Factura..." },
  "Ex: PLA Vermelho Profissional": { en: "e.g.: Professional Red PLA", es: "Ej: PLA Rojo Profesional" },
  "Ex: Prime, 3M, Sinteglos...": { en: "e.g.: Primer, 3M, Sinteglos...", es: "Ej: Imprimación, 3M, Sinteglos..." },
  "Ex: Protótipo de Engenharia Rev.02": { en: "e.g.: Engineering Prototype Rev.02", es: "Ej: Prototipo de Ingeniería Rev.02" },
  "Ex: Reforçar paredes internas, acabamento com primer cinza...": { en: "e.g.: Reinforce internal walls, finish with gray primer...", es: "Ej: Reforzar paredes internas, acabado con imprimación gris..." },
  "Ex: Troca do filme FEP furado...": { en: "e.g.: Replacement of punctured FEP film...", es: "Ej: Sustitución de lámina FEP perforada..." },
  "Ex: UN, KG...": { en: "e.g.: PCS, KG...", es: "Ej: UD, KG..." },
  "Excluir Pedido Permanentemente": { en: "Permanently Delete Order", es: "Eliminar Pedido Permanentemente" },
  "Falha ao carregar projetos": { en: "Failed to load projects", es: "Fallo al cargar proyectos" },
  "Falha ao processar abatimento manual. Alteração revertida.": { en: "Failed to process manual deduction. Change reverted.", es: "Fallo al procesar la deducción manual. Cambio revertido." },
  "Falha ao registrar a entrada. Alteração revertida.": { en: "Failed to record receipt. Change reverted.", es: "Fallo al registrar la entrada. Cambio revertido." },
  "Falha registrada sem perda de material.": { en: "Failure recorded without material loss.", es: "Fallo registrado sin pérdida de material." },
  "Faturamento Bruto": { en: "Gross Revenue", es: "Facturación Bruta" },
  "Fila Ativa": { en: "Active Queue", es: "Cola Activa" },
  "Filamento (PLA, PETG), Resina, Tinta, Cola, Embalagens": { en: "Filament (PLA, PETG), Resin, Paint, Glue, Packaging", es: "Filamento (PLA, PETG), Resina, Pintura, Pegamento, Embalajes" },
  "Filamentos e Materiais": { en: "Filaments & Materials", es: "Filamentos y Materiales" },
  "Finalizar Projeto": { en: "Finish Project", es: "Finalizar Proyecto" },
  "Fluxo de produção limpo": { en: "Clean production flow", es: "Flujo de producción limpio" },
  "Fluxo de Produção Semanal": { en: "Weekly Production Flow", es: "Flujo de Producción Semanal" },
  "Fluxo Limpo": { en: "Clean Flow", es: "Flujo Limpio" },
  "Gestão Preditiva de Estoque & Compras IA": { en: "Predictive Inventory & AI Purchasing Management", es: "Gestión Predictiva de Stock y Compras IA" },
  "Gravando...": { en: "Saving...", es: "Guardando..." },
  "Hardware & Alocação": { en: "Hardware & Allocation", es: "Hardware y Asignación" },
  "Histórico de Atividade": { en: "Activity History", es: "Historial de Actividad" },
  "Histórico de Etapas": { en: "Stage History", es: "Historial de Etapas" },
  "Histórico de Produção": { en: "Production History", es: "Historial de Producción" },
  "Histórico exportado com sucesso!": { en: "History successfully exported!", es: "¡Historial exportado con éxito!" },
  "Histórico Global de Produção": { en: "Global Production History", es: "Historial Global de Producción" },
  "histórico operacional": { en: "operational history", es: "historial operativo" },
  "Histórico Recente": { en: "Recent History", es: "Historial Reciente" },
  "Horas de Impressão": { en: "Print Hours", es: "Horas de Impresión" },
  "horímetro total": { en: "total hour meter", es: "horómetro total" },
  "Houve desperdício de material?": { en: "Was there material waste?", es: "¿Hubo desperdicio de material?" },
  "Houve Perda / Falha": { en: "Loss / Failure Occurred", es: "Hubo Pérdida / Fallo" },
  "Identificação": { en: "Identification", es: "Identificación" },
  "Identificação de Hardware": { en: "Hardware Identification", es: "Identificación de Hardware" },
  "Identificação do Job": { en: "Job Identification", es: "Identificación del Trabajo" },
  "Impressora arquivada.": { en: "Printer archived.", es: "Impresora archivada." },
  "Inatividade": { en: "Downtime", es: "Inactividad" },
  "Informações Básicas": { en: "Basic Information", es: "Información Básica" },
  "Informações de rastreamento salvas com sucesso!": { en: "Tracking information saved successfully!", es: "¡Información de seguimiento guardada con éxito!" },
  "Informe a quantidade de material perdida nas tentativas falhas:": { en: "Enter the amount of material lost in failed attempts:", es: "Indique la cantidad de material perdido en los intentos fallidos:" },
  "Instruções especiais para a produção": { en: "Special production instructions", es: "Instrucciones especiales para producción" },
  "Insumo removido permanentemente do banco.": { en: "Supply item permanently removed.", es: "Insumo eliminado permanentemente." },
  "Insumo Utilizado": { en: "Supply Used", es: "Insumo Utilizado" },
  "Insumos Cadastrados": { en: "Registered Supplies", es: "Insumos Registrados" },
  "Insumos Diversos": { en: "Sundry Supplies", es: "Insumos Varios" },
  "Insumos Secundários": { en: "Secondary Supplies", es: "Insumos Secundarios" },
  "Intervenções Críticas": { en: "Critical Interventions", es: "Intervenciones Críticas" },
  "Inventário de Suprimentos": { en: "Supplies Inventory", es: "Inventario de Suministros" },
  "Investimento (BRL)": { en: "Investment (BRL)", es: "Inversión (BRL)" },
  "Investimento Comercial": { en: "Commercial Investment", es: "Inversión Comercial" },
  "Investimento em Insumos:": { en: "Supplies Investment:", es: "Inversión en Insumos:" },
  "Investimento Total": { en: "Total Investment", es: "Inversión Total" },
  "Linha do tempo completa de todos os pedidos já registrados": { en: "Complete timeline of all orders recorded", es: "Línea de tiempo completa de todos los pedidos registrados" },
  "Linha do Tempo de Uso": { en: "Usage Timeline", es: "Línea de Tiempo de Uso" },
  "Link de rastreamento copiado!": { en: "Tracking link copied!", es: "¡Enlace de seguimiento copiado!" },
  "Log de Operação / Notas": { en: "Operation Log / Notes", es: "Registro de Operación / Notas" },
  "Logística & Hardware": { en: "Logistics & Hardware", es: "Logística y Hardware" },
  "Manutenção Acumulada": { en: "Accumulated Maintenance", es: "Mantenimiento Acumulado" },
  "Manutenção Preventiva": { en: "Preventive Maintenance", es: "Mantenimiento Preventivo" },
  "Manutenção registrada com sucesso!": { en: "Maintenance successfully registered!", es: "¡Mantenimiento registrado con éxito!" },
  "Manutenção registrada!": { en: "Maintenance logged!", es: "¡Mantenimiento registrado!" },
  "Mão de Obra": { en: "Labor", es: "Mano de Obra" },
  "Máquina e deadlines": { en: "Machine and deadlines", es: "Máquina y plazos" },
  "Marcar como Concluído": { en: "Mark as Completed", es: "Marcar como Completado" },
  "Massa Total": { en: "Total Mass", es: "Masa Total" },
  "Materiais e insumos secundários": { en: "Materials and secondary supplies", es: "Materiales e insumos secundarios" },
  "Material arquivado com sucesso.": { en: "Material successfully archived.", es: "Material archivado con éxito." },
  "Material Base": { en: "Base Material", es: "Material Base" },
  "Material Perdido (g):": { en: "Lost Material (g):", es: "Material Perdido (g):" },
  "Média por Projeto": { en: "Average per Project", es: "Media por Proyecto" },
  "Métricas de Performance": { en: "Performance Metrics", es: "Métricas de Rendimiento" },
  "Monitoramento em tempo real fornecido pelo Printlog.": { en: "Real-time monitoring powered by PrintLog.", es: "Monitoreo en tiempo real proporcionado por PrintLog." },
  "Motivo da Saída": { en: "Reason for Outflow", es: "Motivo de la Salida" },
  "Na Fila": { en: "In Queue", es: "En Cola" },
  "Natureza da Intervenção": { en: "Nature of Intervention", es: "Naturaleza de la Intervención" },
  "Nenhum insumo encontrado": { en: "No supplies found", es: "No se encontraron insumos" },
  "Nenhum insumo extra aplicado": { en: "No extra supplies applied", es: "Ningún insumo extra aplicado" },
  "Nenhum material detalhado ainda": { en: "No materials detailed yet", es: "Ningún material detallado aún" },
  "Nenhum material encontrado": { en: "No materials found", es: "No se encontraron materiales" },
  "Nenhum projeto salvo": { en: "No saved projects", es: "Ningún proyecto guardado" },
  "Nenhum registro encontrado": { en: "No records found", es: "No se encontraron registros" },
  "Nenhum registro técnico": { en: "No technical records", es: "Ningún registro técnico" },
  "Nenhum resultado": { en: "No results", es: "Sin resultados" },
  "Nenhuma impressora ativa": { en: "No active printers", es: "Ninguna impresora activa" },
  "Nome / Descrição do Job": { en: "Job Name / Description", es: "Nombre / Descripción del Trabajo" },
  "Notas de acompanhamento do cliente": { en: "Customer tracking notes", es: "Notas de seguimiento del cliente" },
  "Notas do Maker / Estúdio": { en: "Maker / Studio Notes", es: "Notas del Maker / Estudio" },
  "Notas visíveis no portal público...": { en: "Notes visible on public portal...", es: "Notas visibles en el portal público..." },
  "Nova Manutenção": { en: "New Maintenance Record", es: "Nuevo Mantenimiento" },
  "Novo Material Maker": { en: "New Maker Material", es: "Nuevo Material Maker" },
  "Novo Preço Médio (Custo Real)": { en: "New Average Price (Real Cost)", es: "Nuevo Precio Medio (Coste Real)" },
  "O histórico de consumos e abatimentos aparecerá aqui.": { en: "Consumption and deduction history will appear here.", es: "El historial de consumos y deducciones aparecerá aquí." },
  "O que vamos cadastrar?": { en: "What are we adding?", es: "¿Qué vamos a registrar?" },
  "Observações atualizadas!": { en: "Notes updated!", es: "¡Notas actualizadas!" },
  "Observações do Operador": { en: "Operator Notes", es: "Observaciones del Operario" },
  "Observações para o Cliente": { en: "Notes for Customer", es: "Observaciones para el Cliente" },
  "Opcional: Por que?": { en: "Optional: Why?", es: "Opcional: ¿Por qué?" },
  "Orçamento Criado": { en: "Quote Created", es: "Presupuesto Creado" },
  "Orçamento Pendente": { en: "Pending Quote", es: "Presupuesto Pendiente" },
  "Paleta de Cores": { en: "Color Palette", es: "Paleta de Colores" },
  "Para calcular custos com precisão, precisamos saber qual máquina você usa.": { en: "To calculate costs accurately, we need to know which machine you run.", es: "Para calcular costes con precisión, necesitamos saber qué máquina utiliza." },
  "Parafusos, Embalagens, Tintas e Adicionais": { en: "Screws, Packaging, Paints, and Additions", es: "Tornillos, Embalajes, Pinturas y Adicionales" },
  "Parâmetros de Fatiamento e Setup": { en: "Slicing & Setup Parameters", es: "Parámetros de Laminado y Setup" },
  "Parceiro e Descrição Comercial": { en: "Partner & Commercial Description", es: "Socio y Descripción Comercial" },
  "Patrimônio em Estoque": { en: "Stock Asset Value", es: "Patrimonio en Stock" },
  "Peças/Serviço": { en: "Parts/Service", es: "Piezas/Servicio" },
  "Pedido atualizado!": { en: "Order updated!", es: "¡Pedido actualizado!" },
  "Pedido Concluído": { en: "Order Completed", es: "Pedido Completado" },
  "Pedido criado com sucesso! 🚀": { en: "Order created successfully! 🚀", es: "¡Pedido creado con éxito! 🚀" },
  "Pedido excluído.": { en: "Order deleted.", es: "Pedido eliminado." },
  "Pedido recebido e confirmado": { en: "Order received and confirmed", es: "Pedido recibido y confirmado" },
  "Performance Geral": { en: "General Performance", es: "Rendimiento General" },
  "Peso Atual": { en: "Current Weight", es: "Peso Actual" },
  "Peso Médio": { en: "Average Weight", es: "Peso Medio" },
  "Peso Total:": { en: "Total Weight:", es: "Peso Total:" },
  "Portal de Rastreio Público": { en: "Public Tracking Portal", es: "Portal de Seguimiento Público" },
  "Pós-Processamento e Acabamento": { en: "Post-Processing & Finishing", es: "Postprocesado y Acabado" },
  "Prazo de Entrega": { en: "Delivery Deadline", es: "Plazo de Entrega" },
  "Precificação & Estoque": { en: "Pricing & Stock", es: "Fijación de Precios y Stock" },
  "Preço e Quantidade": { en: "Price and Quantity", es: "Precio y Cantidad" },
  "Prejuízo Estimado:": { en: "Estimated Loss:", es: "Pérdida Estimada:" },
  "Previsão": { en: "Estimated Completion", es: "Previsión" },
  "Previsão de Uso": { en: "Usage Forecast", es: "Previsión de Uso" },
  "Produzindo": { en: "In Production", es: "En Producción" },
  "Projeção de Consumo de Materiais": { en: "Material Consumption Projection", es: "Proyección de Consumo de Materiales" },
  "Projeto": { en: "Project", es: "Proyecto" },
  "Projeto afetado:": { en: "Affected project:", es: "Proyecto afectado:" },
  "Projeto concluído! Estoque, financeiro e métricas atualizados. 🎉": { en: "Project completed! Inventory, financial, and metrics updated. 🎉", es: "¡Proyecto completado! Stock, finanzas y métricas actualizados. 🎉" },
  "Projeto enviado para o arquivo. 📦": { en: "Project sent to archive. 📦", es: "Proyecto enviado al archivo. 📦" },
  "Projeto restaurado do arquivo! ♻️": { en: "Project restored from archive! ♻️", es: "¡Proyecto restaurado del archivo! ♻️" },
  "Projetos Arquivados": { en: "Archived Projects", es: "Proyectos Archivados" },
  "Projetos em Atraso": { en: "Overdue Projects", es: "Proyectos Atrasados" },
  "Pronto para envio ou retirada": { en: "Ready for shipping or pickup", es: "Listo para envío o recogida" },
  "Próximos a vencer": { en: "Expiring soon", es: "Próximos a caducar" },
  "Qtd": { en: "Qty", es: "Cant" },
  "Qtd NF": { en: "Invoice Qty", es: "Cant. Factura" },
  "quantidade informada no estoque": { en: "quantity reported in stock", es: "cantidad informada en stock" },
  "Rastreabilidade total de tudo que já foi produzido no seu estúdio.": { en: "Full traceability of everything ever manufactured in your studio.", es: "Trazabilidad total de todo lo fabricado en su estudio." },
  "Rastreamento de peças atualizado!": { en: "Parts tracking updated!", es: "¡Seguimiento de piezas actualizado!" },
  "Rastreamento Indisponível": { en: "Tracking Unavailable", es: "Seguimiento No Disponible" },
  "Rastrear Objeto": { en: "Track Package", es: "Rastrear Paquete" },
  "Recálculo de Custos": { en: "Cost Recalculation", es: "Recálculo de Costes" },
  "Receita Gerada": { en: "Generated Revenue", es: "Ingresos Generados" },
  "Receita registrada no Financeiro!": { en: "Revenue recorded in Financials!", es: "¡Ingreso registrado en Finanzas!" },
  "Recomendação": { en: "Recommendation", es: "Recomendación" },
  "Recursos": { en: "Resources", es: "Recursos" },
  "referências passadas": { en: "past references", es: "referencias pasadas" },
  "Registrar consumo (balança)": { en: "Record consumption (scale)", es: "Registrar consumo (báscula)" },
  "Registrar Entrada de Item": { en: "Record Item Receipt", es: "Registrar Entrada de Artículo" },
  "Registrar Falha": { en: "Record Failure", es: "Registrar Fallo" },
  "Registrar Falha de Produção": { en: "Log Production Failure", es: "Registrar Fallo de Producción" },
  "Registrar Falha?": { en: "Record Failure?", es: "¿Registrar Fallo?" },
  "Registrar Intervenção": { en: "Log Intervention", es: "Registrar Intervención" },
  "Registrar Saída de Insumo": { en: "Record Supply Issue", es: "Registrar Salida de Insumo" },
  "Registrar sucata no painel": { en: "Log scrap on dashboard", es: "Registrar chatarra en el panel" },
  "Registrar Troca": { en: "Record Replacement", es: "Registrar Cambio" },
  "Remoção de suportes e pós-processamento": { en: "Support removal and post-processing", es: "Eliminación de soportes y postprocesado" },
  "Remover Insumo": { en: "Remove Supply Item", es: "Eliminar Insumo" },
  "Remover Insumo?": { en: "Remove Supply Item?", es: "¿Eliminar Insumo?" },
  "Remover Material": { en: "Remove Material", es: "Eliminar Material" },
  "Remover Material?": { en: "Remove Material?", es: "¿Eliminar Material?" },
  "Rendimento & Fracionamento": { en: "Yield & Fractioning", es: "Rendimiento y Fraccionamiento" },
  "Repor Estoque": { en: "Restock Inventory", es: "Reponer Stock" },
  "Repor Estoque Rápidamente": { en: "Quickly Restock", es: "Reponer Stock Rápidamente" },
  "Resetar Horímetro": { en: "Reset Hour Meter", es: "Restablecer Horómetro" },
  "Restam": { en: "Remaining", es: "Quedan" },
  "Saldo Atual": { en: "Current Balance", es: "Saldo Actual" },
  "Saldo que restará no rolo": { en: "Remaining spool balance", es: "Saldo que quedará en la bobina" },
  "Saúde do Ativo": { en: "Asset Health", es: "Salud del Activo" },
  "Saúde do Parque": { en: "Fleet Health", es: "Salud del Parque" },
  "Saúde Geral do Parque": { en: "Overall Farm Health", es: "Salud General de la Granja" },
  "Selecione uma operação acima para movimentar o inventário.": { en: "Select an operation above to manage inventory.", es: "Seleccione una operación arriba para mover el inventario." },
  "Sem Componentes Rastreados": { en: "No Tracked Components", es: "Sin Componentes Rastreados" },
  "Sem desperdício de material": { en: "No material waste", es: "Sin desperdicio de material" },
  "Sem insumos secundários": { en: "No secondary supplies", es: "Sin insumos secundarios" },
  "Sem Máquina Alocada": { en: "No Machine Allocated", es: "Sin Máquina Asignada" },
  "Serviços de Acabamento": { en: "Finishing Services", es: "Servicios de Acabado" },
  "Seu projeto foi postado! Acompanhe a entrega com o código de rastreamento abaixo:": { en: "Your project has been dispatched! Track delivery with the tracking code below:", es: "¡Su proyecto ha sido enviado! Siga la entrega con el código de seguimiento a continuación:" },
  "Sim, Remover Insumo": { en: "Yes, Remove Supply", es: "Sí, Eliminar Insumo" },
  "Sim, Remover Material": { en: "Yes, Remove Material", es: "Sí, Eliminar Material" },
  "Status do Pedido": { en: "Order Status", es: "Estado del Pedido" },
  "Substituição de Componentes": { en: "Component Replacement", es: "Sustitución de Componentes" },
  "Sucesso de Primeira": { en: "First-Time Success", es: "Éxito al Primer Intento" },
  "Tempo de Inatividade": { en: "Downtime", es: "Tiempo de Inactividad" },
  "Tempo de máquina e massa total": { en: "Machine time and total mass", es: "Tiempo de máquina y masa total" },
  "Tempo Médio": { en: "Average Time", es: "Tiempo Medio" },
  "Tente buscar com termos diferentes.": { en: "Try searching with different terms.", es: "Intente buscar con términos diferentes." },
  "Tipo de Material": { en: "Material Type", es: "Tipo de Material" },
  "Todas as ações são registradas automaticamente no histórico.": { en: "All actions are automatically logged in history.", es: "Todas las acciones se registran automáticamente en el historial." },
  "Todos os materiais possuem estoque suficiente para atender a fila de pedidos atual e a taxa de consumo projetada.": { en: "All materials have sufficient stock to meet the current order queue and projected consumption rate.", es: "Todos los materiales cuentan con stock suficiente para atender la cola de pedidos actual y la tasa de consumo proyectada." },
  "Total de Máquinas": { en: "Total Machines", es: "Total de Máquinas" },
  "Total Produzido": { en: "Total Produced", es: "Total Producido" },
  "Tudo operacional. Nenhuma manutenção pendente.": { en: "All operational. No pending maintenance.", es: "Todo operativo. Ningún mantenimiento pendiente." },
  "ultrapassam o estoque disponível": { en: "exceed available inventory", es: "superan el stock disponible" },
  "Unidade": { en: "Unit", es: "Unidad" },
  "Use a calculadora para gerar um orçamento. Quando terminar, clique em": { en: "Use the calculator to generate a quote. When done, click", es: "Use la calculadora para generar un presupuesto. Cuando termine, haga clic en" },
  "Valor de Mercado": { en: "Market Value", es: "Valor de Mercado" },
  "Valor Distribuído": { en: "Allocated Value", es: "Valor Distribuido" },
  "Valor Investido": { en: "Invested Value", es: "Valor Invertido" },
  "Valor Restante": { en: "Remaining Value", es: "Valor Restante" },
  "Valor Total": { en: "Total Value", es: "Valor Total" },
  "valor total pago": { en: "total value paid", es: "valor total pagado" },
  "Vida Útil dos Componentes": { en: "Component Lifespan", es: "Vida Útil de los Componentes" },
  "Vincule o cliente e os detalhes operacionais": { en: "Link the customer and operational details", es: "Vincule al cliente y los detalles operativos" },
  "Você não pode abater mais do que possui em estoque!": { en: "You cannot deduct more than what is in stock!", es: "¡No puede deducir más de lo que tiene en stock!" },
  "Você não tem pedidos ativos no momento, mas seu histórico está salvo no arquivo.": { en: "You have no active orders right now, but your history is stored in the archive.", es: "No tiene pedidos activos en este momento, pero su historial está guardado en el archivo." },
  "Volume de Insumos": { en: "Supplies Volume", es: "Volumen de Insumos" },
  "Fluxo Kanban": { en: "Kanban Flow", es: "Flujo Kanban" },
  "Linha do Tempo": { en: "Timeline", es: "Línea de Tiempo" },
  "Maior Horímetro Total": { en: "Highest Total Hours", es: "Mayor Horímetro Total" },
  "Menor Horímetro Total": { en: "Lowest Total Hours", es: "Menor Horímetro Total" },
  "Maior Valor de Compra": { en: "Highest Purchase Price", es: "Mayor Valor de Compra" },
  "Adicionadas Recentemente": { en: "Recently Added", es: "Añadidas Recientemente" },
  "Manutenção Urgente": { en: "Urgent Maintenance", es: "Mantenimiento Urgente" },
  "Menor Estoque": { en: "Lowest Stock", es: "Menor Stock" },
  "Maior Custo Unitário": { en: "Highest Unit Cost", es: "Mayor Coste Unitario" },
  "Maior Valor em Estoque": { en: "Highest Stock Value", es: "Mayor Valor en Stock" },
  "Menor Quantidade Restante": { en: "Lowest Remaining Quantity", es: "Menor Cantidad Restante" },
  "Histórico": { en: "History", es: "Historial" },
  "Especificações": { en: "Specifications", es: "Especificaciones" },
  "Manutenção": { en: "Maintenance", es: "Mantenimiento" },
  "Preventiva": { en: "Preventative", es: "Preventivo" },
  "Corretiva": { en: "Corrective", es: "Correctivo" },
  "Upgrade": { en: "Upgrade", es: "Mejora" },
  "Estoque e Custos": { en: "Stock and Costs", es: "Stock y Costes" },
  "Rendimento": { en: "Yield", es: "Rendimiento" },
  "Operações": { en: "Operations", es: "Operaciones" },
  "Abatimento": { en: "Deduction", es: "Deducción" },
  "Extrato": { en: "Statement", es: "Extracto" },
  "Cadastro": { en: "Registration", es: "Registro" },
  "Consumos e Custos": { en: "Consumption and Costs", es: "Consumos y Costes" },
  "Horas de Uso": { en: "Operating Hours", es: "Horas de Uso" },
  "Potência": { en: "Power Rating", es: "Potencia" },
  "Data Conclusão": { en: "Completion Date", es: "Fecha de Finalización" },
  "Peso (g)": { en: "Weight (g)", es: "Peso (g)" },
  "ESTOQUE:": { en: "STOCK:", es: "STOCK:" },
  "PESQUISAR...": { en: "SEARCH...", es: "BUSCAR..." },
  "Consumo / Uso Base": { en: "Base Usage / Consumption", es: "Consumo / Uso Base" },
  "Descarte Validade": { en: "Expired Waste Disposal", es: "Desecho por Caducidad" },
  "Quebra / Avaria": { en: "Breakage / Damage", es: "Rotura / Avería" },
  "LIMPEZA": { en: "CLEANING", es: "LIMPIEZA" },
  "EMBALAGEM": { en: "PACKAGING", es: "EMBALAJE" },
  "EMBRULHO": { en: "WRAPPING", es: "ENVOLTORIO" },
  "OUTROS": { en: "OTHERS", es: "OTROS" },
  "PROTEÇÃO": { en: "PROTECTION", es: "PROTECCIÓN" },
  "Limpeza": { en: "Cleaning", es: "Limpieza" },
  "Embalagem": { en: "Packaging", es: "Embalaje" },
  "Embrulho": { en: "Wrapping", es: "Envoltorio" },
  "Proteção": { en: "Protection", es: "Protección" },
  "Outros": { en: "Others", es: "Otros" },
  "Metro (m)": { en: "Meter (m)", es: "Metro (m)" },
  "Centímetro (cm)": { en: "Centimeter (cm)", es: "Centímetro (cm)" },
  "Mililitro (ml)": { en: "Milliliter (ml)", es: "Mililitro (ml)" },
  "Grama (g)": { en: "Gram (g)", es: "Gramo (g)" },
  "Folha": { en: "Sheet", es: "Hoja" },
  "Pedaço": { en: "Piece", es: "Trozo" },
  "Dose": { en: "Dose", es: "Dosis" },
  "Spray / Borrifada": { en: "Spray / Squirt", es: "Spray / Pulverización" },
  "Gota": { en: "Drop", es: "Gota" },
  "Pronto": { en: "Ready", es: "Listo" },
  "PLA (Ácido Polilático)": { en: "PLA (Polylactic Acid)", es: "PLA (Ácido Poliláctico)" },
  "PLA+ / Tough PLA (Alta Resistência)": { en: "PLA+ / Tough PLA (High Strength)", es: "PLA+ / Tough PLA (Alta Resistencia)" },
  "PLA Silk (Acabamento Seda/Brilhante)": { en: "Silk PLA (Silky/Gloss Finish)", es: "PLA Seda (Acabado Brillante/Seda)" },
  "PLA Matte (Fosco)": { en: "Matte PLA", es: "PLA Mate" },
  "PLA Wood (Composto com Madeira)": { en: "Wood PLA (Wood Composite)", es: "PLA Madera (Compuesto con Madera)" },
  "PLA Marble (Efeito Mármore/Pedra)": { en: "Marble PLA (Stone Effect)", es: "PLA Mármol (Efecto Piedra)" },
  "PLA Luminoso (Brilha no Escuro)": { en: "Glow in the Dark PLA", es: "PLA Luminiscente (Brilla en la Oscuridad)" },
  "PLA Metálico (Composto Metálico)": { en: "Metal PLA (Metallic Composite)", es: "PLA Metálico (Compuesto Metálico)" },
  "PLA Co-extrudado (2 ou 3 Cores)": { en: "Co-extruded Dual/Tri Color PLA", es: "PLA Coextruido (2 o 3 Colores)" },
  "PVB (Alisamento com Álcool Isopropílico)": { en: "PVB (IPA Alcohol Smoothing)", es: "PVB (Alisado con Alcohol Isopropílico)" },
  "PETG (Polietileno Tereftalato Glicol)": { en: "PETG (Polyethylene Glycol)", es: "PETG (Polietileno Tereftalato Glicol)" },
  "PCTG (Maior tenacidade que PETG)": { en: "PCTG (Tougher than PETG)", es: "PCTG (Mayor tenacidad que PETG)" },
  "ABS (Acrilonitrila Butadieno Estireno)": { en: "ABS (Acrylonitrile Butadiene Styrene)", es: "ABS (Acrilonitrilo Butadieno Estireno)" },
  "ASA (Resistente UV/Intempéries)": { en: "ASA (UV & Weather Resistant)", es: "ASA (Resistente UV e Intemperie)" },
  "TPU (Poliuretano Flexível)": { en: "TPU (Flexible Polyurethane)", es: "TPU (Poliuretano Flexible)" },
  "TPE (Elastômero Termoplástico)": { en: "TPE (Thermoplastic Elastomer)", es: "TPE (Elastómero Termoplástico)" },
  "TPC (Copoliéster Termoplástico)": { en: "TPC (Thermoplastic Copolyester)", es: "TPC (Copoliéster Termoplástico)" },
  "Nylon (Poliamida - PA)": { en: "Nylon (Polyamide - PA)", es: "Nailon (Poliamida - PA)" },
  "PC (Policarbonato)": { en: "PC (Polycarbonate)", es: "PC (Policarbonato)" },
  "PP (Polipropileno)": { en: "PP (Polypropylene)", es: "PP (Polipropileno)" },
  "POM (Delrin/Poliacetal - Baixo Atrito)": { en: "POM (Delrin/Polyacetal - Low Friction)", es: "POM (Delrin/Poliacetal - Baja Fricción)" },
  "PMMA (Acrílico)": { en: "PMMA (Acrylic)", es: "PMMA (Acrílico)" },
  "Fibra de Carbono (PA-CF, PETG-CF, PLA-CF)": { en: "Carbon Fiber (PA-CF, PETG-CF, PLA-CF)", es: "Fibra de Carbono (PA-CF, PETG-CF, PLA-CF)" },
  "Fibra de Vidro (PA-GF, ABS-GF)": { en: "Glass Fiber (PA-GF, ABS-GF)", es: "Fibra de Vidrio (PA-GF, ABS-GF)" },
  "HIPS (Suporte Solúvel em Limoneno)": { en: "HIPS (Limonene Soluble Support)", es: "HIPS (Soporte Soluble en Limoneno)" },
  "PVA (Suporte Solúvel em Água)": { en: "PVA (Water Soluble Support)", es: "PVA (Soporte Soluble en Agua)" },
  "BVOH (Suporte Solúvel em Água Rápido)": { en: "BVOH (Fast Water Soluble Support)", es: "BVOH (Soporte Soluble en Agua Rápido)" },
  "PEEK (Ultra Performance)": { en: "PEEK (Ultra Performance)", es: "PEEK (Ultra Rendimiento)" },
  "PEI / Ultem (Alta Resistência Térmica)": { en: "PEI / Ultem (High Heat Resistance)", es: "PEI / Ultem (Alta Resistencia Térmica)" },
  "PEKK (Ultra Performance)": { en: "PEKK (Ultra Performance)", es: "PEKK (Ultra Rendimiento)" },
  "Básica / Standard": { en: "Basic / Standard Resin", es: "Resina Básica / Estándar" },
  "Lavável (Water Washable)": { en: "Water Washable Resin", es: "Lavable al Agua (Water Washable)" },
  "Baixo Odor / Plant-Based (Eco)": { en: "Low Odor / Plant-Based Eco Resin", es: "Bajo Olor / Ecológica (Plant-Based)" },
  "Grandes Formatos / Fast Printing": { en: "Fast Printing / Large Formats Resin", es: "Grandes Formatos / Fast Printing" },
  "ABS-Like / Alto Impacto": { en: "ABS-Like / High Impact Resin", es: "Tipo ABS / Alto Impacto" },
  "Alta Resistência / Resistência (Tough)": { en: "Tough / High Strength Resin", es: "Alta Resistencia (Tough)" },
  "Flex / Flexível / Emborrachada": { en: "Flexible / Rubber-like Resin", es: "Flexible / Engomada" },
  "Alta Temperatura (High Temp)": { en: "High Temperature Resin", es: "Alta Temperatura (High Temp)" },
  "Cerâmica (Ceramic)": { en: "Ceramic Resin", es: "Cerámica (Ceramic)" },
  "Alta Resolução (8K/12K/14K)": { en: "High Resolution Resin (8K/12K/14K)", es: "Alta Resolución (8K/12K/14K)" },
  "Translúcida Rígida": { en: "Rigid Translucent Resin", es: "Translúcida Rígida" },
  "Translúcida Cores Vibrantes": { en: "Vibrant Translucent Resin", es: "Translúcida Colores Vivos" },
  "Transparente (Clear / Glass-Like)": { en: "Clear / Glass-Like Resin", es: "Transparente (Clear / Efecto Vidrio)" },
  "Dental (Modelos Ortodônticos/Troquel)": { en: "Dental (Orthodontic Models/Die)", es: "Dental (Modelos Ortodónticos/Troquel)" },
  "Dental Alinhadores": { en: "Dental Aligners Resin", es: "Dental Alineadores" },
  "Dental Guia Cirúrgico (Biocompatível)": { en: "Dental Surgical Guide (Biocompatible)", es: "Guía Quirúrgica Dental (Biocompatible)" },
  "Dental Gengiva Artificial (Gingiva)": { en: "Dental Artificial Gingiva Mask", es: "Encía Artificial Dental (Gingiva)" },
  "Dental Coroas e Pontes Provisórias": { en: "Dental Temporary Crowns & Bridges", es: "Coronas y Puentes Provisionales" },
  "Castable (Calcinável Padrão)": { en: "Castable Jewelry Resin", es: "Calcinable (Castable Joyería)" },
  "Alta Cera (High Wax Castable para Joias finas)": { en: "High Wax Castable Resin", es: "Alta Cera (Calcinable Joyas Finas)" },
  "Genérico Nacional": { en: "Domestic Generic", es: "Genérico Nacional" },
  "Genérico Importado": { en: "Imported Generic", es: "Genérico Importado" },
};
