import { DicionarioTraducao } from "./tipos";

export const dicionarioComercial: DicionarioTraducao = {
  "(-) Custo de Insumos": { en: "(-) Supplies Cost", es: "(-) Coste de Insumos" },
  "(-) Custo de Materiais": { en: "(-) Materials Cost", es: "(-) Coste de Materiales" },
  "(-) Depreciação": { en: "(-) Depreciation", es: "(-) Depreciación" },
  "(-) Despesas Fixas (Gerais)": { en: "(-) Fixed Overhead Expenses", es: "(-) Gastos Fijos (Generales)" },
  "(=) Lucro Líquido": { en: "(=) Net Profit", es: "(=) Beneficio Neto" },
  "(=) Margem de Contribuição": { en: "(=) Contribution Margin", es: "(=) Margen de Contribución" },
  "Adicione seu primeiro cliente para vincular orçamentos e pedidos.": { en: "Add your first customer to link quotes and production orders.", es: "Añada su primer cliente para vincular presupuestos y pedidos." },
  "Anexar Comprovante": { en: "Attach Receipt", es: "Adjuntar Comprobante" },
  "Aumento de Preço (Repasse)": { en: "Price Increase (Pass-through)", es: "Aumento de Precio (Traslado)" },
  "B2B (Empresa)": { en: "B2B (Business)", es: "B2B (Empresa)" },
  "B2C (Consumidor)": { en: "B2C (Consumer)", es: "B2C (Consumidor)" },
  "BUSCAR NOS PEDIDOS DO CLIENTE...": { en: "SEARCH IN CUSTOMER ORDERS...", es: "BUSCAR EN LOS PEDIDOS DEL CLIENTE..." },
  "Bandeira Tarifária (Energia)": { en: "Tariff Flag (Power)", es: "Tarifa Eléctrica (Energía)" },
  "Base de Clientes": { en: "Customer Base", es: "Base de Clientes" },
  "Boleto Bancário": { en: "Bank Slip / Boleto", es: "Boleto Bancario" },
  "BrasilAPI Oficial": { en: "Official BrasilAPI", es: "BrasilAPI Oficial" },
  "Buscar por nome, e-mail ou telefone...": { en: "Search by name, email, or phone...", es: "Buscar por nombre, correo o teléfono..." },
  "Capital Disponível": { en: "Available Capital", es: "Capital Disponible" },
  "Cartão de Crédito": { en: "Credit Card", es: "Tarjeta de Crédito" },
  "Cartão de Débito": { en: "Debit Card", es: "Tarjeta de Débito" },
  "Classificação de Fidelidade": { en: "Loyalty Classification", es: "Clasificación de Fidelidad" },
  "Cliente Frequente / VIP": { en: "Frequent / VIP Customer", es: "Cliente Frecuente / VIP" },
  "Cliente atualizado!": { en: "Customer updated!", es: "¡Cliente actualizado!" },
  "Cliente cadastrado com sucesso!": { en: "Customer registered successfully!", es: "¡Cliente registrado con éxito!" },
  "Cliente excluído.": { en: "Customer deleted.", es: "Cliente eliminado." },
  "Cliente removido.": { en: "Client removed.", es: "Cliente eliminado." },
  "Comece registrando suas contas para visualizar sua rentabilidade e margem de lucro real.": { en: "Start registering your accounts to view your real profitability and profit margin.", es: "Comience registrando sus cuentas para ver su rentabilidad y margen de beneficio real." },
  "Comprovante": { en: "Receipt / Voucher", es: "Comprobante" },
  "Conciliação Bancária": { en: "Bank Reconciliation", es: "Conciliación Bancaria" },
  "Conformidade LGPD Ativa": { en: "Active LGPD Compliance", es: "Conformidad LGPD Activa" },
  "Consumidor Final (B2C)": { en: "End Consumer (B2C)", es: "Consumidor Final (B2C)" },
  "Contas a Pagar": { en: "Accounts Payable", es: "Cuentas por Pagar" },
  "Contas a Receber": { en: "Accounts Receivable", es: "Cuentas por Cobrar" },
  "Criar novo orçamento para este cliente": { en: "Create new quote for this customer", es: "Crear nuevo presupuesto para este cliente" },
  "Custo Operacional": { en: "Operating Cost", es: "Coste Operativo" },
  "Custo das Mercadorias Vendidas (CMV)": { en: "Cost of Goods Sold (COGS)", es: "Coste de Ventas (COGS)" },
  "Custos": { en: "Costs", es: "Costes" },
  "Dados de Identificação": { en: "Identification Details", es: "Datos de Identificación" },
  "Data de Liquidação": { en: "Settlement Date", es: "Fecha de Liquidación" },
  "Demonstrativo de Resultados (DRE)": { en: "P&L Statement (Income Statement)", es: "Estado de Resultados (Pérdidas y Ganancias)" },
  "Despesas Fixas": { en: "Fixed Expenses", es: "Gastos Fijos" },
  "Despesas Operacionais": { en: "Operating Expenses", es: "Gastos Operativos" },
  "Digite o CNPJ da empresa...": { en: "Enter company tax ID...", es: "Ingrese el CIF/NIF de la empresa..." },
  "Dinheiro em Espécie": { en: "Cash", es: "Efectivo" },
  "Editar Cadastro": { en: "Edit Profile", es: "Editar Registro" },
  "Editar Lançamento": { en: "Edit Transaction", es: "Editar Asiento" },
  "Empresa / Parceiro (B2B)": { en: "Company / Partner (B2B)", es: "Empresa / Socio (B2B)" },
  "Entradas do Mês": { en: "Monthly Inflows", es: "Entradas del Mes" },
  "Erro ao atualizar lançamento. Alteração revertida.": { en: "Error updating transaction. Changes reverted.", es: "Error al actualizar asiento. Cambio revertido." },
  "Erro ao carregar clientes.": { en: "Error loading clients.", es: "Error al cargar clientes." },
  "Erro ao carregar dados financeiros.": { en: "Error loading financial data.", es: "Error al cargar datos financieros." },
  "Erro ao consultar CNPJ via BrasilAPI.": { en: "Error looking up tax ID via BrasilAPI.", es: "Error al consultar empresa vía BrasilAPI." },
  "Erro ao registrar lançamento. Alteração revertida.": { en: "Error recording transaction. Changes reverted.", es: "Error al registrar asiento. Cambio revertido." },
  "Erro ao remover cliente. Alteração revertida.": { en: "Error deleting client. Changes reverted.", es: "Error al eliminar cliente. Cambio revertido." },
  "Erro ao remover lançamento. Alteração revertida.": { en: "Error removing transaction. Changes reverted.", es: "Error al eliminar asiento. Cambio revertido." },
  "Erro ao salvar cliente. Alteração revertida.": { en: "Error saving client. Changes reverted.", es: "Error al guardar cliente. Cambio revertido." },
  "Erro ao validar dados do cliente.": { en: "Error validating client data.", es: "Error al validar datos del cliente." },
  "Estatísticas & Histórico": { en: "Stats & History", es: "Estadísticas e Historial" },
  "Estresse seu DRE e veja o impacto financeiro no Saldo Livre.": { en: "Stress-test your Income Statement and see the impact on Free Balance.", es: "Haga una prueba de estrés en su Estado de Resultados y vea el impacto en el Saldo Libre." },
  "Evolução de receitas e despesas": { en: "Revenue and expenses trend", es: "Evolución de ingresos y gastos" },
  "Ex: Gosta de peças em resina, prefere retirada, costuma pedir brindes...": { en: "e.g.: Prefers resin parts, in-person pickup, often asks for giveaways...", es: "Ej: Prefiere piezas en resina, recogida en persona, suele pedir muestras..." },
  "Ex: Instagram, Mercado Livre...": { en: "e.g.: Instagram, Etsy, Shopify...", es: "Ej: Instagram, Mercado Libre..." },
  "Ex: João Silva": { en: "e.g.: John Doe", es: "Ej: Juan Pérez" },
  "Ex: Venda de Action Figure, Compra de Bico 0.4...": { en: "e.g.: Action Figure Sale, 0.4 Nozzle Purchase...", es: "Ej: Venta de Figura de Acción, Compra de Boquilla 0.4..." },
  "Excluir Lançamento": { en: "Delete Transaction", es: "Eliminar Asiento" },
  "Exportar Lançamentos em CSV": { en: "Export Transactions to CSV", es: "Exportar Movimientos a CSV" },
  "Falha ao carregar clientes": { en: "Failed to load clients", es: "Fallo al cargar clientes" },
  "Falha ao carregar dados financeiros": { en: "Failed to load financial data", es: "Fallo al cargar datos financeiros" },
  "Falha ao registrar lançamento.": { en: "Failed to record transaction.", es: "Fallo al registrar el movimiento." },
  "Filtrar por período": { en: "Filter by period", es: "Filtrar por período" },
  "Fluxo Financeiro": { en: "Financial Flow", es: "Flujo Financiero" },
  "Fluxo de Caixa": { en: "Cash Flow", es: "Flujo de Caja" },
  "Fluxo de caixa vazio": { en: "Empty cash flow", es: "Flujo de caja vacío" },
  "Forma de Recebimento": { en: "Payment Receiving Method", es: "Forma de Cobro" },
  "IA Lab": { en: "AI Lab", es: "Laboratorio IA" },
  "Indicador": { en: "Indicator", es: "Indicador" },
  "Lançamento atualizado!": { en: "Transaction updated!", es: "¡Asiento actualizado!" },
  "Lançamento excluído com sucesso.": { en: "Transaction deleted successfully.", es: "Movimiento eliminado con éxito." },
  "Lançamento registrado com sucesso!": { en: "Transaction recorded successfully!", es: "¡Movimiento registrado con éxito!" },
  "Lançamento registrado!": { en: "Transaction recorded!", es: "¡Asiento registrado!" },
  "Lançamento removido.": { en: "Transaction removed.", es: "Asiento eliminado." },
  "Lançar no Financeiro": { en: "Post to Finances", es: "Registrar en Finanzas" },
  "Lead": { en: "Lead", es: "Lead" },
  "Lucratividade": { en: "Profitability", es: "Rentabilidad" },
  "Lucro Simulado Projetado": { en: "Projected Simulated Profit", es: "Beneficio Simulado Proyectado" },
  "Margem Operacional": { en: "Operating Margin", es: "Margen Operativo" },
  "Markup sugerido de 3.0x": { en: "Suggested 3.0x markup", es: "Markup sugerido de 3.0x" },
  "Markup sugerido de 5.0x": { en: "Suggested 5.0x markup", es: "Markup sugerido de 5.0x" },
  "Nenhum cliente encontrado": { en: "No customers found", es: "No se encontraron clientes" },
  "Nenhum lançamento filtrado": { en: "No filtered transactions", es: "Ningún asiento filtrado" },
  "Nenhum pedido encontrado": { en: "No orders found", es: "No se encontraron pedidos" },
  "Nenhuma transação registrada.": { en: "No transactions recorded.", es: "Ninguna transacción registrada." },
  "Notas e CRM": { en: "Notes & CRM", es: "Notas y CRM" },
  "Nova Rentabilidade:": { en: "New Profitability:", es: "Nueva Rentabilidad:" },
  "Não foi possível carregar o histórico de pedidos deste cliente.": { en: "Unable to load order history for this customer.", es: "No se pudo cargar el historial de pedidos de este cliente." },
  "Opções do cliente": { en: "Customer options", es: "Opciones del cliente" },
  "Pedidos Realizados": { en: "Orders Placed", es: "Pedidos Realizados" },
  "Perfil Comercial do Cliente": { en: "Customer Commercial Profile", es: "Perfil Comercial del Cliente" },
  "Performance de Lucro": { en: "Profit Performance", es: "Rendimiento de Beneficio" },
  "Pesquisar parceiro...": { en: "Search partner...", es: "Buscar socio..." },
  "Ponto de Equilíbrio": { en: "Break-even Point", es: "Punto de Equilibrio" },
  "Preenchimento Automático via CNPJ": { en: "Autofill via Tax ID", es: "Relleno Automático vía Identificación Fiscal" },
  "Receita Bruta": { en: "Gross Revenue", es: "Ingresos Brutos" },
  "Receita Bruta (Faturamento)": { en: "Gross Revenue", es: "Ingresos Brutos (Facturación)" },
  "Receita Líquida": { en: "Net Revenue", es: "Ingresos Netos" },
  "Receitas Operacionais": { en: "Operating Revenue", es: "Ingresos Operativos" },
  "Remover Cliente": { en: "Remove Customer", es: "Eliminar Cliente" },
  "Resultado Operacional": { en: "Operating Result", es: "Resultado Operativo" },
  "Simulador de Margem DRE": { en: "Income Statement Margin Simulator", es: "Simulador de Margen DRE" },
  "Token de Consentimento (Hash ID)": { en: "Consent Token (Hash ID)", es: "Token de Consentimiento (Hash ID)" },
  "Total Custos Variáveis (COGS)": { en: "Total Variable Costs (COGS)", es: "Total Costes Variables (COGS)" },
  "Transferência / PIX": { en: "Bank Transfer / PIX", es: "Transferencia / PIX" },
  "Valor Total Gasto (LTV)": { en: "Total Spent Value (LTV)", es: "Valor Total Gastado (LTV)" },
  "Vencimento": { en: "Due Date", es: "Vencimiento" },
  "Vendas, Peças, Fixos...": { en: "Sales, Parts, Overheads...", es: "Ventas, Piezas, Fijos..." },
  "Ver Histórico": { en: "View History", es: "Ver Historial" },
  "Último Pedido": { en: "Last Order", es: "Último Pedido" },
};
