import { DicionarioTraducao } from "./tipos";

export const dicionarioPainel: DicionarioTraducao = {
  "Ações Rápidas": { en: "Quick Actions", es: "Acciones Rápidas" },
  "ARMAZÉM DE INSUMOS": { en: "SUPPLIES WAREHOUSE", es: "ALMACÉN DE INSUMOS" },
  "ARMAZÉM DE MATERIAIS": { en: "MATERIALS WAREHOUSE", es: "ALMACÉN DE MATERIALES" },
  "Carregando gráfico de consumo...": { en: "Loading consumption chart...", es: "Cargando gráfico de consumo..." },
  "Consumo Semanal": { en: "Weekly Consumption", es: "Consumo Semanal" },
  "ELETRÔNICA": { en: "ELECTRONICS", es: "ELECTRÓNICA" },
  "EM CURSO": { en: "IN PROGRESS", es: "EN CURSO" },
  "EM REVISÃO": { en: "UNDER REVIEW", es: "EN REVISIÓN" },
  "Entrada / Saída": { en: "Inflow / Outflow", es: "Entrada / Salida" },
  "Falha ao sincronizar dados do painel.": { en: "Failed to synchronize dashboard data.", es: "Fallo al sincronizar datos del panel." },
  "FARM": { en: "FARM", es: "FARM" },
  "Filamentos & Resinas": { en: "Filaments & Resins", es: "Filamentos y Resinas" },
  "FIXAÇÃO": { en: "FASTENERS", es: "FIJACIÓN" },
  "Fluxo MP": { en: "Raw Material Flow", es: "Flujo MP" },
  "Insumos Técnicos": { en: "Technical Supplies", es: "Insumos Técnicos" },
  "Lançar Despesa": { en: "Record Expense", es: "Registrar Gasto" },
  "Lançar Receita": { en: "Record Income", es: "Registrar Ingreso" },
  "Live Monitor": { en: "Live Monitor", es: "Monitor en Vivo" },
  "Materiais Brutos": { en: "Raw Materials", es: "Materiales Brutos" },
  "Não foi possível ativar seu plano agora.": { en: "Unable to activate your plan right now.", es: "No fue posible activar su plan ahora." },
  "Nenhum registro": { en: "No records found", es: "Ningún registro" },
  "Nenhum registro ainda": { en: "No records yet", es: "Ningún registro aún" },
  "NOVO CADASTRO MAKER": { en: "NEW MAKER ENTRY", es: "NUEVO REGISTRO MAKER" },
  "Novo Cliente": { en: "New Customer", es: "Nuevo Cliente" },
  "Novo Projeto": { en: "New Project", es: "Nuevo Proyecto" },
  "Orçamentos Recentes": { en: "Recent Quotes", es: "Presupuestos Recientes" },
  "Para fortalecer a comunidade.": { en: "To empower the community.", es: "Para fortalecer a la comunidad." },
  "Parabéns! Agora você é um MAKER FUNDADOR vitalício ✨": { en: "Congratulations! You are now a lifetime FOUNDING MAKER ✨", es: "¡Felicidades! Ahora es un MAKER FUNDADOR vitalicio ✨" },
  "Patrimônio Total Geral": { en: "Grand Total Assets", es: "Patrimonio Total General" },
  "PRONTA": { en: "READY", es: "LISTA" },
  "Pronta / Livre": { en: "Ready / Idle", es: "Lista / Libre" },
  "Real-time": { en: "Real-time", es: "Tiempo real" },
  "REGISTRO FINANCEIRO": { en: "FINANCIAL RECORD", es: "REGISTRO FINANCIERO" },
  "Relação de Ativos": { en: "Asset Breakdown", es: "Relación de Activos" },
  "Sistemas Online": { en: "Systems Online", es: "Sistemas en Línea" },
  "Tempo Real": { en: "Real Time", es: "Tiempo Real" },
  "Valor Final": { en: "Final Value", es: "Valor Final" },
  "Valores baseados no preço de aquisição": { en: "Values based on acquisition cost", es: "Valores basados en el coste de adquisición" },
  "VER TODOS": { en: "VIEW ALL", es: "VER TODOS" },
  "Você precisa verificar seu e-mail no Perfil antes de ativar este plano.": { en: "You must verify your email in Profile before activating this plan.", es: "Debe verificar su correo en el Perfil antes de activar este plan." },
};
